import {api, LightningElement, track} from 'lwc';

export default class ExampleQuanticNotifications extends LightningElement {
  @api engineId = 'quantic-notifications-engine';
  @track config = {};
  isConfigured = false;

  pageTitle = 'Quantic Notifications';
  pageDescription =
    'component is responsible for displaying notifications generated by the Coveo Search API.';
  options = [
    {
      attribute: 'useCase',
      label: 'Use Case',
      description:
        'Define which use case to test. Possible values are: search, insights',
      defaultValue: 'search',
    },
  ];

  get notConfigured() {
    return !this.isConfigured;
  }

  handleTryItNow(evt) {
    this.config = evt.detail;
    this.isConfigured = true;
  }
}
