// This file is generated by postcss-build.cjs
import dep0 from '../../../global/global.css';

const css = `.value-count{color:var(--atomic-neutral-dark);margin-left:.375rem}[part=value-exclude-button]+.value-count{margin-right:.5rem}:host(.popover-nested){min-width:18rem}:host(.popover-nested)::part(label-button){display:none}:host(.popover-nested)::part(facet){--tw-shadow:0 10px 15px -3px rgba(0,0,0,.1),0 4px 6px -4px rgba(0,0,0,.1);--tw-shadow-colored:0 10px 15px -3px var(--tw-shadow-color),0 4px 6px -4px var(--tw-shadow-color);box-shadow:var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow)}:host(.popover-nested)::part(values){margin-top:0;max-height:24rem;overflow-y:auto}:host(.popover-nested)::part(search-wrapper){margin-bottom:.5rem}`;
const allCss: string[] = [...dep0, css];
export default allCss;
