// This file is generated by postcss-build.cjs
import dep0 from '../../../global/global.css';
import dep1 from './facet-common.css';
import dep2 from './facet-value-checkbox/facet-value-checkbox.css';
import dep3 from './facet-value-exclude/facet-value-exclude.css';

const css = ``;
const allCss: string[] = [...dep0, ...dep1, ...dep2, ...dep3, css];
export default allCss;
