apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: headless-react
  title: '@coveo/headless-react'
  description: React utilities for SSR (Server Side Rendering) with headless
  annotations:
    github.com/project-slug: coveo/ui-kit
spec:
  type: library
  lifecycle: production
  owner: group:default/dxui
  system: ui-kit
  dependsOn:
    - headless
