name: Setup
description: Install Node and PNPM
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org"
        package-manager-cache: false
    - name: Setup pnpm
      shell: bash
      run: |
        corepack enable
        corepack prepare --activate
