// This file is generated by postcss-build.cjs

const css = `.ripple{animation:ripple var(--animation-duration) linear;border-radius:50%;pointer-events:none;position:absolute;transform:scale(0)}.ripple-relative{position:relative}.ripple-parent{overflow:hidden}@keyframes ripple{to{opacity:0;transform:scale(4)}}`;
const allCss: string[] = [css];
export default allCss;
