// Sample recommendations response based on the fashioncoveodemo API
export const baseRecommendationResponse = {
  totalCount: 3339,
  totalCountFiltered: 3339,
  duration: 2,
  indexDuration: 6,
  requestDuration: 1,
  searchUid: 'aa347948-217f-49f0-b1b5-b2f7a0fc94c9',
  pipeline: 'Recommendations',
  apiVersion: 2,
  queryCorrections: [],
  index: 'cache',
  logicalIndex: 'default',
  refinedKeywords: [],
  triggers: [],
  termsToHighlight: {},
  phrasesToHighlight: {},
  groupByResults: [],
  facets: [],
  suggestedFacets: [],
  categoryFacets: [],
  results: [
    {
      title: 'Be Long Gray Beanie',
      uri: 'https://fashion.coveodemo.com/pdp/033315601_LMG',
      printableUri: 'https://fashion.coveodemo.com/pdp/033315601_LMG',
      clickUri: 'https://fashion.coveodemo.com/pdp/033315601_LMG',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/033315601_LMG',
      excerpt:
        "Be long gray beanie by brekka The Brekka Be Long hat made of soft acrylic is a reversible beanie that ensures ... It 'available in several neutral colors and trendy including gray.",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://thegym-assets.coveodemo.com/images_450x600/b3ff629f-e6cb-5004-a65f-23d1c284d91c.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/c2618156-b5b4-5649-915e-393977d940a2.jpg',
        ],
        sysauthor: 'TheGym',
        sysurihash: 'wdg41NNTjðjyehC1',
        urihash: 'wdg41NNTjðjyehC1',
        cat_rating_count: 0,
        permanentid: '033315601_LMG',
        syslanguage: ['English'],
        ec_brand: 'Brekka',
        date: 1696079831000,
        objecttype: 'Product',
        ec_name: 'Be Long Gray Beanie',
        syssource: 'Products',
        sysdate: 1696079831000,
        author: 'TheGym',
        ec_item_group_id: 'BRFK0015',
        ec_category: ['Men', 'Men|Hats'],
        source: 'Products',
        ec_price: 9.95,
        ec_description:
          "The Brekka Be Long hat made of soft acrylic is a reversible beanie that ensures comfort and protection. It 'available in several neutral colors and trendy including gray.",
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 9.95,
        syscollection: 'default',
      },
      Title: 'Be Long Gray Beanie',
      Uri: 'https://fashion.coveodemo.com/pdp/033315601_LMG',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/033315601_LMG',
      ClickUri: 'https://fashion.coveodemo.com/pdp/033315601_LMG',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/033315601_LMG',
      Excerpt:
        "Be long gray beanie by brekka The Brekka Be Long hat made of soft acrylic is a reversible beanie that ensures ... It 'available in several neutral colors and trendy including gray.",
      FirstSentences: null,
    },
    {
      title: 'Logo Institutional Hoodie',
      uri: 'https://fashion.coveodemo.com/pdp/038132401_402',
      printableUri: 'https://fashion.coveodemo.com/pdp/038132401_402',
      clickUri: 'https://fashion.coveodemo.com/pdp/038132401_402',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/038132401_402',
      excerpt:
        "LOGO INSTITUTIONAL HOODIE by calvin klein jeans The sweater Calvin Klein men's hooded Institutional is the institutional model of brand.",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://thegym-assets.coveodemo.com/images_450x600/346bbee7-fa36-5de2-9a8d-8e63e66e09e3.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/131260ce-6ccd-5d11-b0d9-b3104d63240c.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/fd47cbbf-dfa4-5ed0-8fbb-baf293207e01.jpg',
        ],
        sysauthor: 'TheGym',
        sysurihash: 'HlLycDFK6ZMmd3nK',
        urihash: 'HlLycDFK6ZMmd3nK',
        cat_rating_count: 0,
        permanentid: '038132401_402',
        syslanguage: ['English'],
        ec_brand: 'Calvin Klein Jeans',
        date: 1696079831000,
        objecttype: 'Product',
        ec_name: 'Logo Institutional Hoodie',
        syssource: 'Products',
        sysdate: 1696079831000,
        author: 'TheGym',
        ec_item_group_id: 'J30J309528402',
        ec_category: ['Men', 'Men|Sweatshirts'],
        source: 'Products',
        ec_price: 58.8,
        ec_description:
          "The sweater Calvin Klein men's hooded Institutional is the institutional model of brand.",
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 58.8,
        syscollection: 'default',
      },
      Title: 'Logo Institutional Hoodie',
      Uri: 'https://fashion.coveodemo.com/pdp/038132401_402',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/038132401_402',
      ClickUri: 'https://fashion.coveodemo.com/pdp/038132401_402',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/038132401_402',
      Excerpt:
        "LOGO INSTITUTIONAL HOODIE by calvin klein jeans The sweater Calvin Klein men's hooded Institutional is the institutional model of brand.",
      FirstSentences: null,
    },
    {
      title: "Eastfall Women's Jacket",
      uri: 'https://fashion.coveodemo.com/pdp/034787501_962',
      printableUri: 'https://fashion.coveodemo.com/pdp/034787501_962',
      clickUri: 'https://fashion.coveodemo.com/pdp/034787501_962',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/034787501_962',
      excerpt:
        "Eastfall women's Jacket by burton The snowboard jacket from Burton Eastfall woman, clean and classic look for one of the most popular jackets in the range.",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://thegym-assets.coveodemo.com/images_450x600/b53f2cd4-8fa3-51c3-9a91-a6352aea80e0.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/fa938068-1533-54ef-b4cb-aa4356dbccc4.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/79ed9aeb-36f2-5039-853e-d773e2c907f9.jpg',
        ],
        sysauthor: 'TheGym',
        sysurihash: 'riIEqvHaNðQvkBNn',
        urihash: 'riIEqvHaNðQvkBNn',
        cat_rating_count: 0,
        permanentid: '034787501_962',
        syslanguage: ['English'],
        ec_brand: 'Burton',
        date: 1696079831000,
        objecttype: 'Product',
        ec_name: "Eastfall Women's Jacket",
        syssource: 'Products',
        sysdate: 1696079831000,
        author: 'TheGym',
        ec_item_group_id: '150191',
        ec_category: ['Women', 'Women|Jackets'],
        source: 'Products',
        ec_price: 115.0,
        ec_description:
          'The snowboard jacket from Burton Eastfall woman, clean and classic look for one of the most popular jackets in the range.',
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 103.5,
        syscollection: 'default',
      },
      Title: "Eastfall Women's Jacket",
      Uri: 'https://fashion.coveodemo.com/pdp/034787501_962',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/034787501_962',
      ClickUri: 'https://fashion.coveodemo.com/pdp/034787501_962',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/034787501_962',
      Excerpt:
        "Eastfall women's Jacket by burton The snowboard jacket from Burton Eastfall woman, clean and classic look for one of the most popular jackets in the range.",
      FirstSentences: null,
    },
    {
      title: 'Og Logo Curved Visor Cap',
      uri: 'https://fashion.coveodemo.com/pdp/037053301_2001',
      printableUri: 'https://fashion.coveodemo.com/pdp/037053301_2001',
      clickUri: 'https://fashion.coveodemo.com/pdp/037053301_2001',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/037053301_2001',
      excerpt:
        "OG LOGO CURVED VISOR CAP by huf Huf 71418A054E Hat Og Logo Curved Visor Men's Fashion",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://thegym-assets.coveodemo.com/images_450x600/c201f7fe-817a-506b-8c9f-7e34dbd823f7.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/dcfabca5-197e-53fa-a620-4e754c452d30.jpg',
        ],
        sysauthor: 'TheGym',
        sysurihash: 'LnywBSa0U9GcufMb',
        urihash: 'LnywBSa0U9GcufMb',
        cat_rating_count: 0,
        permanentid: '037053301_2001',
        syslanguage: ['Danish', 'English'],
        ec_brand: 'Huf',
        date: 1696079830000,
        objecttype: 'Product',
        ec_name: 'Og Logo Curved Visor Cap',
        syssource: 'Products',
        sysdate: 1696079830000,
        author: 'TheGym',
        ec_item_group_id: '71418A054E',
        ec_category: ['Men', 'Men|Hats'],
        source: 'Products',
        ec_price: 33.6,
        ec_description: "Huf 71418A054E Hat Og Logo Curved Visor Men's Fashion",
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['Danish', 'English'],
        ec_promo_price: 33.6,
        syscollection: 'default',
      },
      Title: 'Og Logo Curved Visor Cap',
      Uri: 'https://fashion.coveodemo.com/pdp/037053301_2001',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/037053301_2001',
      ClickUri: 'https://fashion.coveodemo.com/pdp/037053301_2001',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/037053301_2001',
      Excerpt:
        "OG LOGO CURVED VISOR CAP by huf Huf 71418A054E Hat Og Logo Curved Visor Men's Fashion",
      FirstSentences: null,
    },
    {
      title: 'Soft-Washed V-Neck Tee for Men',
      uri: 'https://fashion.coveodemo.com/pdp/712308_927',
      printableUri: 'https://fashion.coveodemo.com/pdp/712308_927',
      clickUri: 'https://fashion.coveodemo.com/pdp/712308_927',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/712308_927',
      excerpt:
        "Soft-Washed V-Neck Tee for Men - 712308_927 11.99 $ ... Short sleeves. Soft-washed jersey for the ultimate in softness. We put it through the wringer, so you don't have to.",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://images.coveodemo.com/fashion/712308_cn11736858.jpg',
          'https://images.coveodemo.com/fashion/712308_cn14757234.jpg',
          'https://images.coveodemo.com/fashion/712308_cn14755794.jpg',
        ],
        sysurihash: 'Iu6hue6e7SfdhhC2',
        urihash: 'Iu6hue6e7SfdhhC2',
        cat_rating_count: 423,
        ec_rating: 4.72,
        permanentid: '712308_927',
        syslanguage: ['English'],
        ec_brand: 'Old Navy',
        date: 1696079830000,
        objecttype: 'Product',
        ec_name: 'Soft-Washed V-Neck Tee for Men',
        syssource: 'Products',
        sysdate: 1696079830000,
        ec_item_group_id: '712308',
        ec_category: ['Men', 'Men|T-Shirts & Polo Shirts'],
        source: 'Products',
        ec_price: 11.99,
        ec_description:
          "V-neck. Short sleeves. Soft-washed jersey for the ultimate in softness. We put it through the wringer, so you don't have to. Tag-free label and pieced trim inside neck and shoulders for added comfort & durability.",
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 11.99,
        syscollection: 'default',
      },
      Title: 'Soft-Washed V-Neck Tee for Men',
      Uri: 'https://fashion.coveodemo.com/pdp/712308_927',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/712308_927',
      ClickUri: 'https://fashion.coveodemo.com/pdp/712308_927',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/712308_927',
      Excerpt:
        "Soft-Washed V-Neck Tee for Men - 712308_927 11.99 $ ... Short sleeves. Soft-washed jersey for the ultimate in softness. We put it through the wringer, so you don't have to.",
      FirstSentences: null,
    },
    {
      title: "Annika Women's Faux Leather Skirt",
      uri: 'https://fashion.coveodemo.com/pdp/034491701_8002',
      printableUri: 'https://fashion.coveodemo.com/pdp/034491701_8002',
      clickUri: 'https://fashion.coveodemo.com/pdp/034491701_8002',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/034491701_8002',
      excerpt:
        "Annika women's faux leather skirt by minimum 96417ANNIKA Skirt Satin Annika Women's Ladies Wear",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://thegym-assets.coveodemo.com/images_450x600/4039a461-c781-5923-97c9-0595f70841ab.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/6fb3fc9a-8135-52b7-a9f0-cc8be07f5ed7.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/abe40195-e26d-56b6-a588-95330fc19a30.jpg',
        ],
        sysauthor: 'TheGym',
        sysurihash: 'ZebPñlz1GETCmKTO',
        urihash: 'ZebPñlz1GETCmKTO',
        cat_rating_count: 0,
        permanentid: '034491701_8002',
        syslanguage: ['English'],
        ec_brand: 'Minimum',
        date: 1696079830000,
        objecttype: 'Product',
        ec_name: "Annika Women's Faux Leather Skirt",
        syssource: 'Products',
        sysdate: 1696079830000,
        author: 'TheGym',
        ec_item_group_id: '96417ANNIKA',
        ec_category: ['Women', 'Women|Skirts and Dresses'],
        source: 'Products',
        ec_price: 29.95,
        ec_description: "96417ANNIKA Skirt Satin Annika Women's Ladies Wear",
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 29.95,
        syscollection: 'default',
      },
      Title: "Annika Women's Faux Leather Skirt",
      Uri: 'https://fashion.coveodemo.com/pdp/034491701_8002',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/034491701_8002',
      ClickUri: 'https://fashion.coveodemo.com/pdp/034491701_8002',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/034491701_8002',
      Excerpt:
        "Annika women's faux leather skirt by minimum 96417ANNIKA Skirt Satin Annika Women's Ladies Wear",
      FirstSentences: null,
    },
    {
      title: 'Mid-Rise Utility Pixie Ankle Chinos for Women',
      uri: 'https://fashion.coveodemo.com/pdp/220786_005',
      printableUri: 'https://fashion.coveodemo.com/pdp/220786_005',
      clickUri: 'https://fashion.coveodemo.com/pdp/220786_005',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/220786_005',
      excerpt:
        'Mid-Rise Utility Pixie Ankle Chinos for Women - 220786_005 39.99 $ Double hook-and-bar closure, with interior button closure. Zip fly. ... Mid-rise sits below waist. ... Camo',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://images.coveodemo.com/fashion/220786_cn15572647.jpg',
          'https://images.coveodemo.com/fashion/220786_cn15572654.jpg',
          'https://images.coveodemo.com/fashion/220786_cn15563268.jpg',
        ],
        sysurihash: 'IDo8htedUtoY2q7j',
        urihash: 'IDo8htedUtoY2q7j',
        cat_rating_count: 177,
        ec_rating: 4.73,
        permanentid: '220786_005',
        syslanguage: ['English'],
        ec_brand: 'Old Navy',
        date: 1696079829000,
        objecttype: 'Product',
        ec_name: 'Mid-Rise Utility Pixie Ankle Chinos for Women',
        syssource: 'Products',
        sysdate: 1696079829000,
        ec_item_group_id: '220786',
        ec_category: ['Women', 'Women|Pants'],
        source: 'Products',
        ec_price: 39.99,
        ec_description:
          'Double hook-and-bar closure, with interior button closure. Zip fly. Slant utility pockets in front; patch pockets in back.',
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 32.0,
        syscollection: 'default',
      },
      Title: 'Mid-Rise Utility Pixie Ankle Chinos for Women',
      Uri: 'https://fashion.coveodemo.com/pdp/220786_005',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/220786_005',
      ClickUri: 'https://fashion.coveodemo.com/pdp/220786_005',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/220786_005',
      Excerpt:
        'Mid-Rise Utility Pixie Ankle Chinos for Women - 220786_005 39.99 $ Double hook-and-bar closure, with interior button closure. Zip fly. ... Mid-rise sits below waist. ... Camo',
      FirstSentences: null,
    },
    {
      title: 'Nick Cargo Bermuda Shorts',
      uri: 'https://fashion.coveodemo.com/pdp/037552801_W2096',
      printableUri: 'https://fashion.coveodemo.com/pdp/037552801_W2096',
      clickUri: 'https://fashion.coveodemo.com/pdp/037552801_W2096',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/037552801_W2096',
      excerpt:
        'NICK cargo bermuda shorts by 40weft The Bermuda shorts with pockets 40WEFT Nick are the iconic model of the best-known and ... They also zip and button and belt loops for a regular.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://thegym-assets.coveodemo.com/images_450x600/112ffeae-910b-5d00-8386-0dcabf32b425.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/dcff6d2d-25e1-5509-b642-5505a28108ab.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/5fbc957d-9a6f-53a1-996b-8e6b7130cd09.jpg',
        ],
        sysauthor: 'TheGym',
        sysurihash: '7B1L0TIfAncXMKLv',
        urihash: '7B1L0TIfAncXMKLv',
        cat_rating_count: 0,
        permanentid: '037552801_W2096',
        syslanguage: ['English'],
        ec_brand: '40Weft',
        date: 1696079829000,
        objecttype: 'Product',
        ec_name: 'Nick Cargo Bermuda Shorts',
        syssource: 'Products',
        sysdate: 1696079829000,
        author: 'TheGym',
        ec_item_group_id: '3746',
        ec_category: ['Men', 'Men|Shorts'],
        source: 'Products',
        ec_price: 59.95,
        ec_description:
          'The Bermuda shorts with pockets 40WEFT Nick are the iconic model of the best-known and appreciated brand.',
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 39.95,
        syscollection: 'default',
      },
      Title: 'Nick Cargo Bermuda Shorts',
      Uri: 'https://fashion.coveodemo.com/pdp/037552801_W2096',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/037552801_W2096',
      ClickUri: 'https://fashion.coveodemo.com/pdp/037552801_W2096',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/037552801_W2096',
      Excerpt:
        'NICK cargo bermuda shorts by 40weft The Bermuda shorts with pockets 40WEFT Nick are the iconic model of the best-known and ... They also zip and button and belt loops for a regular.',
      FirstSentences: null,
    },
    {
      title: 'Pacesetter Storm Packable Jacket',
      uri: 'https://fashion.coveodemo.com/pdp/038090101_731',
      printableUri: 'https://fashion.coveodemo.com/pdp/038090101_731',
      clickUri: 'https://fashion.coveodemo.com/pdp/038090101_731',
      uniqueId: '42.33851$https://fashion.coveodemo.com/pdp/038090101_731',
      excerpt:
        'PACESETTER STORM PACKABLE JACKET by under armour The jacket running Under Armor Pacesetter Packable Storm is the perfect product for all those who do not want to let runner stop by ...',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;SkipSentencesScoring',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 86,
      percentScore: 20.867271,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        ec_images: [
          'https://thegym-assets.coveodemo.com/images_450x600/30bb9bc8-0e1c-5f4f-87a9-7a4bd0a246e3.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/544b58eb-1eeb-58bd-bb68-ab00d6a9f331.jpg',
          'https://thegym-assets.coveodemo.com/images_450x600/e1d93f03-6451-5a49-9943-ab3f1ca1cae7.jpg',
        ],
        sysauthor: 'TheGym',
        sysurihash: 'fce1fzL1osDðRhxð',
        urihash: 'fce1fzL1osDðRhxð',
        cat_rating_count: 0,
        permanentid: '038090101_731',
        syslanguage: ['English'],
        ec_brand: 'Under Armour',
        date: 1696079829000,
        objecttype: 'Product',
        ec_name: 'Pacesetter Storm Packable Jacket',
        syssource: 'Products',
        sysdate: 1696079829000,
        author: 'TheGym',
        ec_item_group_id: '1326597',
        ec_category: ['Men', 'Men|Jackets'],
        source: 'Products',
        ec_price: 73.5,
        ec_description:
          'The jacket running Under Armor Pacesetter Packable Storm is the perfect product for all those who do not want to let runner stop by bad weather.',
        collection: 'default',
        filetype: 'html',
        sysfiletype: 'html',
        language: ['English'],
        ec_promo_price: 73.5,
        syscollection: 'default',
      },
      Title: 'Pacesetter Storm Packable Jacket',
      Uri: 'https://fashion.coveodemo.com/pdp/038090101_731',
      PrintableUri: 'https://fashion.coveodemo.com/pdp/038090101_731',
      ClickUri: 'https://fashion.coveodemo.com/pdp/038090101_731',
      UniqueId: '42.33851$https://fashion.coveodemo.com/pdp/038090101_731',
      Excerpt:
        'PACESETTER STORM PACKABLE JACKET by under armour The jacket running Under Armor Pacesetter Packable Storm is the perfect product for all those who do not want to let runner stop by ...',
      FirstSentences: null,
    },
  ],
  extendedResults: {},
};
