apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "@coveo/atomic-react"
  description: React specific wrapper for the Atomic component library
  annotations:
    github.com/project-slug: coveo/ui-kit
spec:
  type: library
  lifecycle: production
  owner: dxui
  dependsOn:
    - "@coveo/atomic"
    - "@coveo/headless"