apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: atomic-react
  title: '@coveo/atomic-react'
  description: React specific wrapper for the Atomic component library
spec:
  type: library
  lifecycle: production
  owner: group:default/dxui
  system: ui-kit
  dependsOn:
    - component:atomic
    - component:headless
