apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ui-kit
  title: ui-kit
  description: Monorepo for Coveo UI packages, shared tooling, and release workflows
  annotations:
    github.com/project-slug: coveo/ui-kit
spec:
  owner: group:default/dxui
