export default {
  $schema: 'https://unpkg.com/knip@6/schema.json',
  // Always ignoring quantic since it throws errors. Adding those two lines is necessary for 100% of quantic to be ignored.
  ignoreWorkspaces: ['packages/quantic', 'packages/create-atomic-component-project/template'],
  ignoreDependencies: ['semver'],
  ignore: [
    '.agents/skills/**',
    '.github/actions/run-affected/test-resolve-tasks.mjs',
    'packages/quantic/**',
    'samples/headless/rga-react/src/components/Quickstart.tsx',
    'samples/headless/rga-react/src/components/Citation.tsx',
    'samples/headless/rga-react/src/components/CitationsList.tsx',
    'packages/pkg-new-template/**',
  ],
  compilers: {
    // Enable the built-in MDX compiler so Knip can trace imports inside .mdx
    // Storybook docs pages (e.g. storybook-utils helpers).
    mdx: true,
  },
  workspaces: {
    '.': {
      entry: ['scripts/**/*.{js,mjs}'],
      ignoreBinaries: ['ts-node'],
      ignoreDependencies: ['@playwright/mcp'],
    },
    'packages/headless': {
      entry: ['src/*index.ts', 'ponyfills/*.js'],
      ignoreDependencies: ['reselect', 'node-fetch'],
    },
    'packages/atomic-hosted-page': {
      entry: ['src/atomic-hosted-page.esm.ts', 'dev/vite.config.ts'],
    },
    'packages/atomic-theming-e2e': {
      entry: ['tests/**/*.spec.ts', 'fixtures/*.js'],
    },
    'packages/atomic-angular': {
      ignoreDependencies: [
        // Can be removed once we bump our package to use more recent Angular versions that support Vite 7+.
        'vite',
        'rxjs', // Used by generated Angular wrapper; Knip can't trace it.
      ],
    },
    'packages/atomic-angular/projects/atomic-angular': {
      entry: ['src/public-api.ts'],
      ignore: [
        'src/utils.ts', // Only used by generated files, so it 'seems' to have unused exports, but it's actually used.
      ],
    },
    'packages/atomic-react': {
      entry: ['src/*index.ts'],
      ignoreDependencies: [
        '@lit/react', // Only used in generated files.
      ],
    },
    'packages/headless-react': {
      // @types/react is an optional peer dep but referenced in source — consumers
      // provide it, so we suppress the knip warning.
      ignoreDependencies: ['@types/react'],
    },
    'packages/relay': {
      entry: ['src/relay.ts', 'config/rollup.config.mjs'],
    },
    'packages/coveo-analytics': {
      // The package publishes `src/**/*.ts` and supports deep imports, so every
      // source module is part of its public surface, not just the bundle entries.
      // `bundle/browser-fetch.ts` is reachable only through the Rollup alias that
      // swaps out `cross-fetch` for browser builds.
      entry: ['src/**/*.ts', 'bundle/browser-fetch.ts'],
      // These modules intentionally expose two public bindings for the same
      // value: a named export plus a `default`, or a short plugin alias such as
      // `EC = ECPlugin`. Both spellings are part of the published API and are
      // reachable through deep imports, so neither can be dropped. Scoped to the
      // known files so new duplicate exports elsewhere in the package still fail.
      ignoreIssues: {
        'src/client/analytics.ts': ['duplicates'],
        'src/coveoua/simpleanalytics.ts': ['duplicates'],
        'src/donottrack.ts': ['duplicates'],
        'src/history.ts': ['duplicates'],
        'src/plugins/ec.ts': ['duplicates'],
        'src/plugins/link.ts': ['duplicates'],
        'src/plugins/svc.ts': ['duplicates'],
      },
    },
    'packages/documentation': {
      entry: [
        '**/assets/**/*.js',
        '**/lib/*.ts',
        '**/*.css', //TODO: Find a better solution
      ],
    },
    'packages/thermidor-schema': {
      entry: ['src/index.ts', 'src/generated/schemas.ts'],
      ignoreUnresolved: [
        /^\.\.\/\.\.\/thermidor-contracts\/src\/generated\/catalog-contracts\.js$/,
      ],
    },
    'samples/headless/commerce-react': {
      // ShowMore and ProductsPerPage are kept as reference examples but are not
      // wired into the UI, so Knip should not flag them as unused files.
      ignore: ['src/components/show-more/**', 'src/components/products-per-page/**'],
    },
    'samples/headless-ssr/commerce-express': {
      entry: ['src/server.ts'],
    },
    'samples/headless-ssr/commerce-nextjs': {
      // `mock-server.mjs` is a test utility, not exported publicly nor imported internally, so Knip cannot trace it.
      entry: ['mocks/mock-server.mjs'],
    },
    'samples/headless-ssr/commerce-nextjs-v4': {},
    'samples/headless-ssr/commerce-react-router': {
      // Generated by `react-router typegen` into .react-router/types/ via rootDirs.
      // Not present during static analysis in CI.
      ignoreUnresolved: [/^\.\/\+types\/.+/],
    },
    'samples/atomic/commerce-vite': {
      // Knip cannot load vite.config.js because it throws when @coveo/atomic
      // build artifacts (dist/lang, dist/assets) are missing. Disable the Vite
      // plugin config loader.
      vite: {config: []},
      entry: ['src/commerce-page.js'],
    },
    'samples/atomic/search-vite': {
      // Same as commerce-vite: vite.config.js throws without build artifacts.
      vite: {config: []},
    },
    'utils/ci': {},
    'utils/cdn': {},

    // Projects to enable rule by rule.
    'packages/atomic': {
      // The `@/*` path alias is declared in packages/atomic/tsconfig.json, but
      // oxc-resolver >=11.21 only applies a tsconfig's `paths` to files that the
      // tsconfig "owns" (its `include` globs cover only .ts/.tsx). Imports from
      // .mdx Storybook docs pages are therefore not aliased, so we declare the
      // alias explicitly here for Knip's resolver.
      paths: {
        '@/*': ['./*'],
      },
      entry: [
        'src/loader.ts',
        'src/cdn.ts',
        'src/**/*.e2e.ts',
        'dev/**/*.{ts,js,mjs}',
        'scripts/**/*.{mjs,js}',
        'csp/**/*.{mjs,js}',
        'custom-elements-manifest.config.mjs',
        // Build-generated barrel indexes (created by `pnpm build:lit`).
        // In CI the build step runs before knip, so these always exist.
        // Adding them as entry points lets knip trace the export chain
        // into section components and other web components naturally.
        'src/components/*/index.ts',
        // Test fixture utilities consumed by spec files via @/ path alias.
        'vitest-utils/**/*.ts',
        // Interactive a11y Storybook helpers — will be consumed by stories
        // in an upcoming PR. Knip cannot trace them yet.
        'storybook-utils/a11y/**/*.ts',
      ],
      ignore: [
        // Static file loaded via HTML <script> tag in manager-head.html
        '.storybook/public/cookieManager.js',
        // CSS files referenced via @import/@reference inside CSS tagged template literals.
        // Knip cannot trace CSS imports inside template literal strings.
        'src/**/*.css',
      ],
    },
    'packages/atomic-legacy': {},
    'packages/create-atomic': {
      ignore: ['**/*'],
    },
    'packages/create-atomic-template': {
      ignore: ['**/*'],
    },
    'packages/shopify': {
      ignore: ['**/*'],
    },
    'samples/headless-ssr/search-nextjs': {
      ignore: ['**/*'],
    },
    'packages/create-atomic-component': {
      ignore: ['template/**/*'],
    },
    'packages/create-atomic-result-component': {
      ignore: ['template/**/*'],
    },
    'packages/thermidor': {
      ignore: ['**/*'],
    },
    'samples/thermidor/generative-react': {
      ignore: ['**/*'],
    },
    'samples/thermidor/generative-angular': {
      entry: ['proxy.conf.js'],
      ignore: ['src/app/services/engine.service.ts'],
    },
  },
};
