name: 'Playwright Atomic Theming'
description: 'Run Playwright smoke tests for Atomic theming'
inputs:
  uploadArtifacts:
    description: 'Whether to upload artifacts'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Run Playwright tests
      run: pnpm exec playwright test -c dev
      working-directory: packages/atomic
      shell: bash
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      if: ${{ inputs.uploadArtifacts == 'true' }}
      with:
        name: atomic-theming-playwright-report
        path: packages/atomic/playwright-report/
        retention-days: 5
