// Fixed reference timestamp (2026-01-13T00:00:00Z) for consistent snapshots
const REFERENCE_TIMESTAMP = 1768348800000;

export const baseRecommendationResponse = {
  totalCount: 10,
  totalCountFiltered: 10,
  duration: 2,
  indexDuration: 6,
  requestDuration: 1,
  searchUid: 'content-recs-demo',
  pipeline: 'Recommendations',
  apiVersion: 2,
  queryCorrections: [],
  index: 'cache',
  logicalIndex: 'default',
  refinedKeywords: [],
  triggers: [],
  termsToHighlight: {},
  phrasesToHighlight: {},
  groupByResults: [],
  facets: [],
  suggestedFacets: [],
  categoryFacets: [],
  results: [
    {
      title: 'Getting Started with Machine Learning',
      uri: 'https://example.coveo.com/articles/ml-getting-started',
      printableUri: 'https://example.coveo.com/articles/ml-getting-started',
      clickUri: 'https://example.coveo.com/articles/ml-getting-started',
      uniqueId: 'article-ml-001',
      excerpt:
        'A comprehensive guide to understanding the fundamentals of machine learning, from basic concepts to practical applications in modern software development.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 100,
      percentScore: 100,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Sarah Johnson',
        date: REFERENCE_TIMESTAMP - 86400000 * 2,
        category: 'Technology',
        source: 'Tech Blog',
        filetype: 'Article',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g1" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%234f46e5;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%237c3aed;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g1)"/%3E%3C/svg%3E',
        permanentid: 'article-ml-001',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Getting Started with Machine Learning',
      Uri: 'https://example.coveo.com/articles/ml-getting-started',
      PrintableUri: 'https://example.coveo.com/articles/ml-getting-started',
      ClickUri: 'https://example.coveo.com/articles/ml-getting-started',
      UniqueId: 'article-ml-001',
      Excerpt:
        'A comprehensive guide to understanding the fundamentals of machine learning, from basic concepts to practical applications in modern software development.',
      FirstSentences: null,
    },
    {
      title: 'Cloud Computing Best Practices for 2026',
      uri: 'https://example.coveo.com/articles/cloud-best-practices',
      printableUri: 'https://example.coveo.com/articles/cloud-best-practices',
      clickUri: 'https://example.coveo.com/articles/cloud-best-practices',
      uniqueId: 'article-cloud-002',
      excerpt:
        'Explore the latest trends and best practices in cloud computing, including serverless architectures, container orchestration, and multi-cloud strategies.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 95,
      percentScore: 95,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Michael Chen',
        date: REFERENCE_TIMESTAMP - 86400000 * 5,
        category: 'Cloud',
        source: 'Dev Weekly',
        filetype: 'Article',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g2" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%2306b6d4;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%230891b2;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g2)"/%3E%3C/svg%3E',
        permanentid: 'article-cloud-002',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Cloud Computing Best Practices for 2026',
      Uri: 'https://example.coveo.com/articles/cloud-best-practices',
      PrintableUri: 'https://example.coveo.com/articles/cloud-best-practices',
      ClickUri: 'https://example.coveo.com/articles/cloud-best-practices',
      UniqueId: 'article-cloud-002',
      Excerpt:
        'Explore the latest trends and best practices in cloud computing, including serverless architectures, container orchestration, and multi-cloud strategies.',
      FirstSentences: null,
    },
    {
      title: 'Building Accessible Web Applications',
      uri: 'https://example.coveo.com/articles/accessible-web-apps',
      printableUri: 'https://example.coveo.com/articles/accessible-web-apps',
      clickUri: 'https://example.coveo.com/articles/accessible-web-apps',
      uniqueId: 'article-a11y-003',
      excerpt:
        'Learn how to create web applications that are accessible to all users, including those with disabilities. Covers WCAG guidelines and practical implementation.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 90,
      percentScore: 90,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Emma Williams',
        date: REFERENCE_TIMESTAMP - 86400000 * 7,
        category: 'Accessibility',
        source: 'Web Dev Today',
        filetype: 'Article',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g3" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%2310b981;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23059669;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g3)"/%3E%3C/svg%3E',
        permanentid: 'article-a11y-003',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Building Accessible Web Applications',
      Uri: 'https://example.coveo.com/articles/accessible-web-apps',
      PrintableUri: 'https://example.coveo.com/articles/accessible-web-apps',
      ClickUri: 'https://example.coveo.com/articles/accessible-web-apps',
      UniqueId: 'article-a11y-003',
      Excerpt:
        'Learn how to create web applications that are accessible to all users, including those with disabilities. Covers WCAG guidelines and practical implementation.',
      FirstSentences: null,
    },
    {
      title: 'Introduction to TypeScript Advanced Types',
      uri: 'https://example.coveo.com/tutorials/typescript-advanced-types',
      printableUri:
        'https://example.coveo.com/tutorials/typescript-advanced-types',
      clickUri: 'https://example.coveo.com/tutorials/typescript-advanced-types',
      uniqueId: 'tutorial-ts-004',
      excerpt:
        'Deep dive into TypeScript advanced type features including conditional types, mapped types, and type inference patterns for better code quality.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 88,
      percentScore: 88,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'David Park',
        date: REFERENCE_TIMESTAMP - 86400000 * 10,
        category: 'Programming',
        source: 'Code Academy',
        filetype: 'Tutorial',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g4" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%233b82f6;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%232563eb;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g4)"/%3E%3C/svg%3E',
        permanentid: 'tutorial-ts-004',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Introduction to TypeScript Advanced Types',
      Uri: 'https://example.coveo.com/tutorials/typescript-advanced-types',
      PrintableUri:
        'https://example.coveo.com/tutorials/typescript-advanced-types',
      ClickUri: 'https://example.coveo.com/tutorials/typescript-advanced-types',
      UniqueId: 'tutorial-ts-004',
      Excerpt:
        'Deep dive into TypeScript advanced type features including conditional types, mapped types, and type inference patterns for better code quality.',
      FirstSentences: null,
    },
    {
      title: 'API Design Principles for RESTful Services',
      uri: 'https://example.coveo.com/guides/api-design-principles',
      printableUri: 'https://example.coveo.com/guides/api-design-principles',
      clickUri: 'https://example.coveo.com/guides/api-design-principles',
      uniqueId: 'guide-api-005',
      excerpt:
        'Master the art of designing clean, maintainable RESTful APIs with proper versioning, error handling, and documentation strategies.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 85,
      percentScore: 85,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Lisa Anderson',
        date: REFERENCE_TIMESTAMP - 86400000 * 14,
        category: 'API Design',
        source: 'Backend Weekly',
        filetype: 'Guide',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g5" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%23f59e0b;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23d97706;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g5)"/%3E%3C/svg%3E',
        permanentid: 'guide-api-005',
        language: ['English'],
        collection: 'default',
      },
      Title: 'API Design Principles for RESTful Services',
      Uri: 'https://example.coveo.com/guides/api-design-principles',
      PrintableUri: 'https://example.coveo.com/guides/api-design-principles',
      ClickUri: 'https://example.coveo.com/guides/api-design-principles',
      UniqueId: 'guide-api-005',
      Excerpt:
        'Master the art of designing clean, maintainable RESTful APIs with proper versioning, error handling, and documentation strategies.',
      FirstSentences: null,
    },
    {
      title: 'Modern CSS Layout Techniques',
      uri: 'https://example.coveo.com/articles/modern-css-layout',
      printableUri: 'https://example.coveo.com/articles/modern-css-layout',
      clickUri: 'https://example.coveo.com/articles/modern-css-layout',
      uniqueId: 'article-css-006',
      excerpt:
        'Explore modern CSS layout methods including Grid, Flexbox, and Container Queries to build responsive and maintainable user interfaces.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 83,
      percentScore: 83,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Robert Taylor',
        date: REFERENCE_TIMESTAMP - 86400000 * 3,
        category: 'Frontend',
        source: 'CSS Tricks',
        filetype: 'Article',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g6" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%23ec4899;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23db2777;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g6)"/%3E%3C/svg%3E',
        permanentid: 'article-css-006',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Modern CSS Layout Techniques',
      Uri: 'https://example.coveo.com/articles/modern-css-layout',
      PrintableUri: 'https://example.coveo.com/articles/modern-css-layout',
      ClickUri: 'https://example.coveo.com/articles/modern-css-layout',
      UniqueId: 'article-css-006',
      Excerpt:
        'Explore modern CSS layout methods including Grid, Flexbox, and Container Queries to build responsive and maintainable user interfaces.',
      FirstSentences: null,
    },
    {
      title: 'Understanding React Server Components',
      uri: 'https://example.coveo.com/tutorials/react-server-components',
      printableUri:
        'https://example.coveo.com/tutorials/react-server-components',
      clickUri: 'https://example.coveo.com/tutorials/react-server-components',
      uniqueId: 'tutorial-react-007',
      excerpt:
        'A practical guide to React Server Components, exploring how they work, when to use them, and how they fit into modern application architecture.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 80,
      percentScore: 80,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Jessica Martinez',
        date: REFERENCE_TIMESTAMP - 86400000 * 6,
        category: 'React',
        source: 'React Weekly',
        filetype: 'Tutorial',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g7" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%2361dafb;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%230ea5e9;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g7)"/%3E%3C/svg%3E',
        permanentid: 'tutorial-react-007',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Understanding React Server Components',
      Uri: 'https://example.coveo.com/tutorials/react-server-components',
      PrintableUri:
        'https://example.coveo.com/tutorials/react-server-components',
      ClickUri: 'https://example.coveo.com/tutorials/react-server-components',
      UniqueId: 'tutorial-react-007',
      Excerpt:
        'A practical guide to React Server Components, exploring how they work, when to use them, and how they fit into modern application architecture.',
      FirstSentences: null,
    },
    {
      title: 'Database Performance Optimization',
      uri: 'https://example.coveo.com/guides/database-performance',
      printableUri: 'https://example.coveo.com/guides/database-performance',
      clickUri: 'https://example.coveo.com/guides/database-performance',
      uniqueId: 'guide-db-008',
      excerpt:
        'Learn proven strategies for optimizing database performance, including indexing strategies, query optimization, and caching techniques.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 78,
      percentScore: 78,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Kevin Zhang',
        date: REFERENCE_TIMESTAMP - 86400000 * 12,
        category: 'Database',
        source: 'DB Weekly',
        filetype: 'Guide',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g8" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%2384cc16;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%2365a30d;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g8)"/%3E%3C/svg%3E',
        permanentid: 'guide-db-008',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Database Performance Optimization',
      Uri: 'https://example.coveo.com/guides/database-performance',
      PrintableUri: 'https://example.coveo.com/guides/database-performance',
      ClickUri: 'https://example.coveo.com/guides/database-performance',
      UniqueId: 'guide-db-008',
      Excerpt:
        'Learn proven strategies for optimizing database performance, including indexing strategies, query optimization, and caching techniques.',
      FirstSentences: null,
    },
    {
      title: 'Kubernetes Deployment Strategies Explained',
      uri: 'https://example.coveo.com/articles/kubernetes-deployment',
      printableUri: 'https://example.coveo.com/articles/kubernetes-deployment',
      clickUri: 'https://example.coveo.com/articles/kubernetes-deployment',
      uniqueId: 'article-k8s-009',
      excerpt:
        'Comprehensive overview of Kubernetes deployment strategies including rolling updates, blue-green deployments, and canary releases.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 75,
      percentScore: 75,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Tom Wilson',
        date: REFERENCE_TIMESTAMP - 86400000 * 8,
        category: 'DevOps',
        source: 'K8s Blog',
        filetype: 'Article',
        duration: '12:45',
        views: '15.2K',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g9" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%23326ce5;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%231e40af;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g9)"/%3E%3C/svg%3E',
        permanentid: 'article-k8s-009',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Kubernetes Deployment Strategies Explained',
      Uri: 'https://example.coveo.com/articles/kubernetes-deployment',
      PrintableUri: 'https://example.coveo.com/articles/kubernetes-deployment',
      ClickUri: 'https://example.coveo.com/articles/kubernetes-deployment',
      UniqueId: 'article-k8s-009',
      Excerpt:
        'Comprehensive overview of Kubernetes deployment strategies including rolling updates, blue-green deployments, and canary releases.',
      FirstSentences: null,
    },
    {
      title: 'Security Best Practices for Web Applications',
      uri: 'https://example.coveo.com/articles/web-security',
      printableUri: 'https://example.coveo.com/articles/web-security',
      clickUri: 'https://example.coveo.com/articles/web-security',
      uniqueId: 'article-security-010',
      excerpt:
        'Essential security practices every developer should know, covering authentication, authorization, data protection, and common vulnerabilities.',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 73,
      percentScore: 73,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: true,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        author: 'Amanda White',
        date: REFERENCE_TIMESTAMP - 86400000 * 4,
        category: 'Security',
        source: 'Security News',
        filetype: 'Article',
        image:
          'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"%3E%3Cdefs%3E%3ClinearGradient id="g10" x1="0%25" y1="0%25" x2="100%25" y2="100%25"%3E%3Cstop offset="0%25" style="stop-color:%23ef4444;stop-opacity:1" /%3E%3Cstop offset="100%25" style="stop-color:%23dc2626;stop-opacity:1" /%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width="800" height="600" fill="url(%23g10)"/%3E%3C/svg%3E',
        permanentid: 'article-security-010',
        language: ['English'],
        collection: 'default',
      },
      Title: 'Security Best Practices for Web Applications',
      Uri: 'https://example.coveo.com/articles/web-security',
      PrintableUri: 'https://example.coveo.com/articles/web-security',
      ClickUri: 'https://example.coveo.com/articles/web-security',
      UniqueId: 'article-security-010',
      Excerpt:
        'Essential security practices every developer should know, covering authentication, authorization, data protection, and common vulnerabilities.',
      FirstSentences: null,
    },
  ],
  extendedResults: {},
};
