name: 'Quantic Playwright E2E tests'
description: 'Runs Playwright tests for Quantic'
runs:
  using: composite
  steps:
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: packages/quantic/.env
        key: quantic-playwright-env-${{ github.sha }}
    - name: Run Playwright Tests
      run: |
        npx playwright install --with-deps
        npx playwright test
      shell: bash
      working-directory: ./packages/quantic
    - name: Upload Playwright Report
      if: cancelled() || failure() || success()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: playwright-report
        path: packages/quantic/test-results
        retention-days: 5
