name: 'Quantic Playwright E2E tests'
description: 'Runs Playwright tests for Quantic'
inputs:
  shardIndex:
    description: 'The shard index to run'
    required: true
  shardTotal:
    description: 'The total number of shards'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        pattern: quantic-playwright-env-*
        path: packages/quantic/.env
        merge-multiple: true
    - name: Run Playwright Tests
      run: pnpm exec playwright test --shard=${{ inputs.shardIndex }}/${{ inputs.shardTotal }}
      shell: bash
      working-directory: ./packages/quantic
    - name: Upload blob report to GitHub Actions Artifacts
      if: cancelled() || failure() || success()
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: quantic-blob-report-${{ matrix.shardIndex }}
        path: packages/quantic/blob-report
        retention-days: 5