// This file is generated by postcss-build.cjs

const css = `.js-focus-visible .value-exclude-button.focus-visible atomic-icon,.value-exclude-button.focus-visible.js-focus-visible atomic-icon{visibility:visible}.value-exclude-button:focus-visible atomic-icon{visibility:visible}`;
const allCss: string[] = [css];
export default allCss;
