apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bueno
  title: '@coveo/bueno'
  description: A simple validator
  annotations:
    github.com/project-slug: coveo/ui-kit
spec:
  type: library
  lifecycle: production
  owner: group:default/dxui
  system: ui-kit
  dependencyOf:
    - headless
    - atomic
