// This file is generated by postcss-build.cjs
import dep0 from '../../../../global/global.css';
import dep2 from '../../../common/facets/facet-common.css';
import dep1 from '../../../common/facets/facet-search/facet-search.css';
import dep5 from '../../../common/facets/facet-value-box/facet-value-box.css';
import dep3 from '../../../common/facets/facet-value-checkbox/facet-value-checkbox.css';
import dep4 from '../../../common/facets/facet-value-exclude/facet-value-exclude.css';

const css = ``;
const allCss: string[] = [
  ...dep0,
  ...dep1,
  ...dep2,
  ...dep3,
  ...dep4,
  ...dep5,
  css,
];
export default allCss;
