name: Deploy
description: Creates and deploys the packages
inputs:
  COMMIT_HASH:
    description: Short commit hash of the version bump
runs:
  using: composite
  steps:
    - uses: coveo/deployment-pipeline-actions/setup-cli@main
    - name: Create and Deploy Packages
      env:
        COMMIT_HASH: ${{ inputs.COMMIT_HASH }}
      shell: bash
      run: node ./.github/actions/deploy/deploy.mjs
