apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: create-atomic-rollup-plugin
  title: '@coveo/create-atomic-rollup-plugin'
  description: Rollup plugin for resolving Coveo Atomic dependencies from CDN or npm
spec:
  type: library
  lifecycle: production
  owner: group:default/dxui
  system: ui-kit
