export const THERMIDOR_CATALOG_ID = 'https://schema.thermidor.coveo.com/a2-ui/catalog.json';

export {
  ActionItemSchema,
  BundleDisplayControllerContractSchema,
  BundleDisplayStateSchema,
  BundleSlotSchema,
  BundleTierSchema,
  CartControllerContractSchema,
  CartItemSchema,
  CartStateSchema,
  ComparisonAttributeSchema,
  ComparisonProductSchema,
  ComparisonTableControllerContractSchema,
  ComparisonTableStateSchema,
  ControllerContractsSchema,
  NextActionsControllerContractSchema,
  NextActionsStateSchema,
  ProductListControllerContractSchema,
  ProductListStateSchema,
  ProductSchema,
  SelectActionPayloadSchema,
  SetItemsPayloadSchema,
  UpdateItemQuantityPayloadSchema,
  BundleDisplayPropsSchema,
  CartPropsSchema,
  ComparisonTablePropsSchema,
  NextActionsBarPropsSchema,
  ProductCarouselPropsSchema,
} from './generated/schemas.js';
export type {
  ActionItem,
  BundleDisplayControllerContract,
  BundleDisplayState,
  BundleSlot,
  BundleTier,
  CartControllerContract,
  CartItem,
  CartState,
  ComparisonAttribute,
  ComparisonProduct,
  ComparisonTableControllerContract,
  ComparisonTableState,
  ControllerContracts,
  NextActionsControllerContract,
  NextActionsState,
  Product,
  ProductListControllerContract,
  ProductListState,
  SelectActionPayload,
  SetItemsPayload,
  UpdateItemQuantityPayload,
  BundleDisplayProps,
  CartProps,
  ComparisonTableProps,
  NextActionsBarProps,
  ProductCarouselProps,
} from './generated/schemas.js';
