export const THERMIDOR_CATALOG_ID = 'https://schema.thermidor.coveo.com/a2-ui/catalog.json';

export {
  ActionItemSchema,
  BundleDisplaySchema,
  BundleDisplayStateSchema,
  BundleSlotSchema,
  BundleTierSchema,
  CartSchema,
  CartItemSchema,
  CartStateSchema,
  ComparisonAttributeSchema,
  ComparisonProductSchema,
  ComparisonTableSchema,
  ComparisonTableStateSchema,
  ComponentContractsSchema,
  NextActionsBarSchema,
  NextActionsStateSchema,
  ProductCarouselSchema,
  ProductListStateSchema,
  ProductSchema,
  SelectActionPayloadSchema,
  SetItemsPayloadSchema,
  UpdateItemQuantityPayloadSchema,
  BundleDisplayPropsSchema,
  CartPropsSchema,
  ComparisonTablePropsSchema,
  NextActionsBarPropsSchema,
  ProductCarouselPropsSchema,
} from './generated/schemas.js';
export type {
  ActionItem,
  BundleDisplay,
  BundleDisplayState,
  BundleSlot,
  BundleTier,
  Cart,
  CartItem,
  CartState,
  ComparisonAttribute,
  ComparisonProduct,
  ComparisonTable,
  ComparisonTableState,
  ComponentContracts,
  NextActionsBar,
  NextActionsState,
  Product,
  ProductCarousel,
  ProductListState,
  SelectActionPayload,
  SetItemsPayload,
  UpdateItemQuantityPayload,
  BundleDisplayProps,
  CartProps,
  ComparisonTableProps,
  NextActionsBarProps,
  ProductCarouselProps,
} from './generated/schemas.js';
