import {getSchemaValidator} from './open-api-schema.js';

const getNthResult = (n: number) => ({
  title: `Sample Result ${n}`,
  excerpt: 'This is a sample result excerpt for testing.',
  clickUri: `https://example.com/search/${n}`,
  uniqueId: `rec-${n}`,
  raw: {
    systitle: `Sample Result ${n}`,
    sysdescription: 'This is a sample result excerpt for testing.',
    sysuri: `https://example.com/search/${n}`,
  },
  uri: `/example.com/search/${n}`,
  printableUri: `https://printable-example.com/search/${n}`,
  absentTerms: [],
  childResults: [],
  totalNumberOfChildResults: 0,
  excerptHighlights: [],
  parentResult: null,
  printableUriHighlights: [],
  firstSentences: null,
  firstSentencesHighlights: [],
  rankingInfo: null,
  rating: 3,
  score: 0,
  percentScore: 42.0,
  summary: null,
  summaryHighlights: [],
  titleHighlights: [],
  isUserActionView: false,
  isTopResult: false,
  isRecommendation: false,
  hasMobileHtmlVersion: false,
  hasHtmlVersion: false,
  flags: '',
});

export const baseResponse = {
  totalCount: 120,
  totalCountFiltered: 120,
  duration: 175,
  indexDuration: 18,
  requestDuration: 41,
  index: 'someIndex',
  searchUid: '2971cca7-90b4-4b64-97dd-5dac45c1cc43',
  pipeline: 'genqatest',
  apiVersion: 2,
  queryCorrections: [],
  basicExpression: 'how to resolve netflix connection with tivo',
  advancedExpression: null,
  largeExpression: null,
  constantExpression: null,
  disjunctionExpression: null,
  mandatoryExpression: null,
  userIdentities: [
    {
      name: 'anonymous_user@anonymous.coveo.com',
      provider: 'Email Security Provider',
      type: 'User',
    },
  ],
  rankingExpressions: [],
  topResults: [],
  executionReport: {},
  refinedKeywords: [],
  triggers: [],
  termsToHighlight: {},
  phrasesToHighlight: {},
  groupByResults: [],
  facets: [],
  suggestedFacets: [],
  categoryFacets: [],
  results: Array.from({length: 120}, (_, n) => getNthResult(n)),
  questionAnswer: {
    answerFound: false,
    question: '',
    answerSnippet: '',
    documentId: {
      contentIdKey: '',
      contentIdValue: '',
    },
    score: 0.0,
    relatedQuestions: [],
  },
};

export const validateResponse = getSchemaValidator('RestQueryResponse');
