const getNthResult = (n: number) => ({
  title: `Sample Result ${n}`,
  excerpt: 'This is a sample result excerpt for testing.',
  clickUri: `https://example.com/search/${n}`,
  uniqueId: `rec-${n}`,
  raw: {
    systitle: `Sample Result ${n}`,
    sysdescription: 'This is a sample result excerpt for testing.',
    sysuri: `https://example.com/search/${n}`,
  },
});

interface Response {
  totalCount: number;
  totalCountFiltered: number;
  duration: number;
  indexDuration: number;
  requestDuration: number;
  searchUid: string;
  pipeline: string;
  index?: string;
  apiVersion: number;
  queryCorrections: unknown[];
  basicExpression: string | null;
  advancedExpression: string | null;
  largeExpression: string | null;
  constantExpression: string | null;
  disjunctionExpression: string | null;
  mandatoryExpression: string | null;
  userIdentities: unknown[];
  rankingExpressions: unknown[];
  topResults: unknown[];
  executionReport: Record<string, unknown>;
  refinedKeywords: unknown[];
  triggers: unknown[];
  termsToHighlight: Record<string, unknown>;
  phrasesToHighlight: Record<string, unknown>;
  groupByResults: unknown[];
  facets: unknown[];
  suggestedFacets: unknown[];
  categoryFacets: unknown[];
  results: unknown[];
  questionAnswer: Record<string, unknown>;
  extendedResults?: Record<string, unknown>;
}

export const baseResponse: Response = {
  totalCount: 120,
  totalCountFiltered: 120,
  duration: 175,
  indexDuration: 18,
  requestDuration: 41,
  searchUid: '2971cca7-90b4-4b64-97dd-5dac45c1cc43',
  pipeline: 'genqatest',
  apiVersion: 2,
  queryCorrections: [],
  basicExpression: 'how to resolve netflix connection with tivo',
  advancedExpression: null,
  largeExpression: null,
  constantExpression: null,
  disjunctionExpression: null,
  mandatoryExpression: null,
  userIdentities: [
    {
      name: 'anonymous_user@anonymous.coveo.com',
      provider: 'Email Security Provider',
      type: 'User',
    },
  ],
  rankingExpressions: [],
  topResults: [],
  executionReport: {},
  refinedKeywords: [],
  triggers: [],
  termsToHighlight: {},
  phrasesToHighlight: {},
  groupByResults: [],
  facets: [
    {
      facetId: 'objecttype',
      field: 'objecttype',
      moreValuesAvailable: true,
      values: [
        {
          value: 'People',
          state: 'idle',
          numberOfResults: 126786,
        },
        {
          value: 'Contact',
          state: 'idle',
          numberOfResults: 179426,
        },
        {
          value: 'Variant',
          state: 'idle',
          numberOfResults: 30827,
        },
        {
          value: 'Message',
          state: 'idle',
          numberOfResults: 26868,
        },
        {
          value: 'Thread',
          state: 'idle',
          numberOfResults: 7112,
        },
        {
          value: 'Account',
          state: 'idle',
          numberOfResults: 4721,
        },
      ],
      indexScore: 0.08949005905806505,
      label: 'Object type',
    },
  ],
  suggestedFacets: [],
  categoryFacets: [],
  results: Array.from({length: 120}, (_, n) => getNthResult(n)),
  questionAnswer: {
    answerFound: false,
    question: '',
    answerSnippet: '',
    documentId: {
      contentIdKey: '',
      contentIdValue: '',
    },
    score: 0.0,
    relatedQuestions: [],
  },
};

// Ultra-minimal folded response inspired by getNthResult
export const baseFoldedResponse: Response = {
  totalCount: 2,
  totalCountFiltered: 2,
  duration: 15,
  indexDuration: 5,
  requestDuration: 3,
  searchUid: 'minimal-folded-response',
  pipeline: 'default',
  apiVersion: 2,
  queryCorrections: [],
  basicExpression: null,
  advancedExpression: null,
  largeExpression: null,
  constantExpression: null,
  disjunctionExpression: null,
  mandatoryExpression: null,
  userIdentities: [],
  rankingExpressions: [],
  topResults: [],
  executionReport: {},
  refinedKeywords: [],
  triggers: [],
  termsToHighlight: {},
  phrasesToHighlight: {},
  groupByResults: [],
  facets: [],
  suggestedFacets: [],
  categoryFacets: [],
  results: [
    // Parent result with children - minimal fields only
    {
      title: 'Animals',
      excerpt: 'Collection of animals',
      clickUri: 'https://example.com/animals',
      uniqueId: 'animals-parent',
      childResults: [
        {
          title: 'Cats',
          excerpt: 'Cat species',
          clickUri: 'https://example.com/cats',
          uniqueId: 'cats-child',
          raw: {
            foldingcollection: 'Animals',
            foldingchild: ['cats'],
            foldingparent: 'animals',
          },
        },
        {
          title: 'Dogs',
          excerpt: 'Dog species',
          clickUri: 'https://example.com/dogs',
          uniqueId: 'dogs-child',
          raw: {
            foldingcollection: 'Animals',
            foldingchild: ['dogs'],
            foldingparent: 'animals',
          },
        },
      ],
      totalNumberOfChildResults: 2,
      raw: {
        foldingcollection: 'Animals',
        foldingchild: ['animals'],
      },
    },
    // Standalone result - minimal fields only
    {
      title: 'Plants',
      excerpt: 'Plant collection',
      clickUri: 'https://example.com/plants',
      uniqueId: 'plants-standalone',
      childResults: [],
      totalNumberOfChildResults: 0,
      raw: {
        foldingcollection: 'Plants',
        foldingchild: ['plants'],
      },
    },
  ],
  questionAnswer: {
    answerFound: false,
    question: '',
    answerSnippet: '',
    documentId: {
      contentIdKey: '',
      contentIdValue: '',
    },
    score: 0.0,
    relatedQuestions: [],
  },
  extendedResults: {},
};

export const richResponse = {
  totalCount: 458475,
  totalCountFiltered: 458475,
  duration: 93,
  indexDuration: 66,
  requestDuration: 87,
  searchUid: '45f06130-c47f-4f46-82f9-347efe40d25b',
  pipeline: 'default',
  apiVersion: 2,
  queryCorrection: {
    corrections: [],
  },
  index:
    'searchuisamples-x2gfkt3pnhhygw75wjwd4ikgtu-Indexer-1-xear73dnxrjptdfj53fhppcixi',
  logicalIndex: 'default',
  indexRegion: 'us-east-1',
  indexToken:
    'c2VhcmNodWlzYW1wbGVzLXgyZ2ZrdDNwbmhoeWd3NzV3andkNGlrZ3R1LUluZGV4ZXItMS14ZWFyNzNkbnhyanB0ZGZqNTNmaHBwY2l4aQ==',
  refinedKeywords: [],
  triggers: [],
  termsToHighlight: {},
  phrasesToHighlight: {},
  groupByResults: [],
  facets: [
    {
      facetId: 'ytviewcount_input_range',
      field: 'ytviewcount',
      moreValuesAvailable: false,
      values: [
        {
          start: 0,
          end: 71000000,
          endInclusive: true,
          state: 'idle',
          numberOfResults: 62734,
        },
      ],
      indexScore: 0.23386394646849415,
      domain: {
        start: 8,
        end: 70261098,
      },
    },
    {
      facetId: 'ytviewcount',
      field: 'ytviewcount',
      moreValuesAvailable: false,
      values: [
        {
          start: 0,
          end: 880000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 59362,
        },
        {
          start: 880000,
          end: 1760000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 1974,
        },
        {
          start: 1760000,
          end: 2640000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 638,
        },
        {
          start: 2640000,
          end: 3520000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 317,
        },
        {
          start: 3520000,
          end: 4400000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 170,
        },
        {
          start: 4400000,
          end: 6160000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 91,
        },
        {
          start: 6160000,
          end: 11440000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 115,
        },
        {
          start: 11440000,
          end: 70400000,
          endInclusive: true,
          state: 'idle',
          numberOfResults: 67,
        },
      ],
      indexScore: 0.23386394646849415,
      domain: {
        start: 8,
        end: 70261098,
      },
    },
    {
      facetId: 'ytviewcount_input',
      field: 'ytviewcount',
      moreValuesAvailable: false,
      values: [],
      indexScore: 0.23386394646849415,
      domain: {
        start: 8,
        end: 70261098,
      },
    },
    {
      facetId: 'ytlikecount',
      field: 'ytlikecount',
      moreValuesAvailable: false,
      values: [
        {
          start: 0,
          end: 1000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 33937,
        },
        {
          start: 1000,
          end: 8000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 24979,
        },
        {
          start: 8000,
          end: 100000,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 3649,
        },
        {
          start: 100000,
          end: 999999999,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 110,
        },
      ],
      indexScore: 0.23385493834373272,
      domain: {
        start: 0,
        end: 1145441,
      },
    },
    {
      facetId: 'filetype',
      field: 'filetype',
      moreValuesAvailable: true,
      values: [
        {
          value: 'dynamicscrmitem',
          state: 'idle',
          numberOfResults: 184232,
        },
        {
          value: 'lithiumuser',
          state: 'idle',
          numberOfResults: 126959,
        },
        {
          value: 'YouTubeVideo',
          state: 'idle',
          numberOfResults: 62734,
        },
        {
          value: 'txt',
          state: 'idle',
          numberOfResults: 38398,
        },
        {
          value: 'lithiummessage',
          state: 'idle',
          numberOfResults: 26879,
        },
        {
          value: 'incident',
          state: 'idle',
          numberOfResults: 7262,
        },
      ],
      indexScore: 0.1,
    },
    {
      facetId: 'author',
      field: 'author',
      moreValuesAvailable: true,
      values: [
        {
          value: 'BBC News',
          state: 'idle',
          numberOfResults: 62794,
        },
        {
          value: 'Susan Cook',
          state: 'idle',
          numberOfResults: 124,
        },
        {
          value: 'Martin Laporte',
          state: 'idle',
          numberOfResults: 71,
        },
        {
          value: 'BBCPanorama',
          state: 'idle',
          numberOfResults: 40,
        },
        {
          value: 'democ',
          state: 'idle',
          numberOfResults: 34,
        },
        {
          value: 'BBC Trending',
          state: 'idle',
          numberOfResults: 26,
        },
        {
          value: 'BBC Newsnight',
          state: 'idle',
          numberOfResults: 21,
        },
        {
          value: 'Wayne Webb',
          state: 'idle',
          numberOfResults: 10,
        },
      ],
      indexScore: 0.1,
    },
    {
      facetId: 'source',
      field: 'source',
      moreValuesAvailable: true,
      values: [
        {
          value: 'Coveo Samples - Youtube BBC News',
          state: 'idle',
          numberOfResults: 62898,
        },
        {
          value: 'Coveo Sample - Lithium Community',
          state: 'idle',
          numberOfResults: 161203,
        },
        {
          value: 'Coveo Samples - Dynamics 365',
          state: 'idle',
          numberOfResults: 184232,
        },
        {
          value: 'Sports',
          state: 'idle',
          numberOfResults: 34545,
        },
        {
          value: 'ServiceNow Speedbit',
          state: 'idle',
          numberOfResults: 10955,
        },
        {
          value: 'iNaturalistTaxons',
          state: 'idle',
          numberOfResults: 3519,
        },
        {
          value: 'Coveo Sample - SF lvu08',
          state: 'idle',
          numberOfResults: 351,
        },
        {
          value: 'Coveo Sample - ListCountries',
          state: 'idle',
          numberOfResults: 316,
        },
      ],
      indexScore: 0.1,
    },
    {
      facetId: 'filetype_1',
      field: 'filetype',
      moreValuesAvailable: true,
      values: [
        {
          value: 'YouTubeVideo',
          state: 'idle',
          numberOfResults: 62734,
        },
        {
          value: 'lithiumuser',
          state: 'idle',
          numberOfResults: 126959,
        },
        {
          value: 'dynamicscrmitem',
          state: 'idle',
          numberOfResults: 184232,
        },
        {
          value: 'txt',
          state: 'idle',
          numberOfResults: 38398,
        },
        {
          value: 'lithiummessage',
          state: 'idle',
          numberOfResults: 26879,
        },
        {
          value: 'incident',
          state: 'idle',
          numberOfResults: 7262,
        },
        {
          value: 'lithiumthread',
          state: 'idle',
          numberOfResults: 7115,
        },
        {
          value: 'sn_hr_core_case',
          state: 'idle',
          numberOfResults: 1192,
        },
      ],
      indexScore: 0.1,
    },
    {
      facetId: 'year',
      field: 'year',
      moreValuesAvailable: true,
      values: [
        {
          value: '2025',
          state: 'idle',
          numberOfResults: 175222,
        },
        {
          value: '2019',
          state: 'idle',
          numberOfResults: 199094,
        },
        {
          value: '2024',
          state: 'idle',
          numberOfResults: 13407,
        },
        {
          value: '2022',
          state: 'idle',
          numberOfResults: 11290,
        },
        {
          value: '2020',
          state: 'idle',
          numberOfResults: 8011,
        },
        {
          value: '2023',
          state: 'idle',
          numberOfResults: 7930,
        },
        {
          value: '2018',
          state: 'idle',
          numberOfResults: 7346,
        },
        {
          value: '2021',
          state: 'idle',
          numberOfResults: 6870,
        },
      ],
      indexScore: 0.1,
    },
    {
      facetId: 'date',
      field: 'date',
      moreValuesAvailable: false,
      values: [
        {
          start: '2025/12/05@16:02:52',
          end: '2025/12/05@17:02:52',
          endInclusive: false,
          state: 'idle',
          numberOfResults: 0,
        },
        {
          start: '2025/12/04@17:02:52',
          end: '2025/12/05@17:02:52',
          endInclusive: false,
          state: 'idle',
          numberOfResults: 0,
        },
        {
          start: '2025/11/28@17:02:52',
          end: '2025/12/05@17:02:52',
          endInclusive: false,
          state: 'idle',
          numberOfResults: 127045,
        },
        {
          start: '2025/11/05@17:02:52',
          end: '2025/12/05@17:02:52',
          endInclusive: false,
          state: 'idle',
          numberOfResults: 127461,
        },
        {
          start: '2025/09/05@17:02:52',
          end: '2025/12/05@17:02:52',
          endInclusive: false,
          state: 'idle',
          numberOfResults: 129765,
        },
        {
          start: '2024/12/05@17:02:52',
          end: '2025/12/05@17:02:52',
          endInclusive: false,
          state: 'idle',
          numberOfResults: 176070,
        },
      ],
      indexScore: 0.1,
      domain: {
        start: '2007/05/11@14:39:46',
        end: '2026/10/17@07:55:44',
      },
    },
    {
      facetId: 'date_input_range',
      field: 'date',
      moreValuesAvailable: false,
      values: [
        {
          start: '2006/12/31@19:00:00',
          end: '2026/12/31@19:00:00',
          endInclusive: true,
          state: 'idle',
          numberOfResults: 458475,
        },
      ],
      indexScore: 0.1,
      domain: {
        start: '2007/05/11@14:39:46',
        end: '2026/10/17@07:55:44',
      },
    },
    {
      facetId: 'date_input',
      field: 'date',
      moreValuesAvailable: false,
      values: [],
      indexScore: 0.1,
      domain: {
        start: '2007/05/11@14:39:46',
        end: '2026/10/17@07:55:44',
      },
    },
    {
      facetId: 'language',
      field: 'language',
      moreValuesAvailable: true,
      values: [
        {
          value: 'English',
          state: 'idle',
          numberOfResults: 120228,
        },
        {
          value: 'Croatian',
          state: 'idle',
          numberOfResults: 742,
        },
        {
          value: 'Polish',
          state: 'idle',
          numberOfResults: 302,
        },
        {
          value: 'Czech',
          state: 'idle',
          numberOfResults: 292,
        },
        {
          value: 'Slovenian',
          state: 'idle',
          numberOfResults: 253,
        },
        {
          value: 'Slovak',
          state: 'idle',
          numberOfResults: 126,
        },
        {
          value: 'French',
          state: 'idle',
          numberOfResults: 106,
        },
        {
          value: 'German',
          state: 'idle',
          numberOfResults: 106,
        },
      ],
      indexScore: 0.08,
    },
    {
      facetId: 'concepts',
      field: 'concepts',
      moreValuesAvailable: true,
      values: [
        {
          value: 'Israel',
          state: 'idle',
          numberOfResults: 1952,
        },
        {
          value: 'meeting',
          state: 'idle',
          numberOfResults: 190,
        },
        {
          value: 'voting',
          state: 'idle',
          numberOfResults: 121,
        },
        {
          value: 'participation',
          state: 'idle',
          numberOfResults: 57,
        },
        {
          value: 'Song Contest',
          state: 'idle',
          numberOfResults: 5,
        },
        {
          value: 'addressed new',
          state: 'idle',
          numberOfResults: 1,
        },
        {
          value: 'biannual general',
          state: 'idle',
          numberOfResults: 1,
        },
        {
          value: 'European Broadcasting Union',
          state: 'idle',
          numberOfResults: 1,
        },
      ],
      indexScore: 0.08,
    },
    {
      facetId: 'objecttype',
      field: 'objecttype',
      moreValuesAvailable: true,
      values: [
        {
          value: 'People',
          state: 'idle',
          numberOfResults: 126959,
        },
        {
          value: 'Contact',
          state: 'idle',
          numberOfResults: 179426,
        },
        {
          value: 'Variant',
          state: 'idle',
          numberOfResults: 30827,
        },
        {
          value: 'Message',
          state: 'idle',
          numberOfResults: 26879,
        },
        {
          value: 'Thread',
          state: 'idle',
          numberOfResults: 7115,
        },
        {
          value: 'Account',
          state: 'idle',
          numberOfResults: 4721,
        },
      ],
      indexScore: 0.05860685969791156,
      label: 'Object type',
    },
    {
      facetId: 'geographicalhierarchy',
      field: 'geographicalhierarchy',
      moreValuesAvailable: false,
      values: [
        {
          value: 'North America',
          state: 'idle',
          numberOfResults: 112,
          children: [],
          path: ['North America'],
          isLeafValue: false,
        },
        {
          value: 'Africa',
          state: 'idle',
          numberOfResults: 58,
          children: [],
          path: ['Africa'],
          isLeafValue: false,
        },
        {
          value: 'Europe',
          state: 'idle',
          numberOfResults: 54,
          children: [],
          path: ['Europe'],
          isLeafValue: false,
        },
        {
          value: 'Asia',
          state: 'idle',
          numberOfResults: 51,
          children: [],
          path: ['Asia'],
          isLeafValue: false,
        },
        {
          value: 'Oceania',
          state: 'idle',
          numberOfResults: 26,
          children: [],
          path: ['Oceania'],
          isLeafValue: false,
        },
        {
          value: 'South America',
          state: 'idle',
          numberOfResults: 14,
          children: [],
          path: ['South America'],
          isLeafValue: false,
        },
        {
          value: 'Antarctica',
          state: 'idle',
          numberOfResults: 1,
          children: [],
          path: ['Antarctica'],
          isLeafValue: false,
        },
      ],
      indexScore: 4.824690550193577e-5,
    },
    {
      facetId: 'snrating',
      field: 'snrating',
      moreValuesAvailable: false,
      values: [
        {
          start: 5,
          end: 6,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 13,
        },
        {
          start: 4,
          end: 5,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 6,
        },
        {
          start: 3,
          end: 4,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 17,
        },
        {
          start: 2,
          end: 3,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 6,
        },
        {
          start: 1,
          end: 2,
          endInclusive: false,
          state: 'idle',
          numberOfResults: 3,
        },
      ],
      indexScore: 6.870603631604777e-6,
      domain: {
        start: 1.0,
        end: 5.0,
      },
    },
    {
      facetId: 'snrating_range',
      field: 'snrating',
      moreValuesAvailable: false,
      values: [
        {
          start: 5,
          end: 5,
          endInclusive: true,
          state: 'idle',
          numberOfResults: 13,
        },
        {
          start: 4,
          end: 5,
          endInclusive: true,
          state: 'idle',
          numberOfResults: 19,
        },
        {
          start: 3,
          end: 5,
          endInclusive: true,
          state: 'idle',
          numberOfResults: 36,
        },
        {
          start: 2,
          end: 5,
          endInclusive: true,
          state: 'idle',
          numberOfResults: 42,
        },
        {
          start: 1,
          end: 5,
          endInclusive: true,
          state: 'idle',
          numberOfResults: 45,
        },
      ],
      indexScore: 6.870603631604777e-6,
      domain: {
        start: 1.0,
        end: 5.0,
      },
    },
  ],
  suggestedFacets: [],
  generateAutomaticFacets: {
    facets: [
      {
        field: 'documenttype',
        moreValuesAvailable: true,
        values: [
          {
            value: 'incident',
            state: 'idle',
            numberOfResults: 7262,
          },
          {
            value: 'message',
            state: 'idle',
            numberOfResults: 26935,
          },
          {
            value: 'problem',
            state: 'idle',
            numberOfResults: 1094,
          },
          {
            value: 'Record',
            state: 'idle',
            numberOfResults: 184232,
          },
          {
            value: 'sn_hr_core_case',
            state: 'idle',
            numberOfResults: 1192,
          },
          {
            value: 'sys_user',
            state: 'idle',
            numberOfResults: 679,
          },
          {
            value: 'thread',
            state: 'idle',
            numberOfResults: 7115,
          },
          {
            value: 'user',
            state: 'idle',
            numberOfResults: 127103,
          },
        ],
        indexScore: 0.2884096686998045,
      },
      {
        field: 'ytchanneltitle',
        moreValuesAvailable: true,
        values: [
          {
            value: 'BBC Click',
            state: 'idle',
            numberOfResults: 1,
          },
          {
            value: 'BBC HARDtalk',
            state: 'idle',
            numberOfResults: 2,
          },
          {
            value: 'BBC My World',
            state: 'idle',
            numberOfResults: 2,
          },
          {
            value: 'BBC News',
            state: 'idle',
            numberOfResults: 62794,
          },
          {
            value: 'BBC Newsbeat',
            state: 'idle',
            numberOfResults: 7,
          },
          {
            value: 'BBC Newsnight',
            state: 'idle',
            numberOfResults: 21,
          },
          {
            value: 'BBC Trending',
            state: 'idle',
            numberOfResults: 26,
          },
          {
            value: 'BBC World Service',
            state: 'idle',
            numberOfResults: 2,
          },
        ],
        indexScore: 0.23388898600172933,
      },
      {
        field: 'ytvideodimension',
        moreValuesAvailable: false,
        values: [
          {
            value: '2d',
            state: 'idle',
            numberOfResults: 62726,
          },
          {
            value: '3d',
            state: 'idle',
            numberOfResults: 8,
          },
        ],
        indexScore: 0.23386394646849415,
      },
    ],
  },
  categoryFacets: [],
  results: [
    {
      title:
        'Several countries boycott Eurovision after Israel allowed to compete | BBC',
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:jWxMrzEXCZE',
      printableUri: 'https://www.youtube.com/watch?v=jWxMrzEXCZE',
      clickUri: 'https://www.youtube.com/watch?v=jWxMrzEXCZE',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:jWxMrzEXCZE',
      excerpt:
        "Ireland, Spain and the Netherlands will boycott next year's Eurovision Song Contest after it was decided Israel could compete. ... They were among a number of countries who had called for Israel to...",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 521,
      percentScore: 51.361214,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: '7oQhK429ñzbuW5c7',
        urihash: '7oQhK429ñzbuW5c7',
        permanentid:
          'c336706aae89ebe6738283d538adcf6e227f969993d4dbc0c97ef36b6b75',
        syslanguage: ['English'],
        date: 1764883694000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764883694000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        language: ['English'],
        syscollection: 'default',
      },
      Title:
        'Several countries boycott Eurovision after Israel allowed to compete | BBC',
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:jWxMrzEXCZE',
      PrintableUri: 'https://www.youtube.com/watch?v=jWxMrzEXCZE',
      ClickUri: 'https://www.youtube.com/watch?v=jWxMrzEXCZE',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:jWxMrzEXCZE',
      Excerpt:
        "Ireland, Spain and the Netherlands will boycott next year's Eurovision Song Contest after it was decided Israel could compete. ... They were among a number of countries who had called for Israel to...",
      FirstSentences: null,
    },
    {
      title:
        "Why Vladimir Putin is 'morally responsible' for the Novichok poisonings | BBC Newscast",
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:m-pMLw20Hv0',
      printableUri: 'https://www.youtube.com/watch?v=m-pMLw20Hv0',
      clickUri: 'https://www.youtube.com/watch?v=m-pMLw20Hv0',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:m-pMLw20Hv0',
      excerpt:
        'An inquiry into the death of Dawn Sturgess, the woman who died after she came into contact with poison intended for a former Russian agent, has reached the conclusion that President Putin was “mo...',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 521,
      percentScore: 51.361214,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: '8cNR3ðQRmDjvRSWy',
        urihash: '8cNR3ðQRmDjvRSWy',
        permanentid:
          '1a27211ee7e8e2357a5738dede814db7693e9539b079a69610828b137430',
        syslanguage: ['English'],
        date: 1764884930000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764884930000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        language: ['English'],
        syscollection: 'default',
      },
      Title:
        "Why Vladimir Putin is 'morally responsible' for the Novichok poisonings | BBC Newscast",
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:m-pMLw20Hv0',
      PrintableUri: 'https://www.youtube.com/watch?v=m-pMLw20Hv0',
      ClickUri: 'https://www.youtube.com/watch?v=m-pMLw20Hv0',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:m-pMLw20Hv0',
      Excerpt:
        'An inquiry into the death of Dawn Sturgess, the woman who died after she came into contact with poison intended for a former Russian agent, has reached the conclusion that President Putin was “mo...',
      FirstSentences: null,
    },
    {
      title:
        "Putin 'morally responsible' for Novichok poisoning of Dawn Sturgess, inquiry says | BBC News",
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:dNXM3IxMouI',
      printableUri: 'https://www.youtube.com/watch?v=dNXM3IxMouI',
      clickUri: 'https://www.youtube.com/watch?v=dNXM3IxMouI',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:dNXM3IxMouI',
      excerpt:
        'Vladimir Putin was "morally responsible" for the 44-year-old\'s death, alongside everyone involved in the assassination attempt on Russian double agent Sergei Skripal. ... Moscow has always denied i...',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 510,
      percentScore: 50.816124,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: '5YOHBrxZMx3i03vu',
        urihash: '5YOHBrxZMx3i03vu',
        permanentid:
          '9a0a48bd6f3e2975e22ce989d60e7c7f85facafd75156fa28e1949bdfe4d',
        syslanguage: ['English'],
        date: 1764869412000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764869412000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        language: ['English'],
        syscollection: 'default',
      },
      Title:
        "Putin 'morally responsible' for Novichok poisoning of Dawn Sturgess, inquiry says | BBC News",
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:dNXM3IxMouI',
      PrintableUri: 'https://www.youtube.com/watch?v=dNXM3IxMouI',
      ClickUri: 'https://www.youtube.com/watch?v=dNXM3IxMouI',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:dNXM3IxMouI',
      Excerpt:
        'Vladimir Putin was "morally responsible" for the 44-year-old\'s death, alongside everyone involved in the assassination attempt on Russian double agent Sergei Skripal. ... Moscow has always denied i...',
      FirstSentences: null,
    },
    {
      title:
        'CCTV captures raccoon drunk in liquor store. #Raccoon #Scotch #BBCNews',
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:c-_Mn7m2VM8',
      printableUri: 'https://www.youtube.com/watch?v=c-_Mn7m2VM8',
      clickUri: 'https://www.youtube.com/watch?v=c-_Mn7m2VM8',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:c-_Mn7m2VM8',
      excerpt: '',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 506,
      percentScore: 50.616447,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: 'tz4Xñpz3B1vCupcB',
        urihash: 'tz4Xñpz3B1vCupcB',
        permanentid:
          'e8e388478d18684fae15c32c445415c5cab5e7d92af90f4a3ad8d24ca174',
        date: 1764858626000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764858626000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        syscollection: 'default',
      },
      Title:
        'CCTV captures raccoon drunk in liquor store. #Raccoon #Scotch #BBCNews',
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:c-_Mn7m2VM8',
      PrintableUri: 'https://www.youtube.com/watch?v=c-_Mn7m2VM8',
      ClickUri: 'https://www.youtube.com/watch?v=c-_Mn7m2VM8',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:c-_Mn7m2VM8',
      Excerpt: '',
      FirstSentences: null,
    },
    {
      title:
        'Pete Hegseth could have endangered troop safety with Signal chat says Pentagon watchdog | BBC News',
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H9Fjzo8-yuA',
      printableUri: 'https://www.youtube.com/watch?v=H9Fjzo8-yuA',
      clickUri: 'https://www.youtube.com/watch?v=H9Fjzo8-yuA',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H9Fjzo8-yuA',
      excerpt:
        "US Defence Secretary Pete Hegseth could have endangered troops' safety when he used an unsecured app to discuss a planned attack on militants in Yemen, according to a report from the Pentagon's ins...",
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 506,
      percentScore: 50.616447,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: 'lbXhxYñ14UHlIfsD',
        urihash: 'lbXhxYñ14UHlIfsD',
        permanentid:
          '38ab3850f8b7176c7622a7ee0952466e1d697b14dbe5a6fe30c38af7dfc7',
        syslanguage: ['English'],
        date: 1764858057000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764858057000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        language: ['English'],
        syscollection: 'default',
      },
      Title:
        'Pete Hegseth could have endangered troop safety with Signal chat says Pentagon watchdog | BBC News',
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H9Fjzo8-yuA',
      PrintableUri: 'https://www.youtube.com/watch?v=H9Fjzo8-yuA',
      ClickUri: 'https://www.youtube.com/watch?v=H9Fjzo8-yuA',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H9Fjzo8-yuA',
      Excerpt:
        "US Defence Secretary Pete Hegseth could have endangered troops' safety when he used an unsecured app to discuss a planned attack on militants in Yemen, according to a report from the Pentagon's ins...",
      FirstSentences: null,
    },
    {
      title:
        'Has Ella Purnell played the Fallout games? #FalloutNewVegas #Fallout #Gaming #BBCNews',
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:FO2k2s70ObE',
      printableUri: 'https://www.youtube.com/watch?v=FO2k2s70ObE',
      clickUri: 'https://www.youtube.com/watch?v=FO2k2s70ObE',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:FO2k2s70ObE',
      excerpt: '',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 506,
      percentScore: 50.616447,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: 'Xwj1dORVSR0YiDkA',
        urihash: 'Xwj1dORVSR0YiDkA',
        permanentid:
          '1c73412bdfee8b70a14a4209a229c287cebc94fa365d518751b2f92a3290',
        date: 1764862208000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764862208000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        syscollection: 'default',
      },
      Title:
        'Has Ella Purnell played the Fallout games? #FalloutNewVegas #Fallout #Gaming #BBCNews',
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:FO2k2s70ObE',
      PrintableUri: 'https://www.youtube.com/watch?v=FO2k2s70ObE',
      ClickUri: 'https://www.youtube.com/watch?v=FO2k2s70ObE',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:FO2k2s70ObE',
      Excerpt: '',
      FirstSentences: null,
    },
    {
      title:
        'Mum of doctor who gave Matthew Perry ketamine says sorry. #MatthewPerry #BBCNews',
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H-1Oe0gKXfU',
      printableUri: 'https://www.youtube.com/watch?v=H-1Oe0gKXfU',
      clickUri: 'https://www.youtube.com/watch?v=H-1Oe0gKXfU',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H-1Oe0gKXfU',
      excerpt: '',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 498,
      percentScore: 50.214733,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: 'JS0xMvWjY66YJWz3',
        urihash: 'JS0xMvWjY66YJWz3',
        permanentid:
          'e65502cefc9cc755b4614a740fe5db392e5359874fc854bd4da2e4d0b94b',
        date: 1764844552000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764844552000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        syscollection: 'default',
      },
      Title:
        'Mum of doctor who gave Matthew Perry ketamine says sorry. #MatthewPerry #BBCNews',
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H-1Oe0gKXfU',
      PrintableUri: 'https://www.youtube.com/watch?v=H-1Oe0gKXfU',
      ClickUri: 'https://www.youtube.com/watch?v=H-1Oe0gKXfU',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:H-1Oe0gKXfU',
      Excerpt: '',
      FirstSentences: null,
    },
    {
      title:
        "Ilhan Omar calls Trump 'creepy' over his 'obsession' with Somali community. #BBCNews",
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:XCoYn-NcG2k',
      printableUri: 'https://www.youtube.com/watch?v=XCoYn-NcG2k',
      clickUri: 'https://www.youtube.com/watch?v=XCoYn-NcG2k',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:XCoYn-NcG2k',
      excerpt: '',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 498,
      percentScore: 50.214733,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: 'Xj2JYzozsoWm5SK7',
        urihash: 'Xj2JYzozsoWm5SK7',
        permanentid:
          '69e39a0a4e9033b15382f9a0d6ea54ddc30d7ec2108a4225892496820320',
        date: 1764849671000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764849671000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        syscollection: 'default',
      },
      Title:
        "Ilhan Omar calls Trump 'creepy' over his 'obsession' with Somali community. #BBCNews",
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:XCoYn-NcG2k',
      PrintableUri: 'https://www.youtube.com/watch?v=XCoYn-NcG2k',
      ClickUri: 'https://www.youtube.com/watch?v=XCoYn-NcG2k',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:XCoYn-NcG2k',
      Excerpt: '',
      FirstSentences: null,
    },
    {
      title:
        'Suspected blackmail gang operating on Grindr uncovered in BBC investigation | BBC News',
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:9UYp4VPfZMg',
      printableUri: 'https://www.youtube.com/watch?v=9UYp4VPfZMg',
      clickUri: 'https://www.youtube.com/watch?v=9UYp4VPfZMg',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:9UYp4VPfZMg',
      excerpt:
        'Police failed to properly investigate allegations that a gang was blackmailing men on the gay dating app Grindr, the BBC can reveal. ... Our investigation has learned of five cases of suspected bla...',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 491,
      percentScore: 49.860565,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: 'J6LC5icgcvRzeYXs',
        urihash: 'J6LC5icgcvRzeYXs',
        permanentid:
          '9f6d838f4956572105a7573b4dbcfc78c4c1390dfc940d5f2c26685ec334',
        syslanguage: ['English'],
        date: 1764831610000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764831610000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        language: ['English'],
        syscollection: 'default',
      },
      Title:
        'Suspected blackmail gang operating on Grindr uncovered in BBC investigation | BBC News',
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:9UYp4VPfZMg',
      PrintableUri: 'https://www.youtube.com/watch?v=9UYp4VPfZMg',
      ClickUri: 'https://www.youtube.com/watch?v=9UYp4VPfZMg',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:9UYp4VPfZMg',
      Excerpt:
        'Police failed to properly investigate allegations that a gang was blackmailing men on the gay dating app Grindr, the BBC can reveal. ... Our investigation has learned of five cases of suspected bla...',
      FirstSentences: null,
    },
    {
      title:
        'Doctor who sold ketamine to Friends star Matthew Perry is jailed | BBC News',
      uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:vQCZOwOKxP4',
      printableUri: 'https://www.youtube.com/watch?v=vQCZOwOKxP4',
      clickUri: 'https://www.youtube.com/watch?v=vQCZOwOKxP4',
      uniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:vQCZOwOKxP4',
      excerpt:
        'A California doctor who supplied ketamine to Friends star Matthew Perry has been sentenced to 30 months in prison in the US. ... The actor was 54 when he died from a ketamine overdose in 2023, afte...',
      firstSentences: null,
      summary: null,
      flags: 'HasHtmlVersion;HasThumbnail;HasAllMetaDataStream',
      hasHtmlVersion: true,
      hasMobileHtmlVersion: false,
      score: 480,
      percentScore: 49.29888,
      rankingInfo: null,
      rating: 0.0,
      isTopResult: false,
      isRecommendation: false,
      isUserActionView: false,
      titleHighlights: [],
      firstSentencesHighlights: [],
      excerptHighlights: [],
      printableUriHighlights: [],
      summaryHighlights: [],
      parentResult: null,
      childResults: [],
      totalNumberOfChildResults: 0,
      absentTerms: [],
      raw: {
        sysauthor: ['BBC News'],
        sysurihash: 'uvxEPVN7PNq0ðhyd',
        urihash: 'uvxEPVN7PNq0ðhyd',
        permanentid:
          '72026f656a1c83e4296d214092d5693cba2e89d8ac5589055e434a8c940f',
        syslanguage: ['English'],
        date: 1764801164000,
        sourcetype: 'YouTube',
        syssource: 'Coveo Samples - Youtube BBC News',
        sysdate: 1764801164000,
        author: ['BBC News'],
        source: 'Coveo Samples - Youtube BBC News',
        collection: 'default',
        syssourcetype: 'YouTube',
        filetype: 'YouTubeVideo',
        sysfiletype: 'YouTubeVideo',
        language: ['English'],
        syscollection: 'default',
      },
      Title:
        'Doctor who sold ketamine to Friends star Matthew Perry is jailed | BBC News',
      Uri: 'https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:vQCZOwOKxP4',
      PrintableUri: 'https://www.youtube.com/watch?v=vQCZOwOKxP4',
      ClickUri: 'https://www.youtube.com/watch?v=vQCZOwOKxP4',
      UniqueId:
        '42.13613$https://youtube.com/User:bbcnews/Channel:UC16niRr50-MSBwiO3YDb3RA/Video:vQCZOwOKxP4',
      Excerpt:
        'A California doctor who supplied ketamine to Friends star Matthew Perry has been sentenced to 30 months in prison in the US. ... The actor was 54 when he died from a ketamine overdose in 2023, afte...',
      FirstSentences: null,
    },
  ],
  questionAnswer: {
    answerFound: false,
    question: '',
    answerSnippet: '',
    documentId: {
      contentIdKey: '',
      contentIdValue: '',
    },
    score: 0.0,
    relatedQuestions: [],
  },
  extendedResults: {},
};
