/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AtomicHostedPage {
        "initialize": (options: AtomicPageInitializationOptions) => Promise<void>;
    }
}
declare global {
    interface HTMLAtomicHostedPageElement extends Components.AtomicHostedPage, HTMLStencilElement {
    }
    var HTMLAtomicHostedPageElement: {
        prototype: HTMLAtomicHostedPageElement;
        new (): HTMLAtomicHostedPageElement;
    };
    interface HTMLElementTagNameMap {
        "atomic-hosted-page": HTMLAtomicHostedPageElement;
    }
}
declare namespace LocalJSX {
    interface AtomicHostedPage {
    }
    interface IntrinsicElements {
        "atomic-hosted-page": AtomicHostedPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "atomic-hosted-page": LocalJSX.AtomicHostedPage & JSXBase.HTMLAttributes<HTMLAtomicHostedPageElement>;
        }
    }
}
