/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PlatformEnvironment } from "@coveo/headless";
export { PlatformEnvironment } from "@coveo/headless";
export namespace Components {
    /**
     * A Web Component used to inject a Coveo Hosted Search Page in the DOM.
     * Pulls from the [Search Interfaces API](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20Interface%20Service#/)
     */
    interface AtomicHostedUi {
        /**
          * Returns the unique, organization-specific endpoint(s).
          * @param organizationId
          * @param env
         */
        "getOrganizationEndpoints": (organizationId: string, env?: PlatformEnvironment) => Promise<{ platform: string; analytics: string; search: string; admin: string; }>;
        /**
          * The type of hosted search page to load.
         */
        "hostedType": 'trial' | 'builder' | 'code';
        "initialize": (options: AtomicHostedUIInitializationOptions) => Promise<void>;
    }
}
declare global {
    /**
     * A Web Component used to inject a Coveo Hosted Search Page in the DOM.
     * Pulls from the [Search Interfaces API](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20Interface%20Service#/)
     */
    interface HTMLAtomicHostedUiElement extends Components.AtomicHostedUi, HTMLStencilElement {
    }
    var HTMLAtomicHostedUiElement: {
        prototype: HTMLAtomicHostedUiElement;
        new (): HTMLAtomicHostedUiElement;
    };
    interface HTMLElementTagNameMap {
        "atomic-hosted-ui": HTMLAtomicHostedUiElement;
    }
}
declare namespace LocalJSX {
    /**
     * A Web Component used to inject a Coveo Hosted Search Page in the DOM.
     * Pulls from the [Search Interfaces API](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20Interface%20Service#/)
     */
    interface AtomicHostedUi {
        /**
          * The type of hosted search page to load.
         */
        "hostedType"?: 'trial' | 'builder' | 'code';
    }
    interface IntrinsicElements {
        "atomic-hosted-ui": AtomicHostedUi;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A Web Component used to inject a Coveo Hosted Search Page in the DOM.
             * Pulls from the [Search Interfaces API](https://platform.cloud.coveo.com/docs?urls.primaryName=Search%20Interface%20Service#/)
             */
            "atomic-hosted-ui": LocalJSX.AtomicHostedUi & JSXBase.HTMLAttributes<HTMLAtomicHostedUiElement>;
        }
    }
}
