import {NumberValue, Schema} from '@coveo/bueno';
import {
  type AutomaticFacetGenerator,
  type AutomaticFacetGeneratorState,
  buildAutomaticFacetGenerator,
  buildSearchStatus,
  type SearchStatus,
  type SearchStatusState,
} from '@coveo/headless';
import {html, LitElement, nothing} from 'lit';
import {customElement, property, state} from 'lit/decorators.js';
import {keyed} from 'lit/directives/keyed.js';
import {renderFacetPlaceholder} from '@/src/components/common/facets/facet-placeholder/facet-placeholder';
import {ValidatePropsController} from '@/src/components/common/validate-props-controller/validate-props-controller';
import type {Bindings} from '@/src/components/search/atomic-search-interface/atomic-search-interface';
import {bindStateToController} from '@/src/decorators/bind-state';
import {bindingGuard} from '@/src/decorators/binding-guard';
import {bindings} from '@/src/decorators/bindings';
import {errorGuard} from '@/src/decorators/error-guard';
import type {InitializableComponent} from '@/src/decorators/types';
import {LightDomMixin} from '@/src/mixins/light-dom';
import '@/src/components/search/atomic-automatic-facet/atomic-automatic-facet';

/**
 * The `atomic-automatic-facet-generator` is a component that renders the facets from
 * the automatic facets feature. Unlike regular facets, which need to be explicitly defined
 * and requested in the query, automatic facets are dynamically generated by the index
 * in response to the search query.
 *
 * **Note:** This component renders one or more [automatic facets](https://docs.coveo.com/en/atomic/latest/reference/components/atomic-automatic-facet/) based on the `desiredCount` property.
 *
 * To learn more about the automatic facet generator feature, see: [About the Facet Generator](https://docs.coveo.com/en/n9sd0159/).
 */
@customElement('atomic-automatic-facet-generator')
@bindings()
export class AtomicAutomaticFacetGenerator
  extends LightDomMixin(LitElement)
  implements InitializableComponent<Bindings>
{
  /**
   * The desired count of automatic facets.
   *
   * Minimum: `1`
   * Maximum: `20`
   */
  @property({type: Number, reflect: true, attribute: 'desired-count'})
  public desiredCount = 5;

  /**
   * The desired number of automatically generated facet values.
   *
   * Minimum: `1`
   */
  @property({type: Number, reflect: true, attribute: 'number-of-values'})
  public numberOfValues = 8;

  @state() public bindings!: Bindings;
  @state() public error!: Error;

  @bindStateToController('automaticFacetGenerator')
  @state()
  private automaticFacetGeneratorState!: AutomaticFacetGeneratorState;
  public automaticFacetGenerator!: AutomaticFacetGenerator;

  @bindStateToController('searchStatus')
  @state()
  public searchStatusState!: SearchStatusState;
  public searchStatus!: SearchStatus;

  @state() private collapseFacetsAfter = -1;

  private static readonly propsSchema = new Schema({
    desiredCount: new NumberValue({min: 1, max: 20, required: false}),
    numberOfValues: new NumberValue({min: 1, required: false}),
  });

  constructor() {
    super();
    new ValidatePropsController(
      this,
      () => ({
        desiredCount: this.desiredCount,
        numberOfValues: this.numberOfValues,
      }),
      AtomicAutomaticFacetGenerator.propsSchema,
      false
    );
  }

  public initialize() {
    this.searchStatus = buildSearchStatus(this.bindings.engine);
    this.automaticFacetGenerator = buildAutomaticFacetGenerator(
      this.bindings.engine,
      {
        options: {
          desiredCount: this.desiredCount,
          numberOfValues: this.numberOfValues,
        },
      }
    );
  }

  /**
   * Updates the collapse facets after value depending on the number of visible facets.
   * @param collapseAfter - The value after which facets should be collapsed.
   * @param numberOfVisibleFacets - The number of currently visible facets.
   */
  public updateCollapseFacetsDependingOnFacetsVisibility(
    collapseAfter: number,
    numberOfVisibleFacets: number
  ) {
    if (collapseAfter === -1) {
      this.collapseFacetsAfter = -1;
      return;
    }
    this.collapseFacetsAfter = Math.max(
      0,
      collapseAfter - numberOfVisibleFacets
    );
  }

  @bindingGuard()
  @errorGuard()
  render() {
    if (!this.searchStatusState.firstSearchExecuted) {
      return this.renderPlaceholders();
    }

    return this.renderAutomaticFacets();
  }

  private renderPlaceholders() {
    return html`${Array.from({length: this.desiredCount}, (_, index) =>
      renderFacetPlaceholder({
        props: {
          numberOfValues: this.numberOfValues,
          isCollapsed: this.shouldCollapseFacet(index),
        },
      })
    )}`;
  }

  private renderAutomaticFacets() {
    if (this.automaticFacetGeneratorState.automaticFacets.length === 0) {
      return nothing;
    }

    return html`${this.automaticFacetGeneratorState.automaticFacets.map(
      (facet, index) =>
        keyed(
          facet.state.field,
          html`
            <atomic-automatic-facet
              .field=${facet.state.field}
              .facetId=${facet.state.field}
              .facet=${facet}
              .searchStatus=${this.searchStatus}
              ?isCollapsed=${this.shouldCollapseFacet(index)}
            ></atomic-automatic-facet>
          `
        )
    )}`;
  }

  private shouldCollapseFacet(index: number): boolean {
    if (this.collapseFacetsAfter === -1) {
      return false;
    }
    return this.collapseFacetsAfter
      ? index + 1 > this.collapseFacetsAfter
      : true;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'atomic-automatic-facet-generator': AtomicAutomaticFacetGenerator;
  }
}
