import {isNullOrUndefined} from '@coveo/bueno';
import type {AutomaticFacet, FacetValue, SearchStatus} from '@coveo/headless';
import {html, LitElement, nothing} from 'lit';
import {customElement, property, state} from 'lit/decorators.js';
import {when} from 'lit/directives/when.js';
import facetCommonStyles from '@/src/components/common/facets/facet-common.tw.css';
import {renderFacetContainer} from '@/src/components/common/facets/facet-container/facet-container';
import {renderFacetHeader} from '@/src/components/common/facets/facet-header/facet-header';
import {renderFacetValueCheckbox} from '@/src/components/common/facets/facet-value-checkbox/facet-value-checkbox';
import facetValueCheckboxStyles from '@/src/components/common/facets/facet-value-checkbox/facet-value-checkbox.tw.css';
import {renderFacetValueLabelHighlight} from '@/src/components/common/facets/facet-value-label-highlight/facet-value-label-highlight';
import {renderFacetValuesGroup} from '@/src/components/common/facets/facet-values-group/facet-values-group';
import type {Bindings} from '@/src/components/search/atomic-search-interface/atomic-search-interface';
import {bindingGuard} from '@/src/decorators/binding-guard';
import {bindings} from '@/src/decorators/bindings';
import {errorGuard} from '@/src/decorators/error-guard';
import type {InitializableComponent} from '@/src/decorators/types';
import {withTailwindStyles} from '@/src/decorators/with-tailwind-styles';
import {InitializeBindingsMixin} from '@/src/mixins/bindings-mixin';
import {FocusTargetController} from '@/src/utils/accessibility-utils';
import {getFieldValueCaption} from '@/src/utils/field-utils';

/**
 * The `atomic-automatic-facet` component is a special type of facet generated by the automatic facets feature.
 * Unlike regular facets, which need to be explicitly defined and requested in the query,
 * automatic facets are dynamically generated by the index in response to the query.
 *
 * **Note:** This component should never be used on its own. It is used internally by the `atomic-automatic-facet-generator`
 * component to automatically render updated facets. However, you can use the shadow parts to style the automatically generated facets.
 *
 * To learn more about the automatic facet generator feature, see: [About the Facet Generator](https://docs.coveo.com/en/n9sd0159/).
 *
 * @part facet - The wrapper for the entire facet.
 *
 * @part label-button - The button that displays the label and allows to expand/collapse the facet.
 * @part label-button-icon - The label button icon.
 * @part clear-button - The button that resets the actively selected facet values.
 * @part clear-button-icon - The clear button icon.
 *
 * @part values - The facet values container.
 * @part value-label - The facet value label, common for all displays.
 * @part value-count - The facet value count, common for all displays.
 *
 * @part value-checkbox - The facet value checkbox, available when display is 'checkbox'.
 * @part value-checkbox-checked - The checked facet value checkbox, available when display is 'checkbox'.
 * @part value-checkbox-label - The facet value checkbox clickable label, available when display is 'checkbox'.
 * @part value-checkbox-icon - The facet value checkbox icon, available when display is 'checkbox'.
 */
@customElement('atomic-automatic-facet')
@bindings()
@withTailwindStyles
export class AtomicAutomaticFacet
  extends InitializeBindingsMixin(LitElement)
  implements InitializableComponent<Bindings>
{
  static styles = [facetCommonStyles, facetValueCheckboxStyles];

  @state() bindings!: Bindings;
  @state() public error!: Error;

  /**
   * The field associated with the automatic facet.
   * @internal
   */
  @property({type: String, reflect: true}) public field!: string;

  /**
   * The unique identifier for the automatic facet.
   * @internal
   */
  @property({type: String, attribute: 'facet-id', reflect: true})
  public facetId!: string;

  /**
   * The automatic facet controller instance.
   * @internal
   */
  @property({type: Object, reflect: true}) public facet!: AutomaticFacet;

  /**
   * The search status controller instance.
   * @internal
   */
  @property({type: Object, attribute: 'search-status', reflect: true})
  public searchStatus!: SearchStatus;

  /**
   * Whether the facet is collapsed.
   * @internal
   */
  @property({type: Boolean, attribute: 'is-collapsed', reflect: true})
  public isCollapsed = false;

  private headerFocus?: FocusTargetController;

  public initialize() {}

  private get focusTarget() {
    if (!this.headerFocus) {
      this.headerFocus = new FocusTargetController(this, this.bindings);
    }
    return this.headerFocus;
  }

  private get numberOfSelectedValues() {
    return this.facet.state.values.filter((value) => this.isSelected(value))
      .length;
  }

  private isSelected(value: FacetValue) {
    return value.state === 'selected';
  }

  private get label() {
    return isNullOrUndefined(this.facet.state.label)
      ? this.facet.state.field
      : this.facet.state.label;
  }

  private renderValue(facetValue: FacetValue, onClick: () => void) {
    const displayValue = getFieldValueCaption(
      this.facet.state.field,
      facetValue.value,
      this.bindings.i18n
    );

    return renderFacetValueCheckbox({
      props: {
        displayValue,
        numberOfResults: facetValue.numberOfResults,
        isSelected: this.isSelected(facetValue),
        i18n: this.bindings.i18n,
        onClick,
      },
    })(
      html`${renderFacetValueLabelHighlight({
        props: {
          displayValue,
          isSelected: this.isSelected(facetValue),
        },
      })}`
    );
  }

  private renderValuesContainer(children: unknown[], query?: string) {
    return renderFacetValuesGroup({
      props: {
        i18n: this.bindings.i18n,
        label: this.facet.state.label,
        query,
      },
    })(html`<ul class="mt-3" part="values">${children}</ul>`);
  }

  private renderValues() {
    return this.renderValuesContainer(
      this.facet.state.values.map((value) =>
        this.renderValue(value, () => this.facet.toggleSelect(value))
      )
    );
  }

  private renderHeader() {
    return renderFacetHeader({
      props: {
        i18n: this.bindings.i18n,
        label: this.label,
        onClearFilters: () => {
          this.focusTarget.focusAfterSearch();
          this.facet.deselectAll();
        },
        numberOfActiveValues: this.numberOfSelectedValues,
        isCollapsed: this.isCollapsed,
        headingLevel: 0,
        onToggleCollapse: () => {
          this.isCollapsed = !this.isCollapsed;
        },
        headerRef: (el) => this.focusTarget.setTarget(el),
      },
    });
  }

  @bindingGuard()
  @errorGuard()
  render() {
    if (this.searchStatus.state.hasError) {
      return html`${nothing}`;
    }

    return renderFacetContainer()(html`
      ${this.renderHeader()} ${when(!this.isCollapsed, () => this.renderValues())}
    `);
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'atomic-automatic-facet': AtomicAutomaticFacet;
  }
}
