import {buildRoutedResponse} from './shared.js';
import {SearchApiResponse, type ConverseEvent} from '../events.js';

const searchApiResponse: ConverseEvent = SearchApiResponse({
  content: {
    totalCount: 4,
    totalCountFiltered: 4,
    duration: 19,
    indexDuration: 7,
    requestDuration: 13,
    searchUid: 'b7a22385-d59b-4153-a07f-63424b1d691c',
    pipeline: 'empty',
    apiVersion: 2,
    queryCorrections: [],
    index: 'barcasportsmcy01fvu-l56dsftu-Indexer-1-r65oq43natljouzp7wev7gcmfe',
    logicalIndex: 'default',
    indexRegion: 'us-east-1',
    indexToken:
      'YmFyY2FzcG9ydHNtY3kwMWZ2dS1sNTZkc2Z0dS1JbmRleGVyLTEtcjY1b3E0M25hdGxqb3V6cDd3ZXY3Z2NtZmU=',
    refinedKeywords: [],
    triggers: [],
    termsToHighlight: {
      surfboard: ['surfboards'],
      care: ['cared', 'careful', 'carefully', 'cares', 'caring'],
    },
    phrasesToHighlight: {},
    groupByResults: [],
    facets: [
      {
        field: 'source',
        moreValuesAvailable: false,
        values: [
          {
            value: 'Sports - Blog',
            state: 'selected',
            numberOfResults: 4,
          },
          {
            value: 'Shopify',
            state: 'idle',
            numberOfResults: 6,
          },
          {
            value: 'shopify:alz_test_quickstart_f7241a32-en-CA-CAD',
            state: 'idle',
            numberOfResults: 2,
          },
          {
            value: 'shopify:quickstart_f7241a32-en-CA-CAD',
            state: 'idle',
            numberOfResults: 2,
          },
          {
            value: 'Sports',
            state: 'idle',
            numberOfResults: 4,
          },
          {
            value: 'Sports2026',
            state: 'idle',
            numberOfResults: 4,
          },
        ],
        indexScore: 0.08,
      },
      {
        field: 'objecttype',
        moreValuesAvailable: false,
        values: [
          {
            value: 'Article',
            state: 'idle',
            numberOfResults: 4,
          },
        ],
        indexScore: 0.2342634430843858,
        label: 'Object Type',
      },
      {
        field: 'filetype',
        moreValuesAvailable: false,
        values: [
          {
            value: 'html',
            state: 'idle',
            numberOfResults: 4,
          },
        ],
        indexScore: 0.2123437081741416,
      },
    ],
    suggestedFacets: [],
    categoryFacets: [],
    results: [
      {
        title: 'Wax or no wax? – Barca Sports Blog',
        uri: 'https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        printableUri: 'https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        clickUri: 'https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        uniqueId: '42.32075$https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        primaryid: 'LJZHQR3HKXB3AWLUJMZXEWCDPFRC4MZSGA3TKLTEMVTGC5LMOQ',
        excerpt:
          'Waxing a surfboard is an important step in the process of owning and caring for your board. ... etc., which can cause damage over time if not taken care of properly – reducing its lifespan ...',
        firstSentences: null,
        summary: null,
        flags: 'HasHtmlVersion;HasAllMetaDataStream',
        hasHtmlVersion: true,
        hasMobileHtmlVersion: false,
        score: 3506,
        percentScore: 64.72844,
        rankingInfo: null,
        rating: 0,
        isTopResult: false,
        isRecommendation: false,
        isUserActionView: false,
        titleHighlights: [],
        firstSentencesHighlights: [],
        excerptHighlights: [
          {
            length: 9,
            offset: 9,
          },
          {
            length: 6,
            offset: 69,
          },
          {
            length: 4,
            offset: 148,
          },
        ],
        printableUriHighlights: [],
        summaryHighlights: [],
        parentResult: null,
        childResults: [],
        totalNumberOfChildResults: 0,
        absentTerms: [],
        raw: {
          sysurihash: 'ZrxGgUðYtK3rXCyb',
          urihash: 'ZrxGgUðYtK3rXCyb',
          sysindexeddate: 1761049878000,
          permanentid: '897b4167c1b1e616a93371de147e00f6604656f9fce46c12679a0770e95d',
          date: 1673321097000,
          objecttype: 'Article',
          sourcetype: 'Sitemap',
          rowid: 1761049877996023300,
          syssource: 'Sports - Blog',
          sysdate: 1673321097000,
          primaryid: 'LJZHQR3HKXB3AWLUJMZXEWCDPFRC4MZSGA3TKLTEMVTGC5LMOQ',
          source: 'Sports - Blog',
          syssourcetype: 'Sitemap',
          indexeddate: 1761049878000,
          filetype: 'html',
          sysfiletype: 'html',
          sysrowid: 1761049877996023300,
        },
        Title: 'Wax or no wax? – Barca Sports Blog',
        Uri: 'https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        PrintableUri: 'https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        ClickUri: 'https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        UniqueId: '42.32075$https://barca356.wordpress.com/2022/12/12/wax-or-no-wax/',
        Excerpt:
          'Waxing a surfboard is an important step in the process of owning and caring for your board. ... etc., which can cause damage over time if not taken care of properly – reducing its lifespan ...',
        FirstSentences: null,
      },
      {
        title: 'What to look for when buying a surf board? – Barca Sports Blog',
        uri: 'https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        printableUri:
          'https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        clickUri:
          'https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        uniqueId:
          '42.32075$https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        primaryid: 'G7B3AUCCKRIU4NRVOJHUUULNORYS4MZSGA3TKLTEMVTGC5LMOQ',
        excerpt:
          'What to look for when buying a surf board? Buying a surfboard is a fun, but important process. ... Maintenance: Surfboards require maintenance and care to keep them in good condition.',
        firstSentences: null,
        summary: null,
        flags: 'HasHtmlVersion;HasAllMetaDataStream',
        hasHtmlVersion: true,
        hasMobileHtmlVersion: false,
        score: 3477,
        percentScore: 64.460175,
        rankingInfo: null,
        rating: 0,
        isTopResult: false,
        isRecommendation: false,
        isUserActionView: false,
        titleHighlights: [],
        firstSentencesHighlights: [],
        excerptHighlights: [
          {
            length: 9,
            offset: 52,
          },
          {
            length: 10,
            offset: 112,
          },
          {
            length: 4,
            offset: 147,
          },
        ],
        printableUriHighlights: [],
        summaryHighlights: [],
        parentResult: null,
        childResults: [],
        totalNumberOfChildResults: 0,
        absentTerms: [],
        raw: {
          sysurihash: '7ðPBTQN65rOJQmtq',
          urihash: '7ðPBTQN65rOJQmtq',
          sysindexeddate: 1761049874000,
          permanentid: 'db8b4912f4b499426ce61e0fb5c3196c459cea2eb113bc5967c5dca1d073',
          date: 1673321096000,
          objecttype: 'Article',
          sourcetype: 'Sitemap',
          rowid: 1761049874948159500,
          syssource: 'Sports - Blog',
          sysdate: 1673321096000,
          primaryid: 'G7B3AUCCKRIU4NRVOJHUUULNORYS4MZSGA3TKLTEMVTGC5LMOQ',
          source: 'Sports - Blog',
          syssourcetype: 'Sitemap',
          indexeddate: 1761049874000,
          filetype: 'html',
          sysfiletype: 'html',
          sysrowid: 1761049874948159500,
        },
        Title: 'What to look for when buying a surf board? – Barca Sports Blog',
        Uri: 'https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        PrintableUri:
          'https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        ClickUri:
          'https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        UniqueId:
          '42.32075$https://barca356.wordpress.com/2022/12/12/what-to-look-for-when-buying-a-surf-board/',
        Excerpt:
          'What to look for when buying a surf board? Buying a surfboard is a fun, but important process. ... Maintenance: Surfboards require maintenance and care to keep them in good condition.',
        FirstSentences: null,
      },
      {
        title: 'First Time Surfer? – Barca Sports Blog',
        uri: 'https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        printableUri: 'https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        clickUri: 'https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        uniqueId: '42.32075$https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        primaryid: 'JJQXQY2BNEYHQZDZHBZVINJWMIXDGMRQG42S4ZDFMZQXK3DU',
        excerpt:
          'Surfboard Wax is an important part of having an enjoyable experience in the water. ... Make sure to check labels carefully and avoid products containing oxybenzone due its detrimental effects ...',
        firstSentences: null,
        summary: null,
        flags: 'HasHtmlVersion;HasAllMetaDataStream',
        hasHtmlVersion: true,
        hasMobileHtmlVersion: false,
        score: 3001,
        percentScore: 59.885567,
        rankingInfo: null,
        rating: 0,
        isTopResult: false,
        isRecommendation: false,
        isUserActionView: false,
        titleHighlights: [],
        firstSentencesHighlights: [],
        excerptHighlights: [
          {
            length: 9,
            offset: 0,
          },
          {
            length: 9,
            offset: 113,
          },
        ],
        printableUriHighlights: [],
        summaryHighlights: [],
        parentResult: null,
        childResults: [],
        totalNumberOfChildResults: 0,
        absentTerms: [],
        raw: {
          sysurihash: 'JaxcAi0xdy8sT56b',
          urihash: 'JaxcAi0xdy8sT56b',
          sysindexeddate: 1761049874000,
          permanentid: '190117e2f7bc7e8366df9595ff10a802a162c9a9184f01e725c6cfdfc592',
          date: 1673404328000,
          objecttype: 'Article',
          sourcetype: 'Sitemap',
          rowid: 1761049874893416200,
          syssource: 'Sports - Blog',
          sysdate: 1673404328000,
          primaryid: 'JJQXQY2BNEYHQZDZHBZVINJWMIXDGMRQG42S4ZDFMZQXK3DU',
          source: 'Sports - Blog',
          syssourcetype: 'Sitemap',
          indexeddate: 1761049874000,
          filetype: 'html',
          sysfiletype: 'html',
          sysrowid: 1761049874893416200,
        },
        Title: 'First Time Surfer? – Barca Sports Blog',
        Uri: 'https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        PrintableUri: 'https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        ClickUri: 'https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        UniqueId: '42.32075$https://barca356.wordpress.com/2023/01/10/first-time-surfer/',
        Excerpt:
          'Surfboard Wax is an important part of having an enjoyable experience in the water. ... Make sure to check labels carefully and avoid products containing oxybenzone due its detrimental effects ...',
        FirstSentences: null,
      },
      {
        title: 'Racking like a King – Barca Sports Blog',
        uri: 'https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        printableUri: 'https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        clickUri: 'https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        uniqueId: '42.32075$https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        primaryid: 'YOYUMV3WGVMUWWSTKFXXOODNOVKC4MZSGA3TKLTEMVTGC5LMOQ',
        excerpt:
          'Next, place the board into the rack with care and make sure it is secured tightly with straps so that it ... When racking up surfboards and paddleboards securely on a vehicle, ensure that all ...',
        firstSentences: null,
        summary: null,
        flags: 'HasHtmlVersion;HasAllMetaDataStream',
        hasHtmlVersion: true,
        hasMobileHtmlVersion: false,
        score: 2930,
        percentScore: 59.172916,
        rankingInfo: null,
        rating: 0,
        isTopResult: false,
        isRecommendation: false,
        isUserActionView: false,
        titleHighlights: [],
        firstSentencesHighlights: [],
        excerptHighlights: [
          {
            length: 4,
            offset: 41,
          },
          {
            length: 10,
            offset: 125,
          },
        ],
        printableUriHighlights: [],
        summaryHighlights: [],
        parentResult: null,
        childResults: [],
        totalNumberOfChildResults: 0,
        absentTerms: [],
        raw: {
          sysurihash: 'ñFWv5YKZSQow8muT',
          urihash: 'ñFWv5YKZSQow8muT',
          sysindexeddate: 1761049873000,
          permanentid: '306c55ce81cdf9de01762914da7f4215866bd9e513e6f644a7637ca8490d',
          date: 1670881110000,
          objecttype: 'Article',
          sourcetype: 'Sitemap',
          rowid: 1761049873565254100,
          syssource: 'Sports - Blog',
          sysdate: 1670881110000,
          primaryid: 'YOYUMV3WGVMUWWSTKFXXOODNOVKC4MZSGA3TKLTEMVTGC5LMOQ',
          source: 'Sports - Blog',
          syssourcetype: 'Sitemap',
          indexeddate: 1761049873000,
          filetype: 'html',
          sysfiletype: 'html',
          sysrowid: 1761049873565254100,
        },
        Title: 'Racking like a King – Barca Sports Blog',
        Uri: 'https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        PrintableUri: 'https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        ClickUri: 'https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        UniqueId: '42.32075$https://barca356.wordpress.com/2022/12/12/racking-like-a-king/',
        Excerpt:
          'Next, place the board into the rack with care and make sure it is secured tightly with straps so that it ... When racking up surfboards and paddleboards securely on a vehicle, ensure that all ...',
        FirstSentences: null,
      },
    ],
    extendedResults: {},
  },
});

const response6Events: ConverseEvent[] = buildRoutedResponse({
  routedEvent: searchApiResponse,
});

export {response6Events};
