apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: headless
  title: '@coveo/headless'
  description: A headless library for building search experiences on the Coveo platform
  annotations:
    github.com/project-slug: coveo/ui-kit
spec:
  type: library
  lifecycle: production
  owner: dxui
  dependsOn:
    - bueno
  dependencyOf:
    - atomic
    - quantic
