apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: headless
  title: '@coveo/headless'
  description: A headless library for building search experiences on the Coveo platform
spec:
  type: library
  lifecycle: production
  owner: group:default/dxui
  system: ui-kit
  dependsOn:
    - component:bueno
