export const baseResponse = {
  responseId: '123e4567-e89b-12d3-a456-426614174000',
  products: [
    {
      permanentid: 'product-1',
      ec_name: 'Sample Product 1',
      ec_price: 99.99,
      clickUri: 'https://example.com/product/1',
      ec_brand: 'Sample Brand',
      ec_category: 'Electronics',
      children: [],
    },
    {
      permanentid: 'product-2',
      ec_name: 'Sample Product 2',
      ec_price: 149.99,
      clickUri: 'https://example.com/product/2',
      ec_brand: 'Sample Brand',
      ec_category: 'Electronics',
      children: [],
    },
  ],
  results: [],
  facets: [],
  pagination: {
    page: 0,
    perPage: 10,
    totalEntries: 2,
    totalPages: 1,
  },
  sort: {
    appliedSort: {
      sortCriteria: 'relevance',
    },
    availableSorts: [
      {
        sortCriteria: 'relevance',
      },
    ],
  },
  triggers: [],
};

export const richResponse = {
  responseId: '6bb81209-d3e1-4fc7-b5d4-665026e44d72',
  products: [
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Blue Lagoon Mat',
      ec_description:
        "This Huge Blue inflatable mat is perfect for parties or events on water. It measures 120in x 60in and is made of durable, weatherproof material. It's easy to set up and can be folded for storage.",
      ec_shortdesc:
        "This Huge Blue inflatable mat is perfect for parties or events on water. It measures 120in x 60in and is made of durable, weatherproof material. It's easy to set up and can be folded for storage.",
      ec_brand: 'Aqua Marina',
      ec_category: [
        'Games & Toys',
        'Games & Toys|Trampolines & Floats',
        'Games & Toys|Trampolines & Floats|Huge inflatable mats',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Trampolines%20%26%20Floats/Huge%20inflatable%20mats/3_Blue/df1a99488425_bottom_right.webp',
        'https://images.barca.group/Sports/mj/Trampolines%20%26%20Floats/Huge%20inflatable%20mats/3_Blue/df1a99488425_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Trampolines%20%26%20Floats/Huge%20inflatable%20mats/3_Blue/df1a99488425_bottom_right.webp',
        'https://images.barca.group/Sports/mj/Trampolines%20%26%20Floats/Huge%20inflatable%20mats/3_Blue/df1a99488425_bottom_left.webp',
      ],
      ec_price: 1000.0,
      ec_promo_price: 1000.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP00021',
      ec_rating: 4.0,
      ec_product_id: 'SP00021_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Games_Toys/Trampolines_Floats/Huge_inflatable_mats',
      clickUri: 'https://sports.barca.group/pdp/SP00021_00001',
      permanentid: 'SP00021_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Al Fresco Bottle',
      ec_description:
        "A white sport water bottle is the perfect way to stay hydrated while you're on the go. The wide-mouth design makes it easy to refill, and the bottle is tough enough to stand up to the rigors of athletic activity.",
      ec_shortdesc:
        "A white sport water bottle is the perfect way to stay hydrated while you're on the go. The wide-mouth design makes it easy to refill, and the bottle is tough enough to stand up to the rigors of athletic activity.",
      ec_brand: 'NRS',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Water Bottles',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_White/b11c4f02c96f_top_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_White/b11c4f02c96f_top_left.webp',
      ],
      ec_price: 16.0,
      ec_promo_price: 16.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03929',
      ec_rating: 3.0,
      ec_product_id: 'SP03929_00007',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
      clickUri: 'https://sports.barca.group/pdp/SP03929_00007',
      permanentid: 'SP03929_00007',
      children: [
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Khaki Bottle',
          ec_description:
            'A khaki sport water bottle is perfect for on-the-go hydration. The bottle is made of durable, leak-resistant material and comes with a built-in straw. The bottle is also designed to fit effortlessly in your hand, making it easy to take along with you wherever you go.',
          ec_shortdesc:
            'A khaki sport water bottle is perfect for on-the-go hydration. The bottle is made of durable, leak-resistant material and comes with a built-in straw. The bottle is also designed to fit effortlessly in your hand, making it easy to take along with you wherever you go.',
          ec_brand: 'NRS',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Khaki/ea4e43931305_top_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Khaki/ea4e43931305_top_left.webp',
          ],
          ec_price: 16.0,
          ec_promo_price: 16.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03929',
          ec_rating: 3.0,
          ec_product_id: 'SP03929_00012',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03929_00012',
          permanentid: 'SP03929_00012',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Charger Blue Bottle',
          ec_description:
            'This is a blue sport water bottle with a built in filter and a soft silicone grip. It comes with a carrying case and is BPA free.',
          ec_shortdesc:
            'This is a blue sport water bottle with a built in filter and a soft silicone grip. It comes with a carrying case and is BPA free.',
          ec_brand: 'NRS',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Blue/4817b0af6822_top_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Blue/4817b0af6822_top_left.webp',
          ],
          ec_price: 16.0,
          ec_promo_price: 16.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03929',
          ec_rating: 3.0,
          ec_product_id: 'SP03929_00008',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03929_00008',
          permanentid: 'SP03929_00008',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Racer Water Bottle',
          ec_description:
            'This is a red sport water bottle. It is made of sturdy plastic and has a screw-on lid. It is perfect for carrying your drink with you wherever you go!',
          ec_shortdesc:
            'This is a red sport water bottle. It is made of sturdy plastic and has a screw-on lid. It is perfect for carrying your drink with you wherever you go!',
          ec_brand: 'NRS',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Red/9f7477c22916_top_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Red/9f7477c22916_top_left.webp',
          ],
          ec_price: 16.0,
          ec_promo_price: 16.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03929',
          ec_rating: 3.0,
          ec_product_id: 'SP03929_00002',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03929_00002',
          permanentid: 'SP03929_00002',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Ophoria Bottle',
          ec_description:
            'This Orange sport water bottle is perfect for on-the-go hydration. The BPA free and leak proof design means that you can stay hydrated throughout your workout without fearing spills. The wide mouth makes it easy to pour your drink and the rubber grip prevents it from slipping out of your hands.',
          ec_shortdesc:
            'This Orange sport water bottle is perfect for on-the-go hydration. The BPA free and leak proof design means that you can stay hydrated throughout your workout without fearing spills. The wide mouth makes it easy to pour your drink and the rubber grip prevents it from slipping out of your hands.',
          ec_brand: 'NRS',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Orange/78ed62b61e55_top_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Orange/78ed62b61e55_top_left.webp',
          ],
          ec_price: 16.0,
          ec_promo_price: 16.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03929',
          ec_rating: 3.0,
          ec_product_id: 'SP03929_00004',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03929_00004',
          permanentid: 'SP03929_00004',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Cymoon Bottle',
          ec_description:
            'This sleek and colorful sport water bottle is perfect for busy athletes and fitness buffs on the go. Its durable construction and leak-proof design make it a great choice for outdoor activities or everyday errands.',
          ec_shortdesc:
            'This sleek and colorful sport water bottle is perfect for busy athletes and fitness buffs on the go. Its durable construction and leak-proof design make it a great choice for outdoor activities or everyday errands.',
          ec_brand: 'NRS',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Cyan/c723422c685c_top_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Cyan/c723422c685c_top_left.webp',
          ],
          ec_price: 16.0,
          ec_promo_price: 16.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03929',
          ec_rating: 3.0,
          ec_product_id: 'SP03929_00006',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03929_00006',
          permanentid: 'SP03929_00006',
        },
      ],
      totalNumberOfChildren: 14,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Gray Bottle',
      ec_description:
        'This Gray sport water bottle is perfect for carrying your favorite drink with you wherever you go. It has a soft, plush material and a comfortable grip, making it easy to carry around.',
      ec_shortdesc:
        'This Gray sport water bottle is perfect for carrying your favorite drink with you wherever you go. It has a soft, plush material and a comfortable grip, making it easy to carry around.',
      ec_brand: 'Coast Guard and Co',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Water Bottles',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Gray/d38fffa9b1a9_bottom_right.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Gray/d38fffa9b1a9_bottom_right.webp',
      ],
      ec_price: 24.0,
      ec_promo_price: 24.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03928',
      ec_rating: 3.0,
      ec_product_id: 'SP03928_00010',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
      clickUri: 'https://sports.barca.group/pdp/SP03928_00010',
      permanentid: 'SP03928_00010',
      children: [
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Pamper Pink Bottle',
          ec_description:
            'This sport water bottle is sleek and colorful. It is perfect for carrying your favorite drink with you on your running or cycling excursions.',
          ec_shortdesc:
            'This sport water bottle is sleek and colorful. It is perfect for carrying your favorite drink with you on your running or cycling excursions.',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Pink/fffb2b055dd9_bottom_right.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Pink/fffb2b055dd9_bottom_right.webp',
          ],
          ec_price: 24.0,
          ec_promo_price: 24.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03928',
          ec_rating: 3.0,
          ec_product_id: 'SP03928_00013',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03928_00013',
          permanentid: 'SP03928_00013',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Pluvial Bottle',
          ec_description:
            "This sport water bottle is perfect for on-the-go drinking. It's made from durable plastic and includes a built-in drinking straw. The purple design is eye-catching and stylish, making it the perfect accessory for any sports activity.",
          ec_shortdesc:
            "This sport water bottle is perfect for on-the-go drinking. It's made from durable plastic and includes a built-in drinking straw. The purple design is eye-catching and stylish, making it the perfect accessory for any sports activity.",
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Purple/941569097cb1_bottom_right.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Purple/941569097cb1_bottom_right.webp',
          ],
          ec_price: 24.0,
          ec_promo_price: 24.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03928',
          ec_rating: 3.0,
          ec_product_id: 'SP03928_00014',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03928_00014',
          permanentid: 'SP03928_00014',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Citrus Fizz Bottle',
          ec_description:
            'This is a lime green sports water bottle that can hold up to 24 ounces of your favorite drink. It has a leak-proof and BPA free design, and is made from durable plastic that will keep your drinks cold for hours.',
          ec_shortdesc:
            'This is a lime green sports water bottle that can hold up to 24 ounces of your favorite drink. It has a leak-proof and BPA free design, and is made from durable plastic that will keep your drinks cold for hours.',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Lime/5cb69ae03283_bottom_right.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Lime/5cb69ae03283_bottom_right.webp',
          ],
          ec_price: 24.0,
          ec_promo_price: 24.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03928',
          ec_rating: 3.0,
          ec_product_id: 'SP03928_00005',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03928_00005',
          permanentid: 'SP03928_00005',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Eco-Gator Bottle',
          ec_description:
            'This is a green sport water bottle with a soft grip and clip. It is made of durable plastic and has a leak proof cap.',
          ec_shortdesc:
            'This is a green sport water bottle with a soft grip and clip. It is made of durable plastic and has a leak proof cap.',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Green/d613e04323bf_bottom_right.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Green/d613e04323bf_bottom_right.webp',
          ],
          ec_price: 24.0,
          ec_promo_price: 24.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03928',
          ec_rating: 3.0,
          ec_product_id: 'SP03928_00011',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03928_00011',
          permanentid: 'SP03928_00011',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Charger Blue Bottle',
          ec_description:
            'This is a blue sport water bottle with a built in filter and a soft silicone grip. It comes with a carrying case and is BPA free.',
          ec_shortdesc:
            'This is a blue sport water bottle with a built in filter and a soft silicone grip. It comes with a carrying case and is BPA free.',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Blue/4817b0af6822_bottom_right.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Blue/4817b0af6822_bottom_right.webp',
          ],
          ec_price: 24.0,
          ec_promo_price: 24.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03928',
          ec_rating: 3.0,
          ec_product_id: 'SP03928_00008',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03928_00008',
          permanentid: 'SP03928_00008',
        },
      ],
      totalNumberOfChildren: 14,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Gray Bottle',
      ec_description:
        'This Gray sport water bottle is perfect for carrying your favorite drink with you wherever you go. It has a soft, plush material and a comfortable grip, making it easy to carry around.',
      ec_shortdesc:
        'This Gray sport water bottle is perfect for carrying your favorite drink with you wherever you go. It has a soft, plush material and a comfortable grip, making it easy to carry around.',
      ec_brand: 'Coast Guard and Co',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Water Bottles',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Gray/d38fffa9b1a9_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Gray/d38fffa9b1a9_bottom_left.webp',
      ],
      ec_price: 20.0,
      ec_promo_price: 20.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03927',
      ec_rating: 5.0,
      ec_product_id: 'SP03927_00010',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
      clickUri: 'https://sports.barca.group/pdp/SP03927_00010',
      permanentid: 'SP03927_00010',
      children: [
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Racer Water Bottle',
          ec_description:
            'This is a red sport water bottle. It is made of sturdy plastic and has a screw-on lid. It is perfect for carrying your drink with you wherever you go!',
          ec_shortdesc:
            'This is a red sport water bottle. It is made of sturdy plastic and has a screw-on lid. It is perfect for carrying your drink with you wherever you go!',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Red/9f7477c22916_bottom_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Red/9f7477c22916_bottom_left.webp',
          ],
          ec_price: 20.0,
          ec_promo_price: 20.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03927',
          ec_rating: 5.0,
          ec_product_id: 'SP03927_00002',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03927_00002',
          permanentid: 'SP03927_00002',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Yellow Water Bottle',
          ec_description:
            'This Yellow sport water bottle is perfect for on-the-go hydration. The BPA free and toxin free design makes it a healthy choice for athletes and everyday drinkers alike.',
          ec_shortdesc:
            'This Yellow sport water bottle is perfect for on-the-go hydration. The BPA free and toxin free design makes it a healthy choice for athletes and everyday drinkers alike.',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Yellow/e1d26c9d6115_bottom_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Yellow/e1d26c9d6115_bottom_left.webp',
          ],
          ec_price: 20.0,
          ec_promo_price: 20.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03927',
          ec_rating: 5.0,
          ec_product_id: 'SP03927_00003',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03927_00003',
          permanentid: 'SP03927_00003',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Eco-Gator Bottle',
          ec_description:
            'This is a green sport water bottle with a soft grip and clip. It is made of durable plastic and has a leak proof cap.',
          ec_shortdesc:
            'This is a green sport water bottle with a soft grip and clip. It is made of durable plastic and has a leak proof cap.',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Green/d613e04323bf_bottom_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Green/d613e04323bf_bottom_left.webp',
          ],
          ec_price: 20.0,
          ec_promo_price: 20.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03927',
          ec_rating: 5.0,
          ec_product_id: 'SP03927_00011',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03927_00011',
          permanentid: 'SP03927_00011',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Cymoon Bottle',
          ec_description:
            'This sleek and colorful sport water bottle is perfect for busy athletes and fitness buffs on the go. Its durable construction and leak-proof design make it a great choice for outdoor activities or everyday errands.',
          ec_shortdesc:
            'This sleek and colorful sport water bottle is perfect for busy athletes and fitness buffs on the go. Its durable construction and leak-proof design make it a great choice for outdoor activities or everyday errands.',
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Cyan/c723422c685c_bottom_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Cyan/c723422c685c_bottom_left.webp',
          ],
          ec_price: 20.0,
          ec_promo_price: 20.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03927',
          ec_rating: 5.0,
          ec_product_id: 'SP03927_00006',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03927_00006',
          permanentid: 'SP03927_00006',
        },
        {
          resultType: 'childProduct',
          additionalFields: {
            source: 'Sports',
            cat_weight: null,
          },
          queryPinned: false,
          badgePlacements: [],
          ec_name: 'Pluvial Bottle',
          ec_description:
            "This sport water bottle is perfect for on-the-go drinking. It's made from durable plastic and includes a built-in drinking straw. The purple design is eye-catching and stylish, making it the perfect accessory for any sports activity.",
          ec_shortdesc:
            "This sport water bottle is perfect for on-the-go drinking. It's made from durable plastic and includes a built-in drinking straw. The purple design is eye-catching and stylish, making it the perfect accessory for any sports activity.",
          ec_brand: 'Coast Guard and Co',
          ec_category: [
            'Accessories',
            'Accessories|Surf Accessories',
            'Accessories|Surf Accessories|Water Bottles',
          ],
          ec_thumbnails: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Purple/941569097cb1_bottom_left.webp',
          ],
          ec_images: [
            'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Water%20Bottles/134_Purple/941569097cb1_bottom_left.webp',
          ],
          ec_price: 20.0,
          ec_promo_price: 20.0,
          ec_in_stock: true,
          ec_item_group_id: 'SP03927',
          ec_rating: 5.0,
          ec_product_id: 'SP03927_00014',
          ec_gender: null,
          ec_color: null,
          ec_listing: '/Accessories/Surf_Accessories/Water_Bottles',
          clickUri: 'https://sports.barca.group/pdp/SP03927_00014',
          permanentid: 'SP03927_00014',
        },
      ],
      totalNumberOfChildren: 14,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Surf Repairer Kit',
      ec_description:
        'A surf repair kit is a essential tool to have in your surf gear bag in case of a rip or tear. This kit includes a variety of patches, strings, and glue to help mend holes and fix boards.',
      ec_shortdesc:
        'A surf repair kit is a essential tool to have in your surf gear bag in case of a rip or tear. This kit includes a variety of patches, strings, and glue to help mend holes and fix boards.',
      ec_brand: 'Wax and More',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Surf Repair Kits',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Repair%20Kits/136/64e4d6cee8b2_top_left.jpg',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Repair%20Kits/136/64e4d6cee8b2_top_left.jpg',
      ],
      ec_price: 36.0,
      ec_promo_price: 36.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03947',
      ec_rating: 3.2,
      ec_product_id: 'SP03952_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Surf_Repair_Kits;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03952_00001',
      permanentid: 'SP03952_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Waxum Wax Package',
      ec_description:
        'This Both ski wax package contains two waxes; a hard wax and a soft wax. The hard wax is perfect for keeping your skis shiny and clean while the soft wax provides flexibility and comfort when applying the wax.',
      ec_shortdesc:
        'This Both ski wax package contains two waxes; a hard wax and a soft wax. The hard wax is perfect for keeping your skis shiny and clean while the soft wax provides flexibility and comfort when applying the wax.',
      ec_brand: 'Wax and More',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Surf Wax',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Wax/140_Both/5d2beb19c452_bottom_left.jpg',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Wax/140_Both/5d2beb19c452_bottom_left.jpg',
      ],
      ec_price: 27.0,
      ec_promo_price: 27.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03972',
      ec_rating: 3.0,
      ec_product_id: 'SP03972_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Surf_Wax;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03972_00001',
      permanentid: 'SP03972_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Waxique Epoxy Wax',
      ec_description:
        'The Epoxy Ski Wax Package contains a variety of waxes to help keep your skis in good condition. The waxes are easy to apply and will protect your skis from the snow and ice.',
      ec_shortdesc:
        'The Epoxy Ski Wax Package contains a variety of waxes to help keep your skis in good condition. The waxes are easy to apply and will protect your skis from the snow and ice.',
      ec_brand: 'Wax and More',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Surf Wax',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Wax/140_Epoxy/60a0ffb77280_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Wax/140_Epoxy/60a0ffb77280_bottom_left.webp',
      ],
      ec_price: 33.0,
      ec_promo_price: 33.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03973',
      ec_rating: 3.5,
      ec_product_id: 'SP03973_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Surf_Wax;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03973_00001',
      permanentid: 'SP03973_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Surf Repairer Kit',
      ec_description:
        'A surf repair kit is a essential tool to have in your surf gear bag in case of a rip or tear. This kit includes a variety of patches, strings, and glue to help mend holes and fix boards.',
      ec_shortdesc:
        'A surf repair kit is a essential tool to have in your surf gear bag in case of a rip or tear. This kit includes a variety of patches, strings, and glue to help mend holes and fix boards.',
      ec_brand: 'WaxIt',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Surf Repair Kits',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Repair%20Kits/136/64e4d6cee8b2_bottom_right.jpg',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Repair%20Kits/136/64e4d6cee8b2_bottom_right.jpg',
      ],
      ec_price: 32.0,
      ec_promo_price: 29.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03946',
      ec_rating: 4.1,
      ec_product_id: 'SP03951_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Surf_Repair_Kits;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03951_00001',
      permanentid: 'SP03951_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Locktron Padlock',
      ec_description:
        'A padlock is a type of lock used to secure objects using a padlock key.',
      ec_shortdesc:
        'A padlock is a type of lock used to secure objects using a padlock key.',
      ec_brand: 'Coronel',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Padlocks',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Padlocks/135/b6984907c09d_top_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Padlocks/135/b6984907c09d_top_left.webp',
      ],
      ec_price: 39.0,
      ec_promo_price: 36.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03923',
      ec_rating: 3.0,
      ec_product_id: 'SP03940_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Padlocks;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03940_00001',
      permanentid: 'SP03940_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Waxpack Combo',
      ec_description:
        'This ski wax package features a convenient application applicator, allowing you to quickly and easily wax your skis. The wax is made from a durable polyester fabric, which helps to resist water and snow buildup.',
      ec_shortdesc:
        'This ski wax package features a convenient application applicator, allowing you to quickly and easily wax your skis. The wax is made from a durable polyester fabric, which helps to resist water and snow buildup.',
      ec_brand: 'Wax and More',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Surf Wax',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Wax/140_Polyester/c3315d775d52_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Wax/140_Polyester/c3315d775d52_bottom_left.webp',
      ],
      ec_price: 39.0,
      ec_promo_price: 36.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03963',
      ec_rating: 3.0,
      ec_product_id: 'SP03963_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Surf_Wax;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03963_00001',
      permanentid: 'SP03963_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Locktron Padlock',
      ec_description:
        'A padlock is a type of lock used to secure objects using a padlock key.',
      ec_shortdesc:
        'A padlock is a type of lock used to secure objects using a padlock key.',
      ec_brand: 'Lockit',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Padlocks',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Padlocks/135/b6984907c09d_bottom_right.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Padlocks/135/b6984907c09d_bottom_right.webp',
      ],
      ec_price: 39.0,
      ec_promo_price: 39.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03924',
      ec_rating: 4.8,
      ec_product_id: 'SP03939_00002',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Padlocks;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03939_00002',
      permanentid: 'SP03939_00002',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Surf Repairer Kit',
      ec_description:
        'A surf repair kit is a essential tool to have in your surf gear bag in case of a rip or tear. This kit includes a variety of patches, strings, and glue to help mend holes and fix boards.',
      ec_shortdesc:
        'A surf repair kit is a essential tool to have in your surf gear bag in case of a rip or tear. This kit includes a variety of patches, strings, and glue to help mend holes and fix boards.',
      ec_brand: 'Surf and Co',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Surf Repair Kits',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Repair%20Kits/136/64e4d6cee8b2_bottom_left.jpg',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Surf%20Repair%20Kits/136/64e4d6cee8b2_bottom_left.jpg',
      ],
      ec_price: 28.0,
      ec_promo_price: 28.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03945',
      ec_rating: 3.0,
      ec_product_id: 'SP03950_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Surf_Repair_Kits;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03950_00001',
      permanentid: 'SP03950_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
    {
      resultType: 'product',
      additionalFields: {
        source: 'Sports',
        cat_weight: null,
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Locktron Padlock',
      ec_description:
        'A padlock is a type of lock used to secure objects using a padlock key.',
      ec_shortdesc:
        'A padlock is a type of lock used to secure objects using a padlock key.',
      ec_brand: 'Paddy',
      ec_category: [
        'Accessories',
        'Accessories|Surf Accessories',
        'Accessories|Surf Accessories|Padlocks',
      ],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Padlocks/135/b6984907c09d_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Accessories/Surf%20Accessories/Padlocks/135/b6984907c09d_bottom_left.webp',
      ],
      ec_price: 42.0,
      ec_promo_price: 38.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP03922',
      ec_rating: 4.4,
      ec_product_id: 'SP03939_00001',
      ec_gender: null,
      ec_color: null,
      ec_listing:
        '/Accessories/Surf_Accessories/Padlocks;/Promotions/Surf_With_Us_This_Year',
      clickUri: 'https://sports.barca.group/pdp/SP03939_00001',
      permanentid: 'SP03939_00001',
      children: [],
      totalNumberOfChildren: 1,
    },
  ],
  results: [],
  facets: [
    {
      type: 'regular',
      facetId: 'ec_brand',
      field: 'ec_brand',
      displayName: 'Brand',
      values: [
        {
          state: 'idle',
          numberOfResults: 27,
          value: 'Coast Guard and Co',
        },
        {
          state: 'idle',
          numberOfResults: 1,
          value: 'Aqua Marina',
        },
        {
          state: 'idle',
          numberOfResults: 14,
          value: 'NRS',
        },
        {
          state: 'idle',
          numberOfResults: 4,
          value: 'Wax and More',
        },
        {
          state: 'idle',
          numberOfResults: 1,
          value: 'WaxIt',
        },
        {
          state: 'idle',
          numberOfResults: 1,
          value: 'Coronel',
        },
        {
          state: 'idle',
          numberOfResults: 1,
          value: 'Lockit',
        },
        {
          state: 'idle',
          numberOfResults: 1,
          value: 'Surf and Co',
        },
      ],
      numberOfValues: 8,
      moreValuesAvailable: true,
      fromAutoSelect: false,
      isFieldExpanded: false,
    },
    {
      type: 'numericalRange',
      facetId: 'ec_price',
      field: 'ec_price',
      displayName: 'Price',
      values: [
        {
          state: 'idle',
          numberOfResults: 52,
          start: 16,
          end: 1006,
          endInclusive: true,
        },
      ],
      numberOfValues: 8,
      moreValuesAvailable: false,
      fromAutoSelect: false,
      domain: {
        min: 16,
        max: 1006,
        increment: 0,
      },
      interval: 'continuous',
      isFieldExpanded: false,
    },
    {
      type: 'hierarchical',
      facetId: 'ec_category',
      field: 'ec_category',
      displayName: 'Category',
      values: [
        {
          state: 'idle',
          numberOfResults: 51,
          value: 'Accessories',
          path: ['Accessories'],
          isLeafValue: false,
          children: [],
        },
        {
          state: 'idle',
          numberOfResults: 1,
          value: 'Games & Toys',
          path: ['Games & Toys'],
          isLeafValue: false,
          children: [],
        },
      ],
      numberOfValues: 5,
      delimitingCharacter: '|',
      moreValuesAvailable: false,
      fromAutoSelect: false,
      isFieldExpanded: false,
    },
    {
      type: 'dateRange',
      facetId: 'cat_date_added',
      field: 'cat_date_added',
      displayName: 'Date',
      values: [
        {
          state: 'idle',
          numberOfResults: 2,
          start: '2021/01/01@00:00:00',
          end: '2021/12/31@23:59:59',
          endInclusive: false,
        },
        {
          state: 'idle',
          numberOfResults: 3,
          start: '2022/01/01@00:00:00',
          end: '2022/12/31@23:59:59',
          endInclusive: false,
        },
        {
          state: 'idle',
          numberOfResults: 5,
          start: '2023/01/01@00:00:00',
          end: '2023/12/31@23:59:59',
          endInclusive: false,
        },
        {
          state: 'idle',
          numberOfResults: 3,
          start: '2024/01/01@00:00:00',
          end: '2024/12/31@23:59:59',
          endInclusive: false,
        },
        {
          state: 'idle',
          numberOfResults: 0,
          start: '2025/01/01@00:00:00',
          end: '2025/12/31@23:59:59',
          endInclusive: false,
        },
      ],
      numberOfValues: 8,
      moreValuesAvailable: false,
      fromAutoSelect: false,
      isFieldExpanded: false,
    },
    {
      type: 'regular',
      facetId: 'cat_color',
      field: 'cat_color',
      displayName: 'Color',
      values: [
        {
          state: 'idle',
          numberOfResults: 4,
          value: 'Blue',
        },
        {
          state: 'idle',
          numberOfResults: 3,
          value: 'White',
        },
        {
          state: 'idle',
          numberOfResults: 3,
          value: 'Gray',
        },
        {
          state: 'idle',
          numberOfResults: 3,
          value: 'Pink',
        },
        {
          state: 'idle',
          numberOfResults: 3,
          value: 'Purple',
        },
        {
          state: 'idle',
          numberOfResults: 3,
          value: 'Red',
        },
        {
          state: 'idle',
          numberOfResults: 3,
          value: 'Lime',
        },
        {
          state: 'idle',
          numberOfResults: 3,
          value: 'Khaki',
        },
      ],
      numberOfValues: 8,
      moreValuesAvailable: true,
      fromAutoSelect: false,
      isFieldExpanded: false,
    },
  ],
  pagination: {
    page: 0,
    perPage: 24,
    totalEntries: 13,
    totalPages: 1,
  },
  sort: {
    appliedSort: {
      sortCriteria: 'relevance',
    },
    availableSorts: [
      {
        sortCriteria: 'relevance',
      },
      {
        sortCriteria: 'fields',
        fields: [
          {
            field: 'ec_price',
            direction: 'asc',
            displayName: 'Price (Low to High)',
          },
        ],
      },
      {
        sortCriteria: 'fields',
        fields: [
          {
            field: 'ec_price',
            direction: 'desc',
            displayName: 'Price (High to Low)',
          },
        ],
      },
    ],
  },
  executionReport: null,
  triggers: [],
};
