export const baseResponse = {
  responseId: '123e4567-e89b-12d3-a456-426614174001',
  headline: 'Recommended for you',
  products: [
    {
      permanentid: 'rec-product-1',
      ec_name: 'Recommended Product 1',
      ec_price: 79.99,
      clickUri: 'https://example.com/product/rec-1',
      ec_brand: 'Rec Brand',
      ec_category: 'Accessories',
    },
    {
      permanentid: 'rec-product-2',
      ec_name: 'Recommended Product 2',
      ec_price: 129.99,
      clickUri: 'https://example.com/product/rec-2',
      ec_brand: 'Rec Brand',
      ec_category: 'Accessories',
    },
  ],
  pagination: {
    page: 0,
    perPage: 10,
    totalEntries: 2,
    totalPages: 1,
  },
  triggers: [],
};

export const richResponse = {
  responseId: '62f1cf88-8457-48cf-880d-845e8ef3ade6',
  headline: 'Customers often buy',
  products: [
    {
      resultType: 'product',
      additionalFields: {
        cat_available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Chino khakis',
      ec_description:
        'The Khaki Acrylic pants for a Men provide a relaxed and comfortable fit. They are made from 100% acrylic and are machine-washable.',
      ec_shortdesc:
        'The Khaki Acrylic pants for a Men provide a relaxed and comfortable fit. They are made from 100% acrylic and are machine-washable.',
      ec_brand: 'Tommy Hilfiger',
      ec_category: ['Clothing', 'Clothing|Pants'],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Men_Khaki_Acrylic/482f8c7ac87c_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Men_Khaki_Acrylic/482f8c7ac87c_bottom_left.webp',
      ],
      ec_price: 154.0,
      ec_promo_price: 154.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP04946',
      ec_rating: 4.2,
      ec_product_id: 'SP04946_00006',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Clothing/Pants',
      clickUri: 'https://sports.barca.group/pdp/SP04946_00006',
      permanentid: 'SP04946_00006',
      children: [],
      totalNumberOfChildren: 0,
    },
    {
      resultType: 'product',
      additionalFields: {
        cat_available_sizes: [
          '4',
          '4.5',
          '5',
          '6',
          '6.5',
          '7',
          '7.5',
          '8',
          '9',
          '9.5',
          '10',
          '10.5',
        ],
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Slippery',
      ec_description:
        'This Blue slipper is made of PET and is perfect for keeping your feet warm.',
      ec_shortdesc:
        'This Blue slipper is made of PET and is perfect for keeping your feet warm.',
      ec_brand: 'Ecco',
      ec_category: ['Sandals & Shoes', 'Sandals & Shoes|Slippers'],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Sandals%20%26%20Shoes/Slippers/50_Blue_PET/2b866f65284b_top_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Sandals%20%26%20Shoes/Slippers/50_Blue_PET/2b866f65284b_top_left.webp',
      ],
      ec_price: 80.0,
      ec_promo_price: 80.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP04884',
      ec_rating: 5.0,
      ec_product_id: 'SP04884_00002',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Sandals_Shoes/Slippers',
      clickUri: 'https://sports.barca.group/pdp/SP04884_00002',
      permanentid: 'SP04884_00002',
      children: [],
      totalNumberOfChildren: 0,
    },
    {
      resultType: 'product',
      additionalFields: {
        cat_available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Stealth Blue',
      ec_description:
        'This blue elastane pants for men is designed to provide stretchy comfort, while keeping your look stylish.',
      ec_shortdesc:
        'This blue elastane pants for men is designed to provide stretchy comfort, while keeping your look stylish.',
      ec_brand: 'Nautica',
      ec_category: ['Clothing', 'Clothing|Pants'],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Men_Blue_Elastane/e86c0a474226_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Men_Blue_Elastane/e86c0a474226_bottom_left.webp',
      ],
      ec_price: 140.0,
      ec_promo_price: 140.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP04951',
      ec_rating: 4.6,
      ec_product_id: 'SP04951_00002',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Clothing/Pants',
      clickUri: 'https://sports.barca.group/pdp/SP04951_00002',
      permanentid: 'SP04951_00002',
      children: [],
      totalNumberOfChildren: 0,
    },
    {
      resultType: 'product',
      additionalFields: {
        cat_available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Pantaloon',
      ec_description:
        'A high-quality, comfortable pair of pink elastane pants that are perfect for a woman. They are made from a stretchy and durable material, which means they will stay in place no matter what you do.',
      ec_shortdesc:
        'A high-quality, comfortable pair of pink elastane pants that are perfect for a woman. They are made from a stretchy and durable material, which means they will stay in place no matter what you do.',
      ec_brand: 'Adidas',
      ec_category: ['Clothing', 'Clothing|Pants'],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Women_Pink_Elastane/35ad2207b8e3_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Women_Pink_Elastane/35ad2207b8e3_bottom_left.webp',
      ],
      ec_price: 98.0,
      ec_promo_price: 98.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP04971',
      ec_rating: 4.7,
      ec_product_id: 'SP04971_00007',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Clothing/Pants',
      clickUri: 'https://sports.barca.group/pdp/SP04971_00007',
      permanentid: 'SP04971_00007',
      children: [],
      totalNumberOfChildren: 0,
    },
    {
      resultType: 'product',
      additionalFields: {
        cat_available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Plumbum',
      ec_description:
        'Looking for a comfortable and stylish pant? Look no further than these Purple Cotton pants. Made from 100% cotton, these pants are perfect for everyday wear. They are also machine-washable and have a comfortable fit.',
      ec_shortdesc:
        'Looking for a comfortable and stylish pant? Look no further than these Purple Cotton pants. Made from 100% cotton, these pants are perfect for everyday wear. They are also machine-washable and have a comfortable fit.',
      ec_brand: 'Calvin Klein',
      ec_category: ['Clothing', 'Clothing|Pants'],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Women_Purple_Cotton/fc329136be16_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Women_Purple_Cotton/fc329136be16_bottom_left.webp',
      ],
      ec_price: 98.0,
      ec_promo_price: 89.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP04969',
      ec_rating: 3.7,
      ec_product_id: 'SP04969_00008',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Clothing/Pants',
      clickUri: 'https://sports.barca.group/pdp/SP04969_00008',
      permanentid: 'SP04969_00008',
      children: [],
      totalNumberOfChildren: 0,
    },
    {
      resultType: 'product',
      additionalFields: {
        cat_available_sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      },
      queryPinned: false,
      badgePlacements: [],
      ec_name: 'Pinkspin',
      ec_description:
        'This is a pink cotton pants for women. It has a fit that is comfortable and stylish.',
      ec_shortdesc:
        'This is a pink cotton pants for women. It has a fit that is comfortable and stylish.',
      ec_brand: 'Calvin Klein',
      ec_category: ['Clothing', 'Clothing|Pants'],
      ec_thumbnails: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Women_Pink_Cotton/c7485c8577b3_bottom_left.webp',
      ],
      ec_images: [
        'https://images.barca.group/Sports/mj/Clothing/Pants/67_Women_Pink_Cotton/c7485c8577b3_bottom_left.webp',
      ],
      ec_price: 98.0,
      ec_promo_price: 89.0,
      ec_in_stock: true,
      ec_item_group_id: 'SP04969',
      ec_rating: 3.7,
      ec_product_id: 'SP04969_00007',
      ec_gender: null,
      ec_color: null,
      ec_listing: '/Clothing/Pants',
      clickUri: 'https://sports.barca.group/pdp/SP04969_00007',
      permanentid: 'SP04969_00007',
      children: [],
      totalNumberOfChildren: 0,
    },
  ],
  pagination: {
    page: 0,
    perPage: 6,
    totalEntries: 3718,
    totalPages: 620,
  },
  executionReport: {
    duration: 5,
    children: [
      {
        name: 'RequestId',
        description: 'The id correlating logs for this request',
        duration: 0,
        'X-Request-ID': 'c699278a-2b93-4c96-bb61-05124e1bde76',
      },
      {
        name: 'Organization ID',
        description: 'Organization ID',
        duration: 0,
        coveo_organization: 'searchuisamples',
      },
      {
        name: 'PerformAuthentication',
        description: 'Perform authentication',
        duration: 0,
        configured: {
          primary: 'CloudToken',
        },
        result: {
          userIds: [
            {
              name: 'anonymous_user@anonymous.coveo.com',
              kind: 'User',
              provider: 'Email Security Provider',
              infos: {},
            },
          ],
          roles: [
            'executeSearchAsOtherUser',
            'searchTokenCreator',
            'queryExecutor',
            'viewAllContent',
            'superUserTokenUser',
          ],
          queryRestrictions: {},
          userGroups: [],
        },
        children: [
          {
            name: 'ResolveProviderAuthentication',
            description: 'Resolve authentication of provider: CloudToken',
            duration: 0,
            result: {
              userIds: [
                {
                  name: 'anonymous_user@anonymous.coveo.com',
                  kind: 'User',
                  provider: 'Email Security Provider',
                  infos: {},
                },
              ],
              roles: [
                'executeSearchAsOtherUser',
                'searchTokenCreator',
                'queryExecutor',
                'viewAllContent',
                'superUserTokenUser',
              ],
              queryRestrictions: {},
              userGroups: [],
            },
          },
        ],
      },
      {
        name: 'PerformAuthentication',
        description: 'Perform authentication',
        duration: 0,
        configured: {
          secondary: [],
          mandatory: [],
        },
        result: {
          userIds: [
            {
              name: 'anonymous_user@anonymous.coveo.com',
              kind: 'User',
              provider: 'Email Security Provider',
              infos: {},
            },
          ],
          roles: [
            'executeSearchAsOtherUser',
            'searchTokenCreator',
            'queryExecutor',
            'viewAllContent',
            'superUserTokenUser',
          ],
          queryRestrictions: {},
          userGroups: [],
        },
        children: [
          {
            name: 'MergeAuthentications',
            description: 'Merge authentications (if needed)',
            duration: 0,
            result: {
              userIds: [
                {
                  name: 'anonymous_user@anonymous.coveo.com',
                  kind: 'User',
                  provider: 'Email Security Provider',
                  infos: {},
                },
              ],
              roles: [
                'executeSearchAsOtherUser',
                'searchTokenCreator',
                'queryExecutor',
                'viewAllContent',
                'superUserTokenUser',
              ],
              queryRestrictions: {},
              userGroups: [],
            },
          },
        ],
      },
      {
        name: 'ResolveContext',
        description: 'Resolve context',
        duration: 0,
        result: {
          userAgent: {
            raw: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
            browser: ['chrome'],
            device: ['desktop', 'pc', 'mac', 'osx'],
            os: ['osx', 'mac'],
          },
          searchHub: 'Recommendations - sports-ui-samples',
          tab: 'https://sports.barca.group',
          referrer: null,
          locale: 'en',
          context: {
            'commerce-api': 'Recommendations',
            trackingId: 'sports-ui-samples',
            'commerce-slot-id': 'af4fb7ba-6641-4b67-9cf9-be67e9f30174',
            'commerce-slot': 'Popular bought',
          },
          expressions: {
            q: {
              original: '',
              parsed: null,
            },
            aq: {
              original: '',
              parsed: null,
            },
            cq: {
              original: '@source=="Sports"',
              parsed: '@source=="Sports"',
            },
            dq: {
              original: '',
              parsed: null,
            },
            lq: {
              original: '',
              parsed: null,
            },
          },
          enableDuplicateFiltering: false,
          filterField: null,
          filterFieldRange: 5,
          parentField: null,
          childField: null,
          recommendation: 'popular_bought',
          lowercaseOperators: false,
          sortCriteria: ['relevancy'],
        },
      },
      {
        name: 'ResolvePipeline',
        description: 'Resolve pipeline',
        duration: 0,
        result: {
          pipeline: 'cmh-search-recs',
          pipelineId: 'a71493dc-d23f-4c76-b961-c972dd6b9bf4',
          pipelineHash: '19d39bc2c68ccc328adadfd6090ccb97',
          splitTest: null,
          statementGroups: [],
        },
      },
      {
        name: 'ResolveContext',
        description: 'Resolve context',
        duration: 0,
        result: {
          userAgent: {
            raw: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
            browser: ['chrome'],
            device: ['desktop', 'pc', 'mac', 'osx'],
            os: ['osx', 'mac'],
          },
          searchHub: 'Recommendations - sports-ui-samples',
          tab: 'https://sports.barca.group',
          referrer: null,
          locale: 'en',
          context: {
            'commerce-api': 'Recommendations',
            trackingId: 'sports-ui-samples',
            'commerce-slot-id': 'af4fb7ba-6641-4b67-9cf9-be67e9f30174',
            'commerce-slot': 'Popular bought',
          },
          expressions: {
            q: {
              original: '',
              parsed: null,
            },
            aq: {
              original: '',
              parsed: null,
            },
            cq: {
              original: '@source=="Sports"',
              parsed: '@source=="Sports"',
            },
            dq: {
              original: '',
              parsed: null,
            },
            lq: {
              original: '',
              parsed: null,
            },
          },
          enableDuplicateFiltering: false,
          filterField: null,
          filterFieldRange: 5,
          parentField: null,
          childField: null,
          recommendation: 'popular_bought',
          lowercaseOperators: false,
          sortCriteria: ['relevancy'],
        },
      },
      {
        name: 'ApplyQueryParamOverrideFeature',
        description: "Apply 'queryParamOverride' rules",
        duration: 0,
        applied: [
          'when $context[commerce-slot] is "No recommendations" then override query {"cq": "permanentid==this_permanent_id_does_not_exist"}',
          'when $context[commerce-slot] is "Error" then override query {"numberOfResults": -1}',
        ],
      },
      {
        name: 'ResolveContext',
        description: 'Resolve context',
        duration: 0,
        result: {
          userAgent: {
            raw: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36',
            browser: ['chrome'],
            device: ['desktop', 'pc', 'mac', 'osx'],
            os: ['osx', 'mac'],
          },
          searchHub: 'Recommendations - sports-ui-samples',
          tab: 'https://sports.barca.group',
          referrer: null,
          locale: 'en',
          context: {
            'commerce-api': 'Recommendations',
            trackingId: 'sports-ui-samples',
            'commerce-slot-id': 'af4fb7ba-6641-4b67-9cf9-be67e9f30174',
            'commerce-slot': 'Popular bought',
          },
          expressions: {
            q: {
              original: '',
              parsed: null,
            },
            aq: {
              original: '',
              parsed: null,
            },
            cq: {
              original: '@source=="Sports"',
              parsed: '@source=="Sports"',
            },
            dq: {
              original: '',
              parsed: null,
            },
            lq: {
              original: '',
              parsed: null,
            },
          },
          enableDuplicateFiltering: false,
          filterField: null,
          filterFieldRange: 5,
          parentField: null,
          childField: null,
          recommendation: 'popular_bought',
          lowercaseOperators: false,
          sortCriteria: ['relevancy'],
        },
      },
      {
        name: 'PreprocessQueryExpression',
        description: 'Preprocess query expression',
        duration: 0,
        result: {
          type: 'cq',
          in: '@source=="Sports"',
          out: '@source=="Sports"',
        },
        children: [
          {
            name: 'ApplyThesaurusFeature',
            description: "Apply 'thesaurus' rules",
            duration: 0,
            applied: [],
          },
          {
            name: 'ApplyStopWordFeature',
            description: "Apply 'stop' rules",
            duration: 0,
            applied: [],
          },
        ],
      },
      {
        name: 'QueryExtension',
        description: 'Find and execute query extensions',
        duration: 0,
      },
      {
        name: 'PreprocessQuery',
        description: 'Preprocess query',
        duration: 0,
        result: {
          in: {
            q: null,
            aq: null,
            lq: null,
            cq: '@source==Sports',
            dq: null,
            mq: null,
            parentField: null,
            childField: null,
            filterField: null,
            filterFieldRange: 5,
            enableDuplicateFiltering: false,
            numberOfResults: 6,
            queryFunctions: [],
            rankingFunctions: [],
            sortCriteria: ['relevancy'],
            rankingExpressions: [],
            rankingOverrides: [],
          },
          out: {
            q: null,
            aq: null,
            lq: null,
            cq: '@source==Sports',
            dq: null,
            mq: null,
            parentField: null,
            childField: null,
            filterField: null,
            filterFieldRange: 5,
            enableDuplicateFiltering: false,
            numberOfResults: 6,
            queryFunctions: [],
            rankingFunctions: [],
            sortCriteria: ['relevancy'],
            rankingExpressions: [],
            rankingOverrides: [],
          },
        },
        children: [
          {
            name: 'ApplyFilterFeature',
            description: "Apply 'filter' rules",
            duration: 0,
            applied: [],
          },
          {
            name: 'ApplyRankingWeightFeature',
            description: "Apply 'rankingweight' rules",
            duration: 0,
            applied: [],
          },
        ],
      },
      {
        name: 'BuildFacetSelectedValueOverride',
        description:
          'Build query overrides based on selected facet selected values',
        duration: 0,
        selectedFacets: [],
        createdOverrides: [],
      },
      {
        name: 'AddExistingQueryParametersToGroupByOverride',
        description:
          'Add query overrides in the query to each Group By results',
        duration: 0,
        queryExpressions: {
          cq: '@source==Sports',
        },
        overridesFromExpressions: [],
      },
      {
        name: 'PipelineResolveTriggers',
        description: 'Resolve triggers',
        duration: 0,
        children: [
          {
            name: 'ApplyTriggerFeature',
            description: "Apply 'trigger' rules",
            duration: 0,
            applied: [],
          },
        ],
      },
      {
        name: 'IndexOperationV8',
        description: 'Send query to index',
        duration: 1,
        result: {
          in: {
            LogicalIndex: 'default',
            BasicExpression: '@uri',
            AdvancedExpression:
              '@uri @objecttype==Product [[@ec_productid] @objecttype==Variant]',
            ConstantExpression:
              '@source==Sports @objecttype==Product [[@ec_productid] @objecttype==Variant @source==Sports]',
            FirstResult: 0,
            NumberOfResults: 6,
            SortBy: 'Relevancy',
            SortByFields: [],
            CustomFilterRange: 5,
            ExcerptLength: 200,
            SummaryLength: 0,
            EnableWildcards: false,
            EnableQuestionMark: false,
            EnableDidYouMean: false,
            DisableLogging: false,
            EnableDuplicateFiltering: false,
            ExtractFirstSentences: false,
            EnableRankingInformation: false,
            EnableQueryProfiling: false,
            TimeOut: 10,
            EnableMetatermSyntax: false,
            BackgroundQuery: false,
            RankingExpressions: [],
            RankingFunctions: [],
            QueryFunctions: [],
            RankingOverrides: [],
            Facets: [],
            AutomaticFacetsRequest: {},
          },
          out: {
            index: 'cache',
            logEntryId: '212630626172172340',
            serverTime: 6,
            requestTime: 1,
            totalCount: 3718,
            totalCountFiltered: 3718,
            groupByCount: 0,
          },
        },
      },
      {
        name: 'FacetResultPostProcessingEvaluationReport',
        description: 'Post process the result through the processors pipeline',
        duration: 1,
        'Index Scores': [],
        children: [
          {
            name: 'FacetSense ML score assigning',
            description:
              'Processing facet result: FacetSense ML score assigning',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Setting more values available',
            description:
              'Processing facet result: Setting more values available',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Apply selection from request',
            description:
              'Processing facet result: Apply selection from request',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Adding optional facet IDs',
            description: 'Processing facet result: Adding optional facet IDs',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Freezing facet values if any',
            description:
              'Processing facet result: Freezing facet values if any',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Reordering values based on facet sense',
            description:
              'Processing facet result: Reordering values based on facet sense',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Retaining selected values based on request',
            description:
              'Processing facet result: Retaining selected values based on request',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Reorder facet range values based on sort criteria',
            description:
              'Processing facet result: Reorder facet range values based on sort criteria',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Reorder facet values using custom sort',
            description:
              'Processing facet result: Reorder facet values using custom sort',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Reorder facet values pushing selected values on top',
            description:
              'Processing facet result: Reorder facet values pushing selected values on top',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Truncate extra values in request',
            description:
              'Processing facet result: Truncate extra values in request',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Reorder facets using index score',
            description:
              'Processing facet result: Reorder facets using index score',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
          {
            name: 'Reorder facets using ML score',
            description:
              'Processing facet result: Reorder facets using ML score',
            duration: 0,
            changed: false,
            in: [],
            out: [],
          },
        ],
      },
    ],
  },
  triggers: [],
};
