apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shopify
  title: '@coveo/shopify'
  description: Utilities to integrate Shopify with Coveo's commerce engine
spec:
  type: library
  lifecycle: production
  owner: group:default/commerce-shopify
  system: ui-kit
  dependsOn:
    - component:default/headless
