name: Functional test
description: Running functional tests for Relay

inputs:
  analytics_key:
    description: "Analytics logging key for functional tests"
    required: true

runs:
  using: composite
  steps:
    - name: Run functional test
      shell: bash
      run: pnpm exec env && pnpm functional-test
      env:
        VITE_ANALYTICS_KEY: ${{ inputs.analytics_key }} # must start with VITE_ or vitest will block
