apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: atomic
  title: '@coveo/atomic'
  description: A web-component library for building modern UIs interfacing with the Coveo platform
spec:
  type: library
  lifecycle: production
  owner: group:default/dxui
  system: ui-kit
  dependsOn:
    - component:default/bueno
    - component:default/headless
