name: 'Setup Quantic E2E'
description: 'Setup Playwright tests for Quantic'
inputs:
  clientid:
    description: The SFDX client ID
    required: true
  jwtkey:
    description: The SFDX JWT key contents
    required: true
  lws-status:
    description: 'Set to "enabled" to deploy the LWS enabled community, and "disabled to deploy the LWS disabled community'
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo "${{ inputs.jwtkey }}" > server.key
        pnpm exec ts-node scripts/build/deploy-community.ts --ci --scratch-org-def-path=./config/lws-${{ inputs.lws-status }}-scratch-def.json
        rm server.key
      shell: bash
      working-directory: ./packages/quantic
      env:
        COMMIT_SHA: ${{ github.sha }}
        SFDX_AUTH_CLIENT_ID: ${{ inputs.clientid }}
        SFDX_AUTH_JWT_KEY_FILE: server.key
        SFDX_AUTH_JWT_USERNAME: rdaccess@coveo.com
        SFDX_AUTH_JWT_INSTANCE_URL: https://login.salesforce.com
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: quantic-playwright-env-lws-${{ inputs.lws-status }}
        path: packages/quantic/.env
        include-hidden-files: true
        retention-days: 1
        if-no-files-found: error
