/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ItemDisplayBasicLayout, ItemDisplayDensity, ItemDisplayImageSize } from "./components/common/layout/display-options";
import { ItemRenderingFunction } from "./components/common/item-list/stencil-item-list-common";
import { Actions, InsightResultActionClickedEvent } from "./components/insight/atomic-insight-result-action/atomic-insight-result-action";
import { InsightResultAttachToCaseEvent } from "./components/insight/atomic-insight-result-attach-to-case-action/atomic-insight-result-attach-to-case-action";
import { DateFilterRange, DateRangeRequest, ResultTemplate, ResultTemplateCondition } from "@coveo/headless";
import { RangeFacetSortCriterion as InsightRangeFacetSortCriterion, UserAction as IUserAction } from "@coveo/headless/insight";
import { AnyBindings } from "./components/common/interface/bindings";
import { i18n } from "i18next";
import { SearchBoxSuggestionElement } from "./components/common/suggestions/suggestions-types";
export { ItemDisplayBasicLayout, ItemDisplayDensity, ItemDisplayImageSize } from "./components/common/layout/display-options";
export { ItemRenderingFunction } from "./components/common/item-list/stencil-item-list-common";
export { Actions, InsightResultActionClickedEvent } from "./components/insight/atomic-insight-result-action/atomic-insight-result-action";
export { InsightResultAttachToCaseEvent } from "./components/insight/atomic-insight-result-attach-to-case-action/atomic-insight-result-attach-to-case-action";
export { DateFilterRange, DateRangeRequest, ResultTemplate, ResultTemplateCondition } from "@coveo/headless";
export { RangeFacetSortCriterion as InsightRangeFacetSortCriterion, UserAction as IUserAction } from "@coveo/headless/insight";
export { AnyBindings } from "./components/common/interface/bindings";
export { i18n } from "i18next";
export { SearchBoxSuggestionElement } from "./components/common/suggestions/suggestions-types";
export namespace Components {
    interface AtomicInsightFoldedResultList {
        /**
          * The name of the field that uniquely identifies a result within a collection.
          * @defaultValue `foldingchild`
         */
        "childField"?: string;
        /**
          * The name of the field on which to do the folding. The folded result list component will use the values of this field to resolve the collections of result items.
          * @defaultValue `foldingcollection`
         */
        "collectionField"?: string;
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density": ItemDisplayDensity;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize": ItemDisplayImageSize;
        /**
          * The name of the field that determines whether a certain result is a top result containing other child results within a collection.
          * @defaultValue `foldingparent`
         */
        "parentField"?: string;
        /**
          * Sets a rendering function to bypass the standard HTML template mechanism for rendering results. You can use this function while working with web frameworks that don't use plain HTML syntax such as React, Angular, or Vue.  Do not use this method if you integrate Atomic in a plain HTML deployment.
         */
        "setRenderFunction": (resultRenderingFunction: ItemRenderingFunction) => Promise<void>;
    }
    interface AtomicInsightResultAction {
        /**
          * The type of action to perform when the result action is clicked. This will be sent along the event fired when the button is clicked.
         */
        "action": Actions | string;
        /**
          * Specify the result action icon to display.
         */
        "icon": string;
        /**
          * The text tooltip to show on the result action icon.
         */
        "tooltip": string;
        /**
          * The text tooltip to show on the result action icon for some time after clicking the button.
         */
        "tooltipOnClick": string;
    }
    interface AtomicInsightResultActionBar {
    }
    interface AtomicInsightResultAttachToCaseAction {
    }
    interface AtomicInsightResultAttachToCaseIndicator {
    }
    interface AtomicInsightResultChildrenTemplate {
        /**
          * A function that must return true on results for the result template to apply. Set programmatically before initialization, not via attribute.  For example, the following targets a template and sets a condition to make it apply only to results whose `title` contains `singapore`: `document.querySelector('#target-template').conditions = [(result) => /singapore/i.test(result.title)];`
         */
        "conditions": ResultTemplateCondition[];
        /**
          * Gets the appropriate result template based on conditions applied.
         */
        "getTemplate": () => Promise<ResultTemplate<DocumentFragment> | null>;
        /**
          * The field that, when defined on a result item, would allow the template to be applied.  For example, a template with the following attribute only applies to result items whose `filetype` and `sourcetype` fields are defined: `if-defined="filetype,sourcetype"`
         */
        "ifDefined"?: string;
        /**
          * The field that, when defined on a result item, would prevent the template from being applied.  For example, a template with the following attribute only applies to result items whose `filetype` and `sourcetype` fields are NOT defined: `if-not-defined="filetype,sourcetype"`
         */
        "ifNotDefined"?: string;
        /**
          * The field and values that define which result items the condition must be applied to.  For example, a template with the following attribute only applies to result items whose `filetype` is `lithiummessage` or `YouTubePlaylist`: `must-match-filetype="lithiummessage,YouTubePlaylist"`
         */
        "mustMatch": Record<
    string,
    string[]
  >;
        /**
          * The field and values that define which result items the condition must not be applied to.  For example, a template with the following attribute only applies to result items whose `filetype` is not `lithiummessage`: `must-not-match-filetype="lithiummessage"`
         */
        "mustNotMatch": Record<
    string,
    string[]
  >;
    }
    interface AtomicInsightResultList {
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density": ItemDisplayDensity;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize": ItemDisplayImageSize;
        /**
          * Sets a rendering function to bypass the standard HTML template mechanism for rendering results. You can use this function while working with web frameworks that don't use plain HTML syntax such as React, Angular, or Vue.  Do not use this method if you integrate Atomic in a plain HTML deployment.
          * @param resultRenderingFunction
         */
        "setRenderFunction": (resultRenderingFunction: ItemRenderingFunction) => Promise<void>;
    }
    interface AtomicInsightResultQuickviewAction {
        /**
          * The `sandbox` attribute to apply to the quickview iframe.  The quickview is loaded inside an iframe with a [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute for security reasons.  This attribute exists primarily to protect against potential XSS attacks that could originate from the document being displayed.  By default, the sandbox attributes are: `allow-popups allow-top-navigation allow-same-origin`.  `allow-same-origin` is not optional, and must always be included in the list of allowed capabilities for the component to function properly.
         */
        "sandbox": string;
    }
    interface AtomicInsightSmartSnippet {
        /**
          * When the answer is partly hidden, how much of its height (in pixels) should be visible.
         */
        "collapsedHeight": number;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the question at the top of the snippet, from 1 to 5.
         */
        "headingLevel": number;
        /**
          * The maximum height (in pixels) a snippet can have before the component truncates it and displays a "show more" button.
         */
        "maximumHeight": number;
        /**
          * Sets the style of the snippet.  Example: ```ts smartSnippet.snippetStyle = `   b {     color: blue;   } `; ```
         */
        "snippetStyle"?: string;
    }
    interface AtomicInsightSmartSnippetSuggestions {
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the "People also ask" heading over the snippets, from 1 to 5.
         */
        "headingLevel": number;
        /**
          * Sets the style of the snippets.  Example: ```ts smartSnippet.snippetStyle = `   b {     color: blue;   } `; ```
         */
        "snippetStyle"?: string;
    }
    interface AtomicInsightTimeframeFacet {
        /**
          * The required facets and values for this facet to be displayed. Examples: ```html <atomic-insight-facet facet-id="abc" field="objecttype" ...></atomic-insight-facet>  <!-- To show the facet when any value is selected in the facet with id "abc": --> <atomic-insight-timeframe-facet   depends-on-abc   ... ></atomic-insight-timeframe-facet>  <!-- To show the facet when value "doc" is selected in the facet with id "abc": --> <atomic-insight-timeframe-facet   depends-on-abc="doc"   ... ></atomic-insight-timeframe-facet> ```
         */
        "dependsOn": Record<string, string>;
        /**
          * Specifies a unique identifier for the facet.
         */
        "facetId"?: string;
        /**
          * The field whose values you want to display in the facet.
         */
        "field": string;
        /**
          * Whether to exclude the parents of folded results when estimating the result count for each facet value.   Note: Resulting count is only an estimation, in some cases this value could be incorrect.
         */
        "filterFacetCount": boolean;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading over the facet, from 1 to 6.
         */
        "headingLevel": number;
        /**
          * The maximum number of results to scan in the index to ensure that the facet lists all potential facet values. Note: A high injectionDepth may negatively impact the facet request performance. Minimum: `0` Default: `1000`
         */
        "injectionDepth": number;
        /**
          * Specifies if the facet is collapsed.
         */
        "isCollapsed": boolean;
        /**
          * The non-localized label for the facet. Used in the atomic-breadbox component through the bindings store.
         */
        "label": string;
        /**
          * The sort criterion to apply to the returned facet values. Possible values are 'ascending' and 'descending'.
         */
        "sortCriteria": InsightRangeFacetSortCriterion;
        /**
          * Whether this facet should contain a date picker allowing users to set custom ranges.
         */
        "withDatePicker": boolean;
    }
    interface AtomicInsightUserActionsModal {
        /**
          * The names of custom events to exclude.
         */
        "excludedCustomActions": string[];
        "isOpen": boolean;
        "openButton"?: HTMLElement;
        /**
          * The date and time when the case was created. For example "2024-01-01T00:00:00Z"
         */
        "ticketCreationDateTime": string;
        /**
          * The ID of the user whose actions are being displayed.
         */
        "userId": string;
    }
    /**
     * @category Insight Panel
     * @example <atomic-insight-user-actions-session userActions={actions} startTimestamp={1723035731}></atomic-insight-user-actions-session>
     */
    interface AtomicInsightUserActionsSession {
        /**
          * The start time of the session as a Unix timestamp.
         */
        "startTimestamp": number;
        /**
          * The list of user actions performed during the session.
         */
        "userActions": Array<IUserAction>;
    }
    /**
     * Internal component used by the `atomic-insight-user-actions-modal`. Do not use directly.
     * This component displays all the actions performed by a user around the time they created a case.
     * The actions are grouped into multiple sessions, including the session during which the case was created,
     * the sessions preceding the case creation and the sessions following the case creation.
     * @component 
     * @example <AtomicInsightUserActionsTimeline userId={'123'} caseCreationDate={'2024-08-15T10:00:00Z'} />
     */
    interface AtomicInsightUserActionsTimeline {
        /**
          * The names of custom events to exclude.
         */
        "excludedCustomActions": string[];
        /**
          * The date and time when the case was created. For example "2024-01-01T00:00:00Z"
         */
        "ticketCreationDateTime": string;
        /**
          * The ID of the user whose actions are being displayed. For example in email format "someone@company.com".
         */
        "userId": string;
    }
    interface AtomicIpxBody {
        "displayFooterSlot": boolean;
        "isOpen"?: boolean;
    }
    /**
     * The `atomic-ipx-recs-list` component displays recommendations by applying one or more result templates.
     */
    interface AtomicIpxRecsList {
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density": ItemDisplayDensity;
        /**
          * The layout to apply when displaying results themselves. This does not affect the display of the surrounding list itself. To modify the number of recommendations per column, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "display": ItemDisplayBasicLayout;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading label, from 1 to 6.
         */
        "headingLevel": number;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize": ItemDisplayImageSize;
        /**
          * The non-localized label for the list of recommendations.
         */
        "label"?: string;
        /**
          * Moves to the next page, when the carousel is activated.
         */
        "nextPage": () => Promise<void>;
        /**
          * The total number of recommendations to display. This does not modify the number of recommendations per column. To do so, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "numberOfRecommendations": number;
        /**
          * The number of recommendations to display, per page. Setting a value greater than and lower than the numberOfRecommendations value activates the carousel. This does not affect the display of the list itself, only the number of recommendation pages.
         */
        "numberOfRecommendationsPerPage"?: number;
        /**
          * Moves to the previous page, when the carousel is activated.
         */
        "previousPage": () => Promise<void>;
        /**
          * The Recommendation identifier used by the Coveo platform to retrieve recommended documents. Make sure to set a different value for each atomic-ipx-recs-list in your page.
         */
        "recommendation": string;
        /**
          * Sets a rendering function to bypass the standard HTML template mechanism for rendering results. You can use this function while working with web frameworks that don't use plain HTML syntax such as React, Angular, or Vue.  Do not use this method if you integrate Atomic in a plain HTML deployment.
          * @param resultRenderingFunction
         */
        "setRenderFunction": (resultRenderingFunction: ItemRenderingFunction) => Promise<void>;
    }
    interface AtomicIpxRefineModal {
        /**
          * The number of expanded facets inside the refine modal. Remaining facets are automatically collapsed.  Using the value `0` collapses all facets.
         */
        "collapseFacetsAfter": number;
        "isOpen": boolean;
        "openButton"?: HTMLElement;
    }
    interface AtomicIpxRefineToggle {
        /**
          * The number of expanded facets inside the refine modal. Remaining facets are automatically collapsed.  Using the value `0` collapses all facets.
         */
        "collapseFacetsAfter": number;
    }
    /**
     * The `atomic-ipx-result-link` component automatically transforms a search result title into a clickable link that points to the original item. It is an experimental internal component not intended for general use.
     */
    interface AtomicIpxResultLink {
        /**
          * Specifies a template literal from which to generate the `href` attribute value (see [Template literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals)).  The template literal can reference any number of result properties from the parent result. It can also reference the window object.  For example, the following markup generates an `href` value such as `http://uri.com?id=itemTitle`, using the result's `clickUri` and `itemtitle` fields. ```html <atomic-ipx-result-link href-template='${clickUri}?id=${raw.itemtitle}'></atomic-ipx-result-link> ```
         */
        "hrefTemplate"?: string;
    }
    /**
     * The `atomic-recs-list` component displays recommendations by applying one or more result templates.
     */
    interface AtomicRecsList {
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density": ItemDisplayDensity;
        /**
          * The layout to apply when displaying results themselves. This does not affect the display of the surrounding list itself. To modify the number of recommendations per column, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "display": ItemDisplayBasicLayout;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading label, from 1 to 6.
         */
        "headingLevel": number;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize": ItemDisplayImageSize;
        /**
          * The non-localized label for the list of recommendations.
         */
        "label"?: string;
        /**
          * Moves to the next page, when the carousel is activated.
         */
        "nextPage": () => Promise<void>;
        /**
          * The total number of recommendations to display. This does not modify the number of recommendations per column. To do so, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "numberOfRecommendations": number;
        /**
          * The number of recommendations to display, per page. Setting a value greater than and lower than the numberOfRecommendations value activates the carousel. This does not affect the display of the list itself, only the number of recommendation pages.
         */
        "numberOfRecommendationsPerPage"?: number;
        /**
          * Moves to the previous page, when the carousel is activated.
         */
        "previousPage": () => Promise<void>;
        /**
          * The Recommendation identifier used by the Coveo platform to retrieve recommended documents. Make sure to set a different value for each atomic-recs-list in your page.
         */
        "recommendation": string;
        /**
          * Sets a rendering function to bypass the standard HTML template mechanism for rendering results. You can use this function while working with web frameworks that don't use plain HTML syntax such as React, Angular, or Vue.  Do not use this method if you integrate Atomic in a plain HTML deployment.
          * @param resultRenderingFunction
         */
        "setRenderFunction": (resultRenderingFunction: ItemRenderingFunction) => Promise<void>;
    }
    /**
     * @deprecated Use `atomic-facet-date-input` instead. This component is meant to be used with Stencil components only.
     * Internal component made to be integrated in a TimeframeFacet.
     */
    interface AtomicStencilFacetDateInput {
        "bindings": AnyBindings;
        "facetId": string;
        "label": string;
        "max"?: string;
        "min"?: string;
        "rangeGetter": () => DateFilterRange | undefined;
        "rangeSetter": (range: DateRangeRequest) => void;
    }
    /**
     * The `atomic-suggestion-renderer` component is used to render individual suggestions. It was created to isolate
     * the rendering logic of the 'content' property of the `SearchBoxSuggestionElement` interface. This property can be Stencil
     * VNode or native Element so there must be a Stencil component to render it. For Lit components using this component, they will
     * use native Elements.
     */
    interface AtomicSuggestionRenderer {
        "i18n": i18n;
        "id": string;
        "index": number;
        "isDoubleList": boolean;
        "isSelected": boolean;
        "lastIndex": number;
        "onClick"?: (e: Event) => void;
        "onMouseEnter"?: (e: Event) => void;
        "side": 'left' | 'right';
        "suggestion": SearchBoxSuggestionElement;
    }
}
export interface AtomicInsightResultActionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAtomicInsightResultActionElement;
}
export interface AtomicInsightResultAttachToCaseActionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAtomicInsightResultAttachToCaseActionElement;
}
export interface AtomicIpxBodyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAtomicIpxBodyElement;
}
export interface AtomicStencilFacetDateInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAtomicStencilFacetDateInputElement;
}
declare global {
    interface HTMLAtomicInsightFoldedResultListElement extends Components.AtomicInsightFoldedResultList, HTMLStencilElement {
    }
    var HTMLAtomicInsightFoldedResultListElement: {
        prototype: HTMLAtomicInsightFoldedResultListElement;
        new (): HTMLAtomicInsightFoldedResultListElement;
    };
    interface HTMLAtomicInsightResultActionElementEventMap {
        "atomicInsightResultActionClicked": InsightResultActionClickedEvent;
    }
    interface HTMLAtomicInsightResultActionElement extends Components.AtomicInsightResultAction, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAtomicInsightResultActionElementEventMap>(type: K, listener: (this: HTMLAtomicInsightResultActionElement, ev: AtomicInsightResultActionCustomEvent<HTMLAtomicInsightResultActionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAtomicInsightResultActionElementEventMap>(type: K, listener: (this: HTMLAtomicInsightResultActionElement, ev: AtomicInsightResultActionCustomEvent<HTMLAtomicInsightResultActionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAtomicInsightResultActionElement: {
        prototype: HTMLAtomicInsightResultActionElement;
        new (): HTMLAtomicInsightResultActionElement;
    };
    interface HTMLAtomicInsightResultActionBarElement extends Components.AtomicInsightResultActionBar, HTMLStencilElement {
    }
    var HTMLAtomicInsightResultActionBarElement: {
        prototype: HTMLAtomicInsightResultActionBarElement;
        new (): HTMLAtomicInsightResultActionBarElement;
    };
    interface HTMLAtomicInsightResultAttachToCaseActionElementEventMap {
        "atomic/insight/attachToCase/attach": InsightResultAttachToCaseEvent;
        "atomic/insight/attachToCase/detach": InsightResultAttachToCaseEvent;
    }
    interface HTMLAtomicInsightResultAttachToCaseActionElement extends Components.AtomicInsightResultAttachToCaseAction, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAtomicInsightResultAttachToCaseActionElementEventMap>(type: K, listener: (this: HTMLAtomicInsightResultAttachToCaseActionElement, ev: AtomicInsightResultAttachToCaseActionCustomEvent<HTMLAtomicInsightResultAttachToCaseActionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAtomicInsightResultAttachToCaseActionElementEventMap>(type: K, listener: (this: HTMLAtomicInsightResultAttachToCaseActionElement, ev: AtomicInsightResultAttachToCaseActionCustomEvent<HTMLAtomicInsightResultAttachToCaseActionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAtomicInsightResultAttachToCaseActionElement: {
        prototype: HTMLAtomicInsightResultAttachToCaseActionElement;
        new (): HTMLAtomicInsightResultAttachToCaseActionElement;
    };
    interface HTMLAtomicInsightResultAttachToCaseIndicatorElement extends Components.AtomicInsightResultAttachToCaseIndicator, HTMLStencilElement {
    }
    var HTMLAtomicInsightResultAttachToCaseIndicatorElement: {
        prototype: HTMLAtomicInsightResultAttachToCaseIndicatorElement;
        new (): HTMLAtomicInsightResultAttachToCaseIndicatorElement;
    };
    interface HTMLAtomicInsightResultChildrenTemplateElement extends Components.AtomicInsightResultChildrenTemplate, HTMLStencilElement {
    }
    var HTMLAtomicInsightResultChildrenTemplateElement: {
        prototype: HTMLAtomicInsightResultChildrenTemplateElement;
        new (): HTMLAtomicInsightResultChildrenTemplateElement;
    };
    interface HTMLAtomicInsightResultListElement extends Components.AtomicInsightResultList, HTMLStencilElement {
    }
    var HTMLAtomicInsightResultListElement: {
        prototype: HTMLAtomicInsightResultListElement;
        new (): HTMLAtomicInsightResultListElement;
    };
    interface HTMLAtomicInsightResultQuickviewActionElement extends Components.AtomicInsightResultQuickviewAction, HTMLStencilElement {
    }
    var HTMLAtomicInsightResultQuickviewActionElement: {
        prototype: HTMLAtomicInsightResultQuickviewActionElement;
        new (): HTMLAtomicInsightResultQuickviewActionElement;
    };
    interface HTMLAtomicInsightSmartSnippetElement extends Components.AtomicInsightSmartSnippet, HTMLStencilElement {
    }
    var HTMLAtomicInsightSmartSnippetElement: {
        prototype: HTMLAtomicInsightSmartSnippetElement;
        new (): HTMLAtomicInsightSmartSnippetElement;
    };
    interface HTMLAtomicInsightSmartSnippetSuggestionsElement extends Components.AtomicInsightSmartSnippetSuggestions, HTMLStencilElement {
    }
    var HTMLAtomicInsightSmartSnippetSuggestionsElement: {
        prototype: HTMLAtomicInsightSmartSnippetSuggestionsElement;
        new (): HTMLAtomicInsightSmartSnippetSuggestionsElement;
    };
    interface HTMLAtomicInsightTimeframeFacetElement extends Components.AtomicInsightTimeframeFacet, HTMLStencilElement {
    }
    var HTMLAtomicInsightTimeframeFacetElement: {
        prototype: HTMLAtomicInsightTimeframeFacetElement;
        new (): HTMLAtomicInsightTimeframeFacetElement;
    };
    interface HTMLAtomicInsightUserActionsModalElement extends Components.AtomicInsightUserActionsModal, HTMLStencilElement {
    }
    var HTMLAtomicInsightUserActionsModalElement: {
        prototype: HTMLAtomicInsightUserActionsModalElement;
        new (): HTMLAtomicInsightUserActionsModalElement;
    };
    /**
     * @category Insight Panel
     * @example <atomic-insight-user-actions-session userActions={actions} startTimestamp={1723035731}></atomic-insight-user-actions-session>
     */
    interface HTMLAtomicInsightUserActionsSessionElement extends Components.AtomicInsightUserActionsSession, HTMLStencilElement {
    }
    var HTMLAtomicInsightUserActionsSessionElement: {
        prototype: HTMLAtomicInsightUserActionsSessionElement;
        new (): HTMLAtomicInsightUserActionsSessionElement;
    };
    /**
     * Internal component used by the `atomic-insight-user-actions-modal`. Do not use directly.
     * This component displays all the actions performed by a user around the time they created a case.
     * The actions are grouped into multiple sessions, including the session during which the case was created,
     * the sessions preceding the case creation and the sessions following the case creation.
     * @component 
     * @example <AtomicInsightUserActionsTimeline userId={'123'} caseCreationDate={'2024-08-15T10:00:00Z'} />
     */
    interface HTMLAtomicInsightUserActionsTimelineElement extends Components.AtomicInsightUserActionsTimeline, HTMLStencilElement {
    }
    var HTMLAtomicInsightUserActionsTimelineElement: {
        prototype: HTMLAtomicInsightUserActionsTimelineElement;
        new (): HTMLAtomicInsightUserActionsTimelineElement;
    };
    interface HTMLAtomicIpxBodyElementEventMap {
        "animationEnded": never;
    }
    interface HTMLAtomicIpxBodyElement extends Components.AtomicIpxBody, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAtomicIpxBodyElementEventMap>(type: K, listener: (this: HTMLAtomicIpxBodyElement, ev: AtomicIpxBodyCustomEvent<HTMLAtomicIpxBodyElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAtomicIpxBodyElementEventMap>(type: K, listener: (this: HTMLAtomicIpxBodyElement, ev: AtomicIpxBodyCustomEvent<HTMLAtomicIpxBodyElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAtomicIpxBodyElement: {
        prototype: HTMLAtomicIpxBodyElement;
        new (): HTMLAtomicIpxBodyElement;
    };
    /**
     * The `atomic-ipx-recs-list` component displays recommendations by applying one or more result templates.
     */
    interface HTMLAtomicIpxRecsListElement extends Components.AtomicIpxRecsList, HTMLStencilElement {
    }
    var HTMLAtomicIpxRecsListElement: {
        prototype: HTMLAtomicIpxRecsListElement;
        new (): HTMLAtomicIpxRecsListElement;
    };
    interface HTMLAtomicIpxRefineModalElement extends Components.AtomicIpxRefineModal, HTMLStencilElement {
    }
    var HTMLAtomicIpxRefineModalElement: {
        prototype: HTMLAtomicIpxRefineModalElement;
        new (): HTMLAtomicIpxRefineModalElement;
    };
    interface HTMLAtomicIpxRefineToggleElement extends Components.AtomicIpxRefineToggle, HTMLStencilElement {
    }
    var HTMLAtomicIpxRefineToggleElement: {
        prototype: HTMLAtomicIpxRefineToggleElement;
        new (): HTMLAtomicIpxRefineToggleElement;
    };
    /**
     * The `atomic-ipx-result-link` component automatically transforms a search result title into a clickable link that points to the original item. It is an experimental internal component not intended for general use.
     */
    interface HTMLAtomicIpxResultLinkElement extends Components.AtomicIpxResultLink, HTMLStencilElement {
    }
    var HTMLAtomicIpxResultLinkElement: {
        prototype: HTMLAtomicIpxResultLinkElement;
        new (): HTMLAtomicIpxResultLinkElement;
    };
    /**
     * The `atomic-recs-list` component displays recommendations by applying one or more result templates.
     */
    interface HTMLAtomicRecsListElement extends Components.AtomicRecsList, HTMLStencilElement {
    }
    var HTMLAtomicRecsListElement: {
        prototype: HTMLAtomicRecsListElement;
        new (): HTMLAtomicRecsListElement;
    };
    interface HTMLAtomicStencilFacetDateInputElementEventMap {
        "atomic/dateInputApply": any;
    }
    /**
     * @deprecated Use `atomic-facet-date-input` instead. This component is meant to be used with Stencil components only.
     * Internal component made to be integrated in a TimeframeFacet.
     */
    interface HTMLAtomicStencilFacetDateInputElement extends Components.AtomicStencilFacetDateInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAtomicStencilFacetDateInputElementEventMap>(type: K, listener: (this: HTMLAtomicStencilFacetDateInputElement, ev: AtomicStencilFacetDateInputCustomEvent<HTMLAtomicStencilFacetDateInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAtomicStencilFacetDateInputElementEventMap>(type: K, listener: (this: HTMLAtomicStencilFacetDateInputElement, ev: AtomicStencilFacetDateInputCustomEvent<HTMLAtomicStencilFacetDateInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAtomicStencilFacetDateInputElement: {
        prototype: HTMLAtomicStencilFacetDateInputElement;
        new (): HTMLAtomicStencilFacetDateInputElement;
    };
    /**
     * The `atomic-suggestion-renderer` component is used to render individual suggestions. It was created to isolate
     * the rendering logic of the 'content' property of the `SearchBoxSuggestionElement` interface. This property can be Stencil
     * VNode or native Element so there must be a Stencil component to render it. For Lit components using this component, they will
     * use native Elements.
     */
    interface HTMLAtomicSuggestionRendererElement extends Components.AtomicSuggestionRenderer, HTMLStencilElement {
    }
    var HTMLAtomicSuggestionRendererElement: {
        prototype: HTMLAtomicSuggestionRendererElement;
        new (): HTMLAtomicSuggestionRendererElement;
    };
    interface HTMLElementTagNameMap {
        "atomic-insight-folded-result-list": HTMLAtomicInsightFoldedResultListElement;
        "atomic-insight-result-action": HTMLAtomicInsightResultActionElement;
        "atomic-insight-result-action-bar": HTMLAtomicInsightResultActionBarElement;
        "atomic-insight-result-attach-to-case-action": HTMLAtomicInsightResultAttachToCaseActionElement;
        "atomic-insight-result-attach-to-case-indicator": HTMLAtomicInsightResultAttachToCaseIndicatorElement;
        "atomic-insight-result-children-template": HTMLAtomicInsightResultChildrenTemplateElement;
        "atomic-insight-result-list": HTMLAtomicInsightResultListElement;
        "atomic-insight-result-quickview-action": HTMLAtomicInsightResultQuickviewActionElement;
        "atomic-insight-smart-snippet": HTMLAtomicInsightSmartSnippetElement;
        "atomic-insight-smart-snippet-suggestions": HTMLAtomicInsightSmartSnippetSuggestionsElement;
        "atomic-insight-timeframe-facet": HTMLAtomicInsightTimeframeFacetElement;
        "atomic-insight-user-actions-modal": HTMLAtomicInsightUserActionsModalElement;
        "atomic-insight-user-actions-session": HTMLAtomicInsightUserActionsSessionElement;
        "atomic-insight-user-actions-timeline": HTMLAtomicInsightUserActionsTimelineElement;
        "atomic-ipx-body": HTMLAtomicIpxBodyElement;
        "atomic-ipx-recs-list": HTMLAtomicIpxRecsListElement;
        "atomic-ipx-refine-modal": HTMLAtomicIpxRefineModalElement;
        "atomic-ipx-refine-toggle": HTMLAtomicIpxRefineToggleElement;
        "atomic-ipx-result-link": HTMLAtomicIpxResultLinkElement;
        "atomic-recs-list": HTMLAtomicRecsListElement;
        "atomic-stencil-facet-date-input": HTMLAtomicStencilFacetDateInputElement;
        "atomic-suggestion-renderer": HTMLAtomicSuggestionRendererElement;
    }
}
declare namespace LocalJSX {
    interface AtomicInsightFoldedResultList {
        /**
          * The name of the field that uniquely identifies a result within a collection.
          * @defaultValue `foldingchild`
         */
        "childField"?: string;
        /**
          * The name of the field on which to do the folding. The folded result list component will use the values of this field to resolve the collections of result items.
          * @defaultValue `foldingcollection`
         */
        "collectionField"?: string;
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density"?: ItemDisplayDensity;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize"?: ItemDisplayImageSize;
        /**
          * The name of the field that determines whether a certain result is a top result containing other child results within a collection.
          * @defaultValue `foldingparent`
         */
        "parentField"?: string;
    }
    interface AtomicInsightResultAction {
        /**
          * The type of action to perform when the result action is clicked. This will be sent along the event fired when the button is clicked.
         */
        "action"?: Actions | string;
        /**
          * Specify the result action icon to display.
         */
        "icon"?: string;
        /**
          * @migration Stencil's
          * @Event () decorator defaults to: bubbles=true, composed=true, cancelable=true. Native CustomEvent defaults to: bubbles=false, composed=false, cancelable=false. When migrating to Lit, explicitly set all three options to preserve behavior: `new CustomEvent('atomicInsightResultActionClicked', { bubbles: true, composed: true, cancelable: true, detail: ... })`
         */
        "onAtomicInsightResultActionClicked"?: (event: AtomicInsightResultActionCustomEvent<InsightResultActionClickedEvent>) => void;
        /**
          * The text tooltip to show on the result action icon.
         */
        "tooltip"?: string;
        /**
          * The text tooltip to show on the result action icon for some time after clicking the button.
         */
        "tooltipOnClick"?: string;
    }
    interface AtomicInsightResultActionBar {
    }
    interface AtomicInsightResultAttachToCaseAction {
        /**
          * @migration Stencil's
          * @Event () decorator defaults to: bubbles=true, composed=true, cancelable=true. Native CustomEvent defaults to: bubbles=false, composed=false, cancelable=false. When migrating to Lit, explicitly set all three options to preserve behavior: `new CustomEvent('atomic/insight/attachToCase/attach', { bubbles: true, composed: true, cancelable: true, detail: ... })` `new CustomEvent('atomic/insight/attachToCase/detach', { bubbles: true, composed: true, cancelable: true, detail: ... })`
         */
        "onAtomic/insight/attachToCase/attach"?: (event: AtomicInsightResultAttachToCaseActionCustomEvent<InsightResultAttachToCaseEvent>) => void;
        "onAtomic/insight/attachToCase/detach"?: (event: AtomicInsightResultAttachToCaseActionCustomEvent<InsightResultAttachToCaseEvent>) => void;
    }
    interface AtomicInsightResultAttachToCaseIndicator {
    }
    interface AtomicInsightResultChildrenTemplate {
        /**
          * A function that must return true on results for the result template to apply. Set programmatically before initialization, not via attribute.  For example, the following targets a template and sets a condition to make it apply only to results whose `title` contains `singapore`: `document.querySelector('#target-template').conditions = [(result) => /singapore/i.test(result.title)];`
         */
        "conditions"?: ResultTemplateCondition[];
        /**
          * The field that, when defined on a result item, would allow the template to be applied.  For example, a template with the following attribute only applies to result items whose `filetype` and `sourcetype` fields are defined: `if-defined="filetype,sourcetype"`
         */
        "ifDefined"?: string;
        /**
          * The field that, when defined on a result item, would prevent the template from being applied.  For example, a template with the following attribute only applies to result items whose `filetype` and `sourcetype` fields are NOT defined: `if-not-defined="filetype,sourcetype"`
         */
        "ifNotDefined"?: string;
        /**
          * The field and values that define which result items the condition must be applied to.  For example, a template with the following attribute only applies to result items whose `filetype` is `lithiummessage` or `YouTubePlaylist`: `must-match-filetype="lithiummessage,YouTubePlaylist"`
         */
        "mustMatch"?: Record<
    string,
    string[]
  >;
        /**
          * The field and values that define which result items the condition must not be applied to.  For example, a template with the following attribute only applies to result items whose `filetype` is not `lithiummessage`: `must-not-match-filetype="lithiummessage"`
         */
        "mustNotMatch"?: Record<
    string,
    string[]
  >;
    }
    interface AtomicInsightResultList {
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density"?: ItemDisplayDensity;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize"?: ItemDisplayImageSize;
    }
    interface AtomicInsightResultQuickviewAction {
        /**
          * The `sandbox` attribute to apply to the quickview iframe.  The quickview is loaded inside an iframe with a [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute for security reasons.  This attribute exists primarily to protect against potential XSS attacks that could originate from the document being displayed.  By default, the sandbox attributes are: `allow-popups allow-top-navigation allow-same-origin`.  `allow-same-origin` is not optional, and must always be included in the list of allowed capabilities for the component to function properly.
         */
        "sandbox"?: string;
    }
    interface AtomicInsightSmartSnippet {
        /**
          * When the answer is partly hidden, how much of its height (in pixels) should be visible.
         */
        "collapsedHeight"?: number;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the question at the top of the snippet, from 1 to 5.
         */
        "headingLevel"?: number;
        /**
          * The maximum height (in pixels) a snippet can have before the component truncates it and displays a "show more" button.
         */
        "maximumHeight"?: number;
        /**
          * Sets the style of the snippet.  Example: ```ts smartSnippet.snippetStyle = `   b {     color: blue;   } `; ```
         */
        "snippetStyle"?: string;
    }
    interface AtomicInsightSmartSnippetSuggestions {
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the "People also ask" heading over the snippets, from 1 to 5.
         */
        "headingLevel"?: number;
        /**
          * Sets the style of the snippets.  Example: ```ts smartSnippet.snippetStyle = `   b {     color: blue;   } `; ```
         */
        "snippetStyle"?: string;
    }
    interface AtomicInsightTimeframeFacet {
        /**
          * The required facets and values for this facet to be displayed. Examples: ```html <atomic-insight-facet facet-id="abc" field="objecttype" ...></atomic-insight-facet>  <!-- To show the facet when any value is selected in the facet with id "abc": --> <atomic-insight-timeframe-facet   depends-on-abc   ... ></atomic-insight-timeframe-facet>  <!-- To show the facet when value "doc" is selected in the facet with id "abc": --> <atomic-insight-timeframe-facet   depends-on-abc="doc"   ... ></atomic-insight-timeframe-facet> ```
         */
        "dependsOn"?: Record<string, string>;
        /**
          * Specifies a unique identifier for the facet.
         */
        "facetId"?: string;
        /**
          * The field whose values you want to display in the facet.
         */
        "field"?: string;
        /**
          * Whether to exclude the parents of folded results when estimating the result count for each facet value.   Note: Resulting count is only an estimation, in some cases this value could be incorrect.
         */
        "filterFacetCount"?: boolean;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading over the facet, from 1 to 6.
         */
        "headingLevel"?: number;
        /**
          * The maximum number of results to scan in the index to ensure that the facet lists all potential facet values. Note: A high injectionDepth may negatively impact the facet request performance. Minimum: `0` Default: `1000`
         */
        "injectionDepth"?: number;
        /**
          * Specifies if the facet is collapsed.
         */
        "isCollapsed"?: boolean;
        /**
          * The non-localized label for the facet. Used in the atomic-breadbox component through the bindings store.
         */
        "label"?: string;
        /**
          * The sort criterion to apply to the returned facet values. Possible values are 'ascending' and 'descending'.
         */
        "sortCriteria"?: InsightRangeFacetSortCriterion;
        /**
          * Whether this facet should contain a date picker allowing users to set custom ranges.
         */
        "withDatePicker"?: boolean;
    }
    interface AtomicInsightUserActionsModal {
        /**
          * The names of custom events to exclude.
         */
        "excludedCustomActions"?: string[];
        "isOpen"?: boolean;
        "openButton"?: HTMLElement;
        /**
          * The date and time when the case was created. For example "2024-01-01T00:00:00Z"
         */
        "ticketCreationDateTime": string;
        /**
          * The ID of the user whose actions are being displayed.
         */
        "userId": string;
    }
    /**
     * @category Insight Panel
     * @example <atomic-insight-user-actions-session userActions={actions} startTimestamp={1723035731}></atomic-insight-user-actions-session>
     */
    interface AtomicInsightUserActionsSession {
        /**
          * The start time of the session as a Unix timestamp.
         */
        "startTimestamp": number;
        /**
          * The list of user actions performed during the session.
         */
        "userActions": Array<IUserAction>;
    }
    /**
     * Internal component used by the `atomic-insight-user-actions-modal`. Do not use directly.
     * This component displays all the actions performed by a user around the time they created a case.
     * The actions are grouped into multiple sessions, including the session during which the case was created,
     * the sessions preceding the case creation and the sessions following the case creation.
     * @component 
     * @example <AtomicInsightUserActionsTimeline userId={'123'} caseCreationDate={'2024-08-15T10:00:00Z'} />
     */
    interface AtomicInsightUserActionsTimeline {
        /**
          * The names of custom events to exclude.
         */
        "excludedCustomActions"?: string[];
        /**
          * The date and time when the case was created. For example "2024-01-01T00:00:00Z"
         */
        "ticketCreationDateTime": string;
        /**
          * The ID of the user whose actions are being displayed. For example in email format "someone@company.com".
         */
        "userId": string;
    }
    interface AtomicIpxBody {
        "displayFooterSlot"?: boolean;
        "isOpen"?: boolean;
        /**
          * @migration Stencil's
          * @Event () decorator defaults to: bubbles=true, composed=true, cancelable=true. Native CustomEvent defaults to: bubbles=false, composed=false, cancelable=false. When migrating to Lit, explicitly set all three options to preserve behavior: `new CustomEvent('animationEnded', { bubbles: true, composed: true, cancelable: true })`
         */
        "onAnimationEnded"?: (event: AtomicIpxBodyCustomEvent<never>) => void;
    }
    /**
     * The `atomic-ipx-recs-list` component displays recommendations by applying one or more result templates.
     */
    interface AtomicIpxRecsList {
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density"?: ItemDisplayDensity;
        /**
          * The layout to apply when displaying results themselves. This does not affect the display of the surrounding list itself. To modify the number of recommendations per column, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "display"?: ItemDisplayBasicLayout;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading label, from 1 to 6.
         */
        "headingLevel"?: number;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize"?: ItemDisplayImageSize;
        /**
          * The non-localized label for the list of recommendations.
         */
        "label"?: string;
        /**
          * The total number of recommendations to display. This does not modify the number of recommendations per column. To do so, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "numberOfRecommendations"?: number;
        /**
          * The number of recommendations to display, per page. Setting a value greater than and lower than the numberOfRecommendations value activates the carousel. This does not affect the display of the list itself, only the number of recommendation pages.
         */
        "numberOfRecommendationsPerPage"?: number;
        /**
          * The Recommendation identifier used by the Coveo platform to retrieve recommended documents. Make sure to set a different value for each atomic-ipx-recs-list in your page.
         */
        "recommendation"?: string;
    }
    interface AtomicIpxRefineModal {
        /**
          * The number of expanded facets inside the refine modal. Remaining facets are automatically collapsed.  Using the value `0` collapses all facets.
         */
        "collapseFacetsAfter"?: number;
        "isOpen"?: boolean;
        "openButton"?: HTMLElement;
    }
    interface AtomicIpxRefineToggle {
        /**
          * The number of expanded facets inside the refine modal. Remaining facets are automatically collapsed.  Using the value `0` collapses all facets.
         */
        "collapseFacetsAfter"?: number;
    }
    /**
     * The `atomic-ipx-result-link` component automatically transforms a search result title into a clickable link that points to the original item. It is an experimental internal component not intended for general use.
     */
    interface AtomicIpxResultLink {
        /**
          * Specifies a template literal from which to generate the `href` attribute value (see [Template literals](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals)).  The template literal can reference any number of result properties from the parent result. It can also reference the window object.  For example, the following markup generates an `href` value such as `http://uri.com?id=itemTitle`, using the result's `clickUri` and `itemtitle` fields. ```html <atomic-ipx-result-link href-template='${clickUri}?id=${raw.itemtitle}'></atomic-ipx-result-link> ```
         */
        "hrefTemplate"?: string;
    }
    /**
     * The `atomic-recs-list` component displays recommendations by applying one or more result templates.
     */
    interface AtomicRecsList {
        /**
          * The spacing of various elements in the result list, including the gap between results, the gap between parts of a result, and the font sizes of different parts in a result.
         */
        "density"?: ItemDisplayDensity;
        /**
          * The layout to apply when displaying results themselves. This does not affect the display of the surrounding list itself. To modify the number of recommendations per column, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "display"?: ItemDisplayBasicLayout;
        /**
          * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use for the heading label, from 1 to 6.
         */
        "headingLevel"?: number;
        /**
          * The expected size of the image displayed in the results.
         */
        "imageSize"?: ItemDisplayImageSize;
        /**
          * The non-localized label for the list of recommendations.
         */
        "label"?: string;
        /**
          * The total number of recommendations to display. This does not modify the number of recommendations per column. To do so, modify the --atomic-recs-number-of-columns CSS variable.
         */
        "numberOfRecommendations"?: number;
        /**
          * The number of recommendations to display, per page. Setting a value greater than and lower than the numberOfRecommendations value activates the carousel. This does not affect the display of the list itself, only the number of recommendation pages.
         */
        "numberOfRecommendationsPerPage"?: number;
        /**
          * The Recommendation identifier used by the Coveo platform to retrieve recommended documents. Make sure to set a different value for each atomic-recs-list in your page.
         */
        "recommendation"?: string;
    }
    /**
     * @deprecated Use `atomic-facet-date-input` instead. This component is meant to be used with Stencil components only.
     * Internal component made to be integrated in a TimeframeFacet.
     */
    interface AtomicStencilFacetDateInput {
        "bindings": AnyBindings;
        "facetId": string;
        "label": string;
        "max"?: string;
        "min"?: string;
        /**
          * @migration Stencil's
          * @Event () decorator defaults to: bubbles=true, composed=true, cancelable=true. Native CustomEvent defaults to: bubbles=false, composed=false, cancelable=false. When migrating to Lit, explicitly set all three options to preserve behavior: `new CustomEvent('atomic/dateInputApply', { bubbles: true, composed: true, cancelable: true, detail: ... })`
         */
        "onAtomic/dateInputApply"?: (event: AtomicStencilFacetDateInputCustomEvent<any>) => void;
        "rangeGetter": () => DateFilterRange | undefined;
        "rangeSetter": (range: DateRangeRequest) => void;
    }
    /**
     * The `atomic-suggestion-renderer` component is used to render individual suggestions. It was created to isolate
     * the rendering logic of the 'content' property of the `SearchBoxSuggestionElement` interface. This property can be Stencil
     * VNode or native Element so there must be a Stencil component to render it. For Lit components using this component, they will
     * use native Elements.
     */
    interface AtomicSuggestionRenderer {
        "i18n": i18n;
        "id": string;
        "index": number;
        "isDoubleList": boolean;
        "isSelected": boolean;
        "lastIndex": number;
        "onClick"?: (e: Event) => void;
        "onMouseEnter"?: (e: Event) => void;
        "side": 'left' | 'right';
        "suggestion": SearchBoxSuggestionElement;
    }
    interface IntrinsicElements {
        "atomic-insight-folded-result-list": AtomicInsightFoldedResultList;
        "atomic-insight-result-action": AtomicInsightResultAction;
        "atomic-insight-result-action-bar": AtomicInsightResultActionBar;
        "atomic-insight-result-attach-to-case-action": AtomicInsightResultAttachToCaseAction;
        "atomic-insight-result-attach-to-case-indicator": AtomicInsightResultAttachToCaseIndicator;
        "atomic-insight-result-children-template": AtomicInsightResultChildrenTemplate;
        "atomic-insight-result-list": AtomicInsightResultList;
        "atomic-insight-result-quickview-action": AtomicInsightResultQuickviewAction;
        "atomic-insight-smart-snippet": AtomicInsightSmartSnippet;
        "atomic-insight-smart-snippet-suggestions": AtomicInsightSmartSnippetSuggestions;
        "atomic-insight-timeframe-facet": AtomicInsightTimeframeFacet;
        "atomic-insight-user-actions-modal": AtomicInsightUserActionsModal;
        "atomic-insight-user-actions-session": AtomicInsightUserActionsSession;
        "atomic-insight-user-actions-timeline": AtomicInsightUserActionsTimeline;
        "atomic-ipx-body": AtomicIpxBody;
        "atomic-ipx-recs-list": AtomicIpxRecsList;
        "atomic-ipx-refine-modal": AtomicIpxRefineModal;
        "atomic-ipx-refine-toggle": AtomicIpxRefineToggle;
        "atomic-ipx-result-link": AtomicIpxResultLink;
        "atomic-recs-list": AtomicRecsList;
        "atomic-stencil-facet-date-input": AtomicStencilFacetDateInput;
        "atomic-suggestion-renderer": AtomicSuggestionRenderer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "atomic-insight-folded-result-list": LocalJSX.AtomicInsightFoldedResultList & JSXBase.HTMLAttributes<HTMLAtomicInsightFoldedResultListElement>;
            "atomic-insight-result-action": LocalJSX.AtomicInsightResultAction & JSXBase.HTMLAttributes<HTMLAtomicInsightResultActionElement>;
            "atomic-insight-result-action-bar": LocalJSX.AtomicInsightResultActionBar & JSXBase.HTMLAttributes<HTMLAtomicInsightResultActionBarElement>;
            "atomic-insight-result-attach-to-case-action": LocalJSX.AtomicInsightResultAttachToCaseAction & JSXBase.HTMLAttributes<HTMLAtomicInsightResultAttachToCaseActionElement>;
            "atomic-insight-result-attach-to-case-indicator": LocalJSX.AtomicInsightResultAttachToCaseIndicator & JSXBase.HTMLAttributes<HTMLAtomicInsightResultAttachToCaseIndicatorElement>;
            "atomic-insight-result-children-template": LocalJSX.AtomicInsightResultChildrenTemplate & JSXBase.HTMLAttributes<HTMLAtomicInsightResultChildrenTemplateElement>;
            "atomic-insight-result-list": LocalJSX.AtomicInsightResultList & JSXBase.HTMLAttributes<HTMLAtomicInsightResultListElement>;
            "atomic-insight-result-quickview-action": LocalJSX.AtomicInsightResultQuickviewAction & JSXBase.HTMLAttributes<HTMLAtomicInsightResultQuickviewActionElement>;
            "atomic-insight-smart-snippet": LocalJSX.AtomicInsightSmartSnippet & JSXBase.HTMLAttributes<HTMLAtomicInsightSmartSnippetElement>;
            "atomic-insight-smart-snippet-suggestions": LocalJSX.AtomicInsightSmartSnippetSuggestions & JSXBase.HTMLAttributes<HTMLAtomicInsightSmartSnippetSuggestionsElement>;
            "atomic-insight-timeframe-facet": LocalJSX.AtomicInsightTimeframeFacet & JSXBase.HTMLAttributes<HTMLAtomicInsightTimeframeFacetElement>;
            "atomic-insight-user-actions-modal": LocalJSX.AtomicInsightUserActionsModal & JSXBase.HTMLAttributes<HTMLAtomicInsightUserActionsModalElement>;
            /**
             * @category Insight Panel
             * @example <atomic-insight-user-actions-session userActions={actions} startTimestamp={1723035731}></atomic-insight-user-actions-session>
             */
            "atomic-insight-user-actions-session": LocalJSX.AtomicInsightUserActionsSession & JSXBase.HTMLAttributes<HTMLAtomicInsightUserActionsSessionElement>;
            /**
             * Internal component used by the `atomic-insight-user-actions-modal`. Do not use directly.
             * This component displays all the actions performed by a user around the time they created a case.
             * The actions are grouped into multiple sessions, including the session during which the case was created,
             * the sessions preceding the case creation and the sessions following the case creation.
             * @component 
             * @example <AtomicInsightUserActionsTimeline userId={'123'} caseCreationDate={'2024-08-15T10:00:00Z'} />
             */
            "atomic-insight-user-actions-timeline": LocalJSX.AtomicInsightUserActionsTimeline & JSXBase.HTMLAttributes<HTMLAtomicInsightUserActionsTimelineElement>;
            "atomic-ipx-body": LocalJSX.AtomicIpxBody & JSXBase.HTMLAttributes<HTMLAtomicIpxBodyElement>;
            /**
             * The `atomic-ipx-recs-list` component displays recommendations by applying one or more result templates.
             */
            "atomic-ipx-recs-list": LocalJSX.AtomicIpxRecsList & JSXBase.HTMLAttributes<HTMLAtomicIpxRecsListElement>;
            "atomic-ipx-refine-modal": LocalJSX.AtomicIpxRefineModal & JSXBase.HTMLAttributes<HTMLAtomicIpxRefineModalElement>;
            "atomic-ipx-refine-toggle": LocalJSX.AtomicIpxRefineToggle & JSXBase.HTMLAttributes<HTMLAtomicIpxRefineToggleElement>;
            /**
             * The `atomic-ipx-result-link` component automatically transforms a search result title into a clickable link that points to the original item. It is an experimental internal component not intended for general use.
             */
            "atomic-ipx-result-link": LocalJSX.AtomicIpxResultLink & JSXBase.HTMLAttributes<HTMLAtomicIpxResultLinkElement>;
            /**
             * The `atomic-recs-list` component displays recommendations by applying one or more result templates.
             */
            "atomic-recs-list": LocalJSX.AtomicRecsList & JSXBase.HTMLAttributes<HTMLAtomicRecsListElement>;
            /**
             * @deprecated Use `atomic-facet-date-input` instead. This component is meant to be used with Stencil components only.
             * Internal component made to be integrated in a TimeframeFacet.
             */
            "atomic-stencil-facet-date-input": LocalJSX.AtomicStencilFacetDateInput & JSXBase.HTMLAttributes<HTMLAtomicStencilFacetDateInputElement>;
            /**
             * The `atomic-suggestion-renderer` component is used to render individual suggestions. It was created to isolate
             * the rendering logic of the 'content' property of the `SearchBoxSuggestionElement` interface. This property can be Stencil
             * VNode or native Element so there must be a Stencil component to render it. For Lit components using this component, they will
             * use native Elements.
             */
            "atomic-suggestion-renderer": LocalJSX.AtomicSuggestionRenderer & JSXBase.HTMLAttributes<HTMLAtomicSuggestionRendererElement>;
        }
    }
}
