name: 'Atomic E2E Screenshot tests'
description: 'Runs Cypress Screenshots tests for Atomic'
inputs:
  github-token:
    description: The GitHub token for accurately detecting a build vs a re-run build
    required: false
    default: ''
runs:
  using: composite
  steps:
    - run: pnpm exec cypress install
      shell: bash
      working-directory: packages/atomic
    - uses: cypress-io/github-action@bc22e01685c56e89e7813fd8e26f33dc47f87e15 # v7.1.5
      name: Run Cypress
      with:
        browser: chrome
        command-prefix: 'pnpm --filter @coveo/atomic exec cypress-repeat run -n 3 --until-passes --rerun-failed-only --'
        config-file: cypress-screenshots.config.mjs
        start: pnpm exec turbo web:dev --filter=@coveo/atomic
        wait-on: 'http://localhost:3333'
        wait-on-timeout: 600000
        install: false
        record: false
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      if: cancelled() || failure() || success()
      with:
        name: result-lists-screenshots
        path: packages/atomic/cypress/screenshots
