export const baseSearchResponse = {
  totalCount: 120,
  totalCountFiltered: 120,
  duration: 175,
  indexDuration: 18,
  requestDuration: 41,
  searchUid: '2971cca7-90b4-4b64-97dd-5dac45c1cc43',
  pipeline: 'genqatest',
  apiVersion: 2,
  queryCorrections: [],
  basicExpression: 'how to resolve netflix connection with tivo',
  advancedExpression: null,
  largeExpression: null,
  constantExpression: null,
  disjunctionExpression: null,
  mandatoryExpression: null,
  userIdentities: [
    {
      name: 'anonymous_user@anonymous.coveo.com',
      provider: 'Email Security Provider',
      type: 'User',
    },
  ],
  rankingExpressions: [],
  topResults: [],
  executionReport: {},
  refinedKeywords: [],
  triggers: [],
  termsToHighlight: {},
  phrasesToHighlight: {},
  groupByResults: [],
  facets: [],
  suggestedFacets: [],
  categoryFacets: [],
  results: [
    {
      title: 'Sample Result 1',
      excerpt: 'This is a sample result excerpt for testing.',
      clickUri: 'https://example.com/search/1',
      uniqueId: 'rec-1',
      raw: {
        systitle: 'Sample Result 1',
        sysdescription: 'This is a sample result excerpt for testing.',
        sysuri: 'https://example.com/search/1',
      },
    },
    {
      title: 'Sample Result 2',
      excerpt: 'This is another sample result for testing purposes.',
      clickUri: 'https://example.com/search/2',
      uniqueId: 'rec-2',
      raw: {
        systitle: 'Sample Result 2',
        sysdescription: 'This is another sample result for testing purposes.',
        sysuri: 'https://example.com/search/2',
      },
    },
    {
      title: 'Sample Result 3',
      excerpt: 'Third sample result with useful content.',
      clickUri: 'https://example.com/search/3',
      uniqueId: 'rec-3',
      raw: {
        systitle: 'Sample Result 3',
        sysdescription: 'Third sample result with useful content.',
        sysuri: 'https://example.com/search/3',
      },
    },
  ],
  questionAnswer: {
    answerFound: false,
    question: '',
    answerSnippet: '',
    documentId: {
      contentIdKey: '',
      contentIdValue: '',
    },
    score: 0.0,
    relatedQuestions: [],
  },
};
