name: 'Merge Playwright Reports'
description: 'Merge Playwright reports from different browsers and shards'
inputs:
  working-directory:
    description: 'Package directory where Playwright was run (e.g., packages/atomic)'
    required: true
  artifact-pattern:
    description: Glob-like pattern used to match the names of downloaded Playwright blob report artifacts (e.g., blob-report-shard-*)'
    required: true
  upload-artifact-name:
    description: 'Name for the uploaded artifact'
    required: true
  output-folder:
    description: 'Folder where final merged report will be generated'
    required: false
    default: 'playwright-report'

runs:
  using: composite
  steps:
    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
      with:
        path: ${{ inputs.working-directory }}/all-blob-reports
        pattern: ${{ inputs.artifact-pattern }}
        merge-multiple: true
    - name: Merge into HTML Report
      run: pnpm exec playwright merge-reports --reporter html ./all-blob-reports
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Upload HTML report
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        name: ${{ inputs.upload-artifact-name }}
        path: ${{ inputs.working-directory }}/${{ inputs.output-folder }}
        retention-days: 5
