import Head from 'next/head';
import Script from 'next/script';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Atomic + Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <atomic-search-interface id="search">
        <atomic-search-box></atomic-search-box>
        <atomic-result-list></atomic-result-list>
      </atomic-search-interface>

      <Script
        src=" https://static.cloud.coveo.com/atomic/latest/atomic.esm.js"
        type="module"
      />
      <Script>{`
      (async () => {
        await customElements.whenDefined('atomic-search-interface');
        const searchInterface = document.querySelector('#search');

        await searchInterface.initialize({
          accessToken: 'xx564559b1-0045-48e1-953c-3addd1ee4457',
          organizationId: 'searchuisamples',
        });

        searchInterface.executeFirstSearch();
      })();
      `}</Script>
    </div>
  );
}
