// This file is generated by postcss-build.cjs

const css = `.box-container{display:grid;gap:var(--atomic-facet-boxes-gap,.5rem);grid-template-columns:repeat(var(--atomic-facet-boxes-per-row,4),minmax(0,1fr));padding-left:.5rem;padding-right:.5rem}.value-box .value-label,.value-box-count{display:block;width:100%}.value-box.selected{box-shadow:0 0 0 1px var(--atomic-primary)}`;
const allCss: string[] = [css];
export default allCss;
