import {mkdir, readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {stringify} from 'yaml';
import {
  DEFAULT_A11Y_REPORT_FILENAME,
  DEFAULT_A11Y_REPORT_OUTPUT_DIR,
} from '../shared/constants.js';
import {isA11yReport} from '../shared/guards.js';
import type {A11yReport} from '../shared/types.js';
import {loadManualAuditData} from './manual-audit.js';
import {loadOverrides} from './overrides.js';
import {buildOpenAcrReport} from './report-builder.js';
import type {OpenAcrReport} from './types.js';

const LOG_PREFIX = '[json-to-openacr]';
const DEFAULT_OPENACR_OUTPUT_FILENAME = 'openacr.yaml';
const DEFAULT_OVERRIDES_FILENAME = 'a11y-overrides.json';
const DEFAULT_OVERRIDES_DIR = 'a11y';
const DEFAULT_MANUAL_AUDIT_DIR = 'a11y/reports';

async function readInputReport(inputFilePath: string): Promise<A11yReport> {
  let fileContents: string;
  try {
    fileContents = await readFile(inputFilePath, 'utf8');
  } catch (error) {
    throw new Error(
      `${LOG_PREFIX} Input report not found at ${inputFilePath}. Run the a11y tests first to generate it.`
    );
  }

  const parsed = JSON.parse(fileContents) as unknown;

  if (!isA11yReport(parsed)) {
    throw new Error(
      `${LOG_PREFIX} Invalid report structure in ${inputFilePath}. The report may have been generated by an incompatible version. Re-run the a11y tests to regenerate it.`
    );
  }

  return parsed;
}

/**
 * Options for {@link transformJsonToOpenAcr}.
 */
export interface JsonToOpenAcrOptions {
  /** Path to the input `a11y-report.json` file.
   * @default 'reports/a11y-report.json' */
  inputFile?: string;
  /** Path where the OpenACR YAML output is written.
   * @default 'reports/openacr.yaml' */
  outputFile?: string;
  /** Path to a JSON file with per-criterion conformance overrides.
   * @default 'a11y/a11y-overrides.json' */
  overridesFile?: string;
  /** Directory containing `manual-audit-*.json` baseline files.
   * @default 'a11y/reports' */
  manualAuditDir?: string;
}

/**
 * Converts an `a11y-report.json` into an OpenACR-compliant YAML document.
 *
 * Reads the input report, loads optional manual audit baselines and conformance
 * overrides, resolves per-criterion conformance using a priority chain
 * (override → manual → existing → automated), and writes the result as YAML.
 *
 * Throws if the input report is missing or invalid.
 *
 * @returns The assembled {@link OpenAcrReport} object (also written to disk as YAML).
 *
 * @example
 * ```ts
 * import { transformJsonToOpenAcr } from '@coveo/atomic-a11y';
 *
 * const report = await transformJsonToOpenAcr({
 *   inputFile: 'reports/a11y-report.json',
 *   outputFile: 'reports/openacr.yaml',
 * });
 * ```
 */
export async function transformJsonToOpenAcr(
  options: JsonToOpenAcrOptions = {}
): Promise<OpenAcrReport> {
  const inputFile = path.resolve(
    options.inputFile ??
      path.join(DEFAULT_A11Y_REPORT_OUTPUT_DIR, DEFAULT_A11Y_REPORT_FILENAME)
  );
  const outputFile = path.resolve(
    options.outputFile ??
      path.join(DEFAULT_A11Y_REPORT_OUTPUT_DIR, DEFAULT_OPENACR_OUTPUT_FILENAME)
  );
  const overridesFile = path.resolve(
    options.overridesFile ??
      path.join(DEFAULT_OVERRIDES_DIR, DEFAULT_OVERRIDES_FILENAME)
  );

  const report = await readInputReport(inputFile);

  if (!report) {
    console.warn(
      LOG_PREFIX,
      'No valid a11y report available. Skipping OpenACR generation.'
    );
    throw new Error(
      'Cannot generate OpenACR report: a11y-report.json is missing or invalid'
    );
  }

  const overrides = await loadOverrides(overridesFile);

  if (overrides.size > 0) {
    console.log(
      LOG_PREFIX,
      `Loaded ${overrides.size} conformance override(s) from ${overridesFile}.`
    );
  }

  const manualAuditDir = path.resolve(
    options.manualAuditDir ?? DEFAULT_MANUAL_AUDIT_DIR
  );
  const manualAggregates = await loadManualAuditData(manualAuditDir);

  const openAcrReport = buildOpenAcrReport(report, overrides, manualAggregates);
  // `singleQuote: true` keeps the output consistent with the committed
  // openacr.yaml baseline (single-quoted scalars), so regenerating produces a
  // minimal diff limited to real conformance changes rather than quote churn.
  const serialized = stringify(openAcrReport, {
    version: '1.1',
    singleQuote: true,
  });

  await mkdir(path.dirname(outputFile), {recursive: true});
  await writeFile(outputFile, serialized, 'utf8');

  return openAcrReport;
}
