'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type AtomicCommerceSearchBoxCustomEvent, type RedirectionPayload } from "@coveo/atomic";
import { AtomicCommerceCategoryFacet as AtomicCommerceCategoryFacetElement, defineCustomElement as defineAtomicCommerceCategoryFacet } from "@coveo/atomic/dist/components/atomic-commerce-category-facet.js";
import { AtomicCommerceFacet as AtomicCommerceFacetElement, defineCustomElement as defineAtomicCommerceFacet } from "@coveo/atomic/dist/components/atomic-commerce-facet.js";
import { AtomicCommerceFacets as AtomicCommerceFacetsElement, defineCustomElement as defineAtomicCommerceFacets } from "@coveo/atomic/dist/components/atomic-commerce-facets.js";
import { AtomicCommerceInterface as AtomicCommerceInterfaceElement, defineCustomElement as defineAtomicCommerceInterface } from "@coveo/atomic/dist/components/atomic-commerce-interface.js";
import { AtomicCommerceLoadMoreProducts as AtomicCommerceLoadMoreProductsElement, defineCustomElement as defineAtomicCommerceLoadMoreProducts } from "@coveo/atomic/dist/components/atomic-commerce-load-more-products.js";
import { AtomicCommercePager as AtomicCommercePagerElement, defineCustomElement as defineAtomicCommercePager } from "@coveo/atomic/dist/components/atomic-commerce-pager.js";
import { AtomicCommerceProductList as AtomicCommerceProductListElement, defineCustomElement as defineAtomicCommerceProductList } from "@coveo/atomic/dist/components/atomic-commerce-product-list.js";
import { AtomicCommerceProductsPerPage as AtomicCommerceProductsPerPageElement, defineCustomElement as defineAtomicCommerceProductsPerPage } from "@coveo/atomic/dist/components/atomic-commerce-products-per-page.js";
import { AtomicCommerceQuerySummary as AtomicCommerceQuerySummaryElement, defineCustomElement as defineAtomicCommerceQuerySummary } from "@coveo/atomic/dist/components/atomic-commerce-query-summary.js";
import { AtomicCommerceRefineModal as AtomicCommerceRefineModalElement, defineCustomElement as defineAtomicCommerceRefineModal } from "@coveo/atomic/dist/components/atomic-commerce-refine-modal.js";
import { AtomicCommerceRefineToggle as AtomicCommerceRefineToggleElement, defineCustomElement as defineAtomicCommerceRefineToggle } from "@coveo/atomic/dist/components/atomic-commerce-refine-toggle.js";
import { AtomicCommerceSearchBox as AtomicCommerceSearchBoxElement, defineCustomElement as defineAtomicCommerceSearchBox } from "@coveo/atomic/dist/components/atomic-commerce-search-box.js";
import { AtomicCommerceText as AtomicCommerceTextElement, defineCustomElement as defineAtomicCommerceText } from "@coveo/atomic/dist/components/atomic-commerce-text.js";
import { AtomicIcon as AtomicIconElement, defineCustomElement as defineAtomicIcon } from "@coveo/atomic/dist/components/atomic-icon.js";
import { AtomicLayoutSection as AtomicLayoutSectionElement, defineCustomElement as defineAtomicLayoutSection } from "@coveo/atomic/dist/components/atomic-layout-section.js";
import { AtomicNumericRange as AtomicNumericRangeElement, defineCustomElement as defineAtomicNumericRange } from "@coveo/atomic/dist/components/atomic-numeric-range.js";
import { AtomicResultLocalizedText as AtomicResultLocalizedTextElement, defineCustomElement as defineAtomicResultLocalizedText } from "@coveo/atomic/dist/components/atomic-result-localized-text.js";
import { AtomicTimeframe as AtomicTimeframeElement, defineCustomElement as defineAtomicTimeframe } from "@coveo/atomic/dist/components/atomic-timeframe.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type AtomicCommerceCategoryFacetEvents = NonNullable<unknown>;

export const AtomicCommerceCategoryFacet: StencilReactComponent<AtomicCommerceCategoryFacetElement, AtomicCommerceCategoryFacetEvents> = /*@__PURE__*/ createComponent<AtomicCommerceCategoryFacetElement, AtomicCommerceCategoryFacetEvents>({
    tagName: 'atomic-commerce-category-facet',
    elementClass: AtomicCommerceCategoryFacetElement,
    react: React,
    events: {} as AtomicCommerceCategoryFacetEvents,
    defineCustomElement: defineAtomicCommerceCategoryFacet
});

type AtomicCommerceFacetEvents = NonNullable<unknown>;

export const AtomicCommerceFacet: StencilReactComponent<AtomicCommerceFacetElement, AtomicCommerceFacetEvents> = /*@__PURE__*/ createComponent<AtomicCommerceFacetElement, AtomicCommerceFacetEvents>({
    tagName: 'atomic-commerce-facet',
    elementClass: AtomicCommerceFacetElement,
    react: React,
    events: {} as AtomicCommerceFacetEvents,
    defineCustomElement: defineAtomicCommerceFacet
});

type AtomicCommerceFacetsEvents = NonNullable<unknown>;

export const AtomicCommerceFacets: StencilReactComponent<AtomicCommerceFacetsElement, AtomicCommerceFacetsEvents> = /*@__PURE__*/ createComponent<AtomicCommerceFacetsElement, AtomicCommerceFacetsEvents>({
    tagName: 'atomic-commerce-facets',
    elementClass: AtomicCommerceFacetsElement,
    react: React,
    events: {} as AtomicCommerceFacetsEvents,
    defineCustomElement: defineAtomicCommerceFacets
});

type AtomicCommerceInterfaceEvents = NonNullable<unknown>;

export const AtomicCommerceInterface: StencilReactComponent<AtomicCommerceInterfaceElement, AtomicCommerceInterfaceEvents> = /*@__PURE__*/ createComponent<AtomicCommerceInterfaceElement, AtomicCommerceInterfaceEvents>({
    tagName: 'atomic-commerce-interface',
    elementClass: AtomicCommerceInterfaceElement,
    react: React,
    events: {} as AtomicCommerceInterfaceEvents,
    defineCustomElement: defineAtomicCommerceInterface
});

type AtomicCommerceLoadMoreProductsEvents = NonNullable<unknown>;

export const AtomicCommerceLoadMoreProducts: StencilReactComponent<AtomicCommerceLoadMoreProductsElement, AtomicCommerceLoadMoreProductsEvents> = /*@__PURE__*/ createComponent<AtomicCommerceLoadMoreProductsElement, AtomicCommerceLoadMoreProductsEvents>({
    tagName: 'atomic-commerce-load-more-products',
    elementClass: AtomicCommerceLoadMoreProductsElement,
    react: React,
    events: {} as AtomicCommerceLoadMoreProductsEvents,
    defineCustomElement: defineAtomicCommerceLoadMoreProducts
});

type AtomicCommercePagerEvents = { 'onAtomic/scrollToTop': EventName<CustomEvent<any>> };

export const AtomicCommercePager: StencilReactComponent<AtomicCommercePagerElement, AtomicCommercePagerEvents> = /*@__PURE__*/ createComponent<AtomicCommercePagerElement, AtomicCommercePagerEvents>({
    tagName: 'atomic-commerce-pager',
    elementClass: AtomicCommercePagerElement,
    react: React,
    events: { 'onAtomic/scrollToTop': 'atomic/scrollToTop' } as AtomicCommercePagerEvents,
    defineCustomElement: defineAtomicCommercePager
});

type AtomicCommerceProductListEvents = NonNullable<unknown>;

export const AtomicCommerceProductList: StencilReactComponent<AtomicCommerceProductListElement, AtomicCommerceProductListEvents> = /*@__PURE__*/ createComponent<AtomicCommerceProductListElement, AtomicCommerceProductListEvents>({
    tagName: 'atomic-commerce-product-list',
    elementClass: AtomicCommerceProductListElement,
    react: React,
    events: {} as AtomicCommerceProductListEvents,
    defineCustomElement: defineAtomicCommerceProductList
});

type AtomicCommerceProductsPerPageEvents = { 'onAtomic/scrollToTop': EventName<CustomEvent<any>> };

export const AtomicCommerceProductsPerPage: StencilReactComponent<AtomicCommerceProductsPerPageElement, AtomicCommerceProductsPerPageEvents> = /*@__PURE__*/ createComponent<AtomicCommerceProductsPerPageElement, AtomicCommerceProductsPerPageEvents>({
    tagName: 'atomic-commerce-products-per-page',
    elementClass: AtomicCommerceProductsPerPageElement,
    react: React,
    events: { 'onAtomic/scrollToTop': 'atomic/scrollToTop' } as AtomicCommerceProductsPerPageEvents,
    defineCustomElement: defineAtomicCommerceProductsPerPage
});

type AtomicCommerceQuerySummaryEvents = NonNullable<unknown>;

export const AtomicCommerceQuerySummary: StencilReactComponent<AtomicCommerceQuerySummaryElement, AtomicCommerceQuerySummaryEvents> = /*@__PURE__*/ createComponent<AtomicCommerceQuerySummaryElement, AtomicCommerceQuerySummaryEvents>({
    tagName: 'atomic-commerce-query-summary',
    elementClass: AtomicCommerceQuerySummaryElement,
    react: React,
    events: {} as AtomicCommerceQuerySummaryEvents,
    defineCustomElement: defineAtomicCommerceQuerySummary
});

type AtomicCommerceRefineModalEvents = NonNullable<unknown>;

export const AtomicCommerceRefineModal: StencilReactComponent<AtomicCommerceRefineModalElement, AtomicCommerceRefineModalEvents> = /*@__PURE__*/ createComponent<AtomicCommerceRefineModalElement, AtomicCommerceRefineModalEvents>({
    tagName: 'atomic-commerce-refine-modal',
    elementClass: AtomicCommerceRefineModalElement,
    react: React,
    events: {} as AtomicCommerceRefineModalEvents,
    defineCustomElement: defineAtomicCommerceRefineModal
});

type AtomicCommerceRefineToggleEvents = NonNullable<unknown>;

export const AtomicCommerceRefineToggle: StencilReactComponent<AtomicCommerceRefineToggleElement, AtomicCommerceRefineToggleEvents> = /*@__PURE__*/ createComponent<AtomicCommerceRefineToggleElement, AtomicCommerceRefineToggleEvents>({
    tagName: 'atomic-commerce-refine-toggle',
    elementClass: AtomicCommerceRefineToggleElement,
    react: React,
    events: {} as AtomicCommerceRefineToggleEvents,
    defineCustomElement: defineAtomicCommerceRefineToggle
});

type AtomicCommerceSearchBoxEvents = { 'onRedirect': EventName<AtomicCommerceSearchBoxCustomEvent<RedirectionPayload>> };

export const AtomicCommerceSearchBox: StencilReactComponent<AtomicCommerceSearchBoxElement, AtomicCommerceSearchBoxEvents> = /*@__PURE__*/ createComponent<AtomicCommerceSearchBoxElement, AtomicCommerceSearchBoxEvents>({
    tagName: 'atomic-commerce-search-box',
    elementClass: AtomicCommerceSearchBoxElement,
    react: React,
    events: { 'onRedirect': 'redirect' } as AtomicCommerceSearchBoxEvents,
    defineCustomElement: defineAtomicCommerceSearchBox
});

type AtomicCommerceTextEvents = NonNullable<unknown>;

export const AtomicCommerceText: StencilReactComponent<AtomicCommerceTextElement, AtomicCommerceTextEvents> = /*@__PURE__*/ createComponent<AtomicCommerceTextElement, AtomicCommerceTextEvents>({
    tagName: 'atomic-commerce-text',
    elementClass: AtomicCommerceTextElement,
    react: React,
    events: {} as AtomicCommerceTextEvents,
    defineCustomElement: defineAtomicCommerceText
});

type AtomicIconEvents = NonNullable<unknown>;

export const AtomicIcon: StencilReactComponent<AtomicIconElement, AtomicIconEvents> = /*@__PURE__*/ createComponent<AtomicIconElement, AtomicIconEvents>({
    tagName: 'atomic-icon',
    elementClass: AtomicIconElement,
    react: React,
    events: {} as AtomicIconEvents,
    defineCustomElement: defineAtomicIcon
});

type AtomicLayoutSectionEvents = NonNullable<unknown>;

export const AtomicLayoutSection: StencilReactComponent<AtomicLayoutSectionElement, AtomicLayoutSectionEvents> = /*@__PURE__*/ createComponent<AtomicLayoutSectionElement, AtomicLayoutSectionEvents>({
    tagName: 'atomic-layout-section',
    elementClass: AtomicLayoutSectionElement,
    react: React,
    events: {} as AtomicLayoutSectionEvents,
    defineCustomElement: defineAtomicLayoutSection
});

type AtomicNumericRangeEvents = NonNullable<unknown>;

export const AtomicNumericRange: StencilReactComponent<AtomicNumericRangeElement, AtomicNumericRangeEvents> = /*@__PURE__*/ createComponent<AtomicNumericRangeElement, AtomicNumericRangeEvents>({
    tagName: 'atomic-numeric-range',
    elementClass: AtomicNumericRangeElement,
    react: React,
    events: {} as AtomicNumericRangeEvents,
    defineCustomElement: defineAtomicNumericRange
});

type AtomicResultLocalizedTextEvents = NonNullable<unknown>;

export const AtomicResultLocalizedText: StencilReactComponent<AtomicResultLocalizedTextElement, AtomicResultLocalizedTextEvents> = /*@__PURE__*/ createComponent<AtomicResultLocalizedTextElement, AtomicResultLocalizedTextEvents>({
    tagName: 'atomic-result-localized-text',
    elementClass: AtomicResultLocalizedTextElement,
    react: React,
    events: {} as AtomicResultLocalizedTextEvents,
    defineCustomElement: defineAtomicResultLocalizedText
});

type AtomicTimeframeEvents = NonNullable<unknown>;

export const AtomicTimeframe: StencilReactComponent<AtomicTimeframeElement, AtomicTimeframeEvents> = /*@__PURE__*/ createComponent<AtomicTimeframeElement, AtomicTimeframeEvents>({
    tagName: 'atomic-timeframe',
    elementClass: AtomicTimeframeElement,
    react: React,
    events: {} as AtomicTimeframeEvents,
    defineCustomElement: defineAtomicTimeframe
});
