// This file is generated by postcss-build.cjs
import dep0 from '../../../common/facets/facet-common.css';
import dep1 from '../../../common/facets/facet-search/facet-search.css';

const css = `[part~=active-parent],[part~=parents] [part~=values]{padding-left:2.25rem}[part~=all-categories-button],[part~=parent-button]{align-items:center;display:flex;padding:.625rem .5rem .625rem 1.75rem;position:relative;text-align:left;width:100%}[part~=back-arrow]{height:1.25rem;left:.25rem;position:absolute;width:1.25rem}`;
const allCss: string[] = [...dep0, ...dep1, css];
export default allCss;
