import {NumberValue, Schema} from '@coveo/bueno';
import {
  buildNotifyTrigger,
  type NotifyTrigger,
  type NotifyTriggerState,
} from '@coveo/headless';
import {html, LitElement, nothing} from 'lit';
import {customElement, property, state} from 'lit/decorators.js';
import {map} from 'lit/directives/map.js';
import {renderHeading} from '@/src/components/common/heading';
import {ValidatePropsController} from '@/src/components/common/validate-props-controller/validate-props-controller';
import {bindStateToController} from '@/src/decorators/bind-state';
import {bindingGuard} from '@/src/decorators/binding-guard';
import {bindings} from '@/src/decorators/bindings';
import {errorGuard} from '@/src/decorators/error-guard';
import type {InitializableComponent} from '@/src/decorators/types';
import {withTailwindStyles} from '@/src/decorators/with-tailwind-styles';
import InfoIcon from '@/src/images/info.svg';
import {InitializeBindingsMixin} from '@/src/mixins/bindings-mixin';
import {AriaLiveRegionController} from '@/src/utils/accessibility-utils';
import type {Bindings} from '../atomic-search-interface/interfaces';

/**
 * The `atomic-notifications` component is responsible for displaying notifications generated by the Coveo Search API (see [Trigger](https://docs.coveo.com/en/1458)).
 *
 * @part notifications - The wrapper around the notifications.
 * @part notification - The wrapper around a single notification.
 * @part icon - The icon of the notification.
 * @part text - The text of the notification.
 */
@customElement('atomic-notifications')
@bindings()
@withTailwindStyles
export class AtomicNotifications
  extends InitializeBindingsMixin(LitElement)
  implements InitializableComponent<Bindings>
{
  private static readonly schema = new Schema({
    headingLevel: new NumberValue({min: 0, max: 6, required: false}),
  });

  @state() public bindings!: Bindings;
  @state() public error!: Error;

  /**
   * The [heading level](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements) to use above the notifications, from 1 to 6.
   */
  @property({type: Number, reflect: true, attribute: 'heading-level'})
  headingLevel = 0;

  /**
   * Specifies an icon to display at the left-end of a notification.
   *
   * - Use a value that starts with `http://`, `https://`, `./`, or `../`, to fetch and display an icon from a given location.
   * - Use a value that starts with `assets://`, to display an icon from the Atomic package.
   * - Use a stringified SVG to display it directly
   */
  @property({type: String, reflect: true}) icon?: string;

  @bindStateToController('notifyTrigger')
  @state()
  private notifyTriggerState!: NotifyTriggerState;
  public notifyTrigger!: NotifyTrigger;

  protected ariaMessage = new AriaLiveRegionController(this, 'notifications');

  constructor() {
    super();

    new ValidatePropsController(
      this,
      () => ({
        headingLevel: this.headingLevel,
      }),
      AtomicNotifications.schema,
      // TODO V4: KIT-5197 - Remove false
      false
    );
  }

  public initialize() {
    this.notifyTrigger = buildNotifyTrigger(this.bindings.engine);
  }

  private get notifications(): string[] {
    return this.notifyTriggerState?.notifications || [];
  }

  private generateAriaMessage() {
    if (this.notifications.length === 1) {
      return this.notifications[0];
    }
    return this.notifications
      .map((text, i) =>
        this.bindings.i18n.t('notification-n', {n: i + 1, text})
      )
      .join('\n');
  }

  private renderNotification(text: string) {
    return html`
      <div
        part="notification"
        class="bg-background border-neutral-dark flex items-center rounded-md border p-6 shadow-lg"
      >
        <atomic-icon
          icon=${this.icon ?? InfoIcon}
          part="icon"
          class="text-neutral-dark mr-6 h-7 w-7"
        ></atomic-icon>
        <span part="text" class="text-on-background text-base leading-5">
          ${text}
        </span>
      </div>
    `;
  }

  private renderNotifications() {
    return html`
      <div part="notifications" class="flex flex-col gap-4">
        ${map(this.notifications, (text) => this.renderNotification(text))}
      </div>
    `;
  }

  @bindingGuard()
  @errorGuard()
  render() {
    if (!this.notifications.length) {
      return html`${nothing}`;
    }

    this.ariaMessage.message = this.generateAriaMessage();

    return html`
      ${renderHeading({
        props: {level: this.headingLevel, class: 'sr-only'},
      })(html`${this.bindings.i18n.t('notifications')}`)}
      ${this.renderNotifications()}
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'atomic-notifications': AtomicNotifications;
  }
}
