import {BooleanValue, Schema} from '@coveo/bueno';
import {
  AutomaticFacetGenerator,
  AutomaticFacetGeneratorState,
  SearchStatus,
  SearchStatusState,
  buildAutomaticFacetGenerator,
  buildSearchStatus,
} from '@coveo/headless';
import {Component, Prop, State, h} from '@stencil/core';
import {
  BindStateToController,
  InitializableComponent,
  InitializeBindings,
} from '../../../../utils/initialization-utils';
import {FacetPlaceholder} from '../../../common/facets/facet-placeholder/facet-placeholder';
import {Bindings} from '../../atomic-search-interface/atomic-search-interface';

/**
 * @beta - This component is part of the automatic facets feature.
 * Automatic facets are currently in beta testing and should be available soon.
 *
 * The `atomic-automatic-facet-generator` is a component that renders the facets from
 * the automatic facets feature. It dynamically creates multiple atomic-automatic-facet
 * components based on the desiredCount prop. Automatic facets are generated by the index
 * in response to the search query.
 */
@Component({
  tag: 'atomic-automatic-facet-generator',
  styleUrl: 'atomic-automatic-facet-generator.pcss',
  shadow: false,
})
export class AtomicAutomaticFacetGenerator implements InitializableComponent {
  @InitializeBindings() public bindings!: Bindings;
  @State() public error!: Error;

  public automaticFacetGenerator!: AutomaticFacetGenerator;
  @BindStateToController('automaticFacetGenerator')
  @State()
  private automaticFacetGeneratorState!: AutomaticFacetGeneratorState;

  public searchStatus!: SearchStatus;
  @BindStateToController('searchStatus')
  @State()
  public searchStatusState!: SearchStatusState;

  /**
   * @beta - This prop is part of the automatic facets feature.
   * Automatic facets are currently in beta testing and should be available soon.
   *
   * The desired count of automatic facets.
   * Must be a positive integer.
   */
  @Prop() public desiredCount!: number;

  /**
   * @beta - This prop is part of the automatic facets feature.
   * Automatic facets are currently in beta testing and should be available soon.
   *
   * Specifies whether the automatic facets are collapsed.
   */
  @Prop() public areCollapsed = true;

  /**
   * @beta - This prop is part of the automatic facets feature.
   * Automatic facets are currently in beta testing and should be available soon.
   *
   * The desired number of automatically generated facet values.
   * Must be a positive integer.
   */
  @Prop() public numberOfValues = 8;

  public initialize() {
    this.validateProps();
    this.searchStatus = buildSearchStatus(this.bindings.engine);
    this.automaticFacetGenerator = buildAutomaticFacetGenerator(
      this.bindings.engine,
      {
        options: {
          desiredCount: this.desiredCount,
          numberOfValues: this.numberOfValues,
        },
      }
    );
  }

  private validateProps() {
    new Schema({
      areCollapsed: new BooleanValue({default: true, required: false}),
    }).validate({
      areCollapsed: this.areCollapsed,
    });
  }

  public render() {
    const automaticFacets =
      this.automaticFacetGeneratorState.automaticFacets.map((facet) => {
        return (
          <atomic-automatic-facet
            key={facet.state.field}
            field={facet.state.field}
            facetId={facet.state.field}
            facet={facet}
            searchStatus={this.searchStatus}
            isCollapsed={this.areCollapsed}
          ></atomic-automatic-facet>
        );
      });
    if (!this.searchStatus.state.firstSearchExecuted) {
      return Array.from({length: this.desiredCount}, () => (
        <FacetPlaceholder
          numberOfValues={this.numberOfValues}
          isCollapsed={this.areCollapsed}
        />
      ));
    }

    return automaticFacets;
  }
}
