name: Label PR with Areas

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    environment: pr-workflows

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          sparse-checkout: .areas

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          app-id: ${{ vars.CODE_AREAS_APP_ID }}
          private-key: ${{ secrets.CODE_AREAS_PEM }}

      - uses: coveooss/areas@b3ca247fb24809a01a25dc009f6754dd5c06f314 # v0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          command: label-pr
