name: Label PR with Areas

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    environment: pr-workflows

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          sparse-checkout: .areas

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ vars.CODE_AREAS_APP_ID }}
          private-key: ${{ secrets.CODE_AREAS_PEM }}

      - uses: coveooss/areas@b3ca247fb24809a01a25dc009f6754dd5c06f314 # v0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          command: label-pr
