name: Label PR with Areas

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    environment: pr-workflows

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          sparse-checkout: .areas

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ vars.CODE_AREAS_APP_ID }}
          private-key: ${{ secrets.CODE_AREAS_PEM }}

      - uses: coveooss/areas@b3ca247fb24809a01a25dc009f6754dd5c06f314 # v0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          command: label-pr
