name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  ci:
    name: CI
    runs-on: [coveo, linux, x64, eks]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install
        uses: ./.github/actions/install-dependencies
      - name: Lint
        uses: ./.github/actions/lint
      - name: Build
        uses: ./.github/actions/build-packages
      - name: Clean tree check
        uses: ./.github/actions/clean-tree-check
      - name: Tests
        uses: ./.github/actions/test
  functional-tests:
    name: "Functional tests"
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install
        uses: ./.github/actions/install-dependencies
      - name: Install Playwright Browsers
        run: pnpm -r playwright:install
      - name: Functional tests
        uses: ./.github/actions/test-functional
        with:
          analytics_key: ${{ secrets.ANALYTICS_KEY }}
  my-tag:
    name: "My tag"
    needs: [functional-tests]
    if: github.ref_name == 'main'
    runs-on: [coveo, linux, x64, eks]
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: tag
        run: echo "tag=$(git tag --contains | head -n 1)" >> "$GITHUB_OUTPUT"
  version:
    name: Bump versions
    needs: [my-tag]
    if: ${{ !needs.my-tag.outputs.tag }}
    runs-on: [coveo, linux, x64, eks]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.COMMIT_TOKEN }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install
        uses: ./.github/actions/install-dependencies
      - name: Git Setup
        uses: ./.github/actions/git-setup
      - name: Version Bump
        uses: ./.github/actions/version-bump
  release:
    name: Release
    needs: [my-tag]
    if: needs.my-tag.outputs.tag
    runs-on: [coveo, linux, x64, eks]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install
        uses: ./.github/actions/install-dependencies
      - name: Build
        uses: ./.github/actions/build-packages
      - name: Publish
        uses: ./.github/actions/publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          COMMIT_HASH: ${{ github.sha }}
