name: Publish Preview Packages
on:
  pull_request:

permissions: {}

jobs:
  publish-preview:
    name: "Publish Preview Packages"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup
        with:
          load-cache: "false"
      - name: Publish to pkg.pr.new
        run: |
          pnpm dlx pkg-pr-new publish --pnpm \
            './packages/atomic' \
            './packages/atomic-hosted-page' \
            './packages/atomic-legacy' \
            './packages/atomic-react' \
            './packages/auth' \
            './packages/bueno' \
            './packages/create-atomic' \
            './packages/create-atomic-component' \
            './packages/create-atomic-component-project' \
            './packages/create-atomic-result-component' \
            './packages/create-atomic-rollup-plugin' \
            './packages/headless' \
            './packages/headless-react' \
            './packages/shopify'
