name: Mirror Playwright Docker Image from Microsoft Container Registry
on:
  push:
    branches: [main]
    paths:
      - '.github/playwright-caching.yml'
permissions:
  contents: read

jobs:
  mirror-playwright-image:
    runs-on: ubuntu-latest
    container: gcr.io/go-containerregistry/crane@sha256:2b6828477d3cdf9999e84515f4e2019c7e6550e4d7fe9b5b37542bd25c9bc201

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      PLAYWRIGHT_VERSION: v1.57.0-noble
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Log in to the GitHub Container registry
        env:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: crane auth login ${{env.registry}} -u ${username} -p ${password}
      - name: Mirror Playwright Docker Image
        run: crane copy mcr.microsoft.com/playwright:${{ env.PLAYWRIGHT_VERSION }} ghcr.io/coveo/ui-kit-playwright:${{ env.PLAYWRIGHT_VERSION }}
