name: Deploy PR to CDN (commits/)
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-cdn:
    name: Build CDN
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: ./.github/actions/build-cdn
        with:
          commit-sha: ${{ github.sha }}

  commit-artifact-upload:
    name: Upload commit artifacts to S3
    needs: build-cdn
    runs-on: ubuntu-latest
    environment: 'Prerelease (CDN)'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: ./.github/actions/setup
        with:
          skip-build: 'true'
          load-cache: 'false'
      - name: Trigger commit artifact upload on ui-kit-cd
        run: node ./scripts/deploy/trigger-commit-upload.mjs
        env:
          GH_TOKEN: ${{ secrets.UI_KIT_CD_DISPATCHER }}
          CHANNELS: ''
