name: Release latest

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment in which to run the job
      region:
        description: The region in which to run the job
      package:
        description: The package name
      job:
        description: The name of the job (as defined in the deployment config)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Promote npm packages to latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        shell: bash
        run: npm run npm:tag:latest

      - name: Notify docs
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        shell: bash
        run: |
          pnpm i @octokit/rest --filter @coveo/relay
          npm run docs:notify
