name: Release

on:
  push:
    tags:
      - "**/v**"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: [coveo, linux, x64, ec2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        uses: ./.github/actions/build-packages
      - name: Publish
        uses: ./.github/actions/publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          COMMIT_HASH: ${{ github.sha }}
