name: Renovate Production Changeset

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  debug:
    name: Debug trigger
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          echo "event: ${{ github.event_name }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "pr.head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "base.ref: ${{ github.event.pull_request.base.ref }}"
