name: Release beta

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment in which to run the job
      region:
        description: The region in which to run the job
      package:
        description: The package name
      job:
        description: The name of the job (as defined in the deployment config)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Promote npm packages to beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        shell: bash
        run: npm run npm:tag:beta
