name: VersionBump

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  version:
    name: Bump versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.COMMIT_TOKEN }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Git Setup
        uses: ./.github/actions/git-setup
      - name: Version Bump
        uses: ./.github/actions/version-bump
