// This file is generated by postcss-build.cjs

const css = `.js-focus-visible input[type=text].focus-visible~.search-icon,input[type=text].focus-visible.js-focus-visible~.search-icon{color:var(--atomic-primary)}input[type=text]:focus-visible~.search-icon{color:var(--atomic-primary)}input[type=text]:hover~.search-icon{color:var(--atomic-primary-light)}.search-icon atomic-icon{height:var(--atomic-facet-search-icon-size,.75rem);width:var(--atomic-facet-search-icon-size,.75rem)}.search-clear-button atomic-icon{height:var(--atomic-facet-search-clear-icon-size,.625rem);width:var(--atomic-facet-search-clear-icon-size,.625rem)}`;
const allCss: string[] = [css];
export default allCss;
